-- AUTOGENERATED from Kopis/Properties/CoerceBridge10.lean by `make generated`.  Do not edit.
-- See NEON_VERIFICATION_PLAN.md phase E: the serial proof, with the extracted
-- constants and this stack's namespace renamed, and nothing else changed.
import Kopis.Bits.Stream
import Kopis.Neon.Properties.RingArith
import Kopis.Neon.Properties.Serialize
open Aeneas Aeneas.Std Result RustKopisNeon
open scoped BigOperators
namespace Kopis.Neon.Properties

open Kopis.Properties (streamBit streamNat streamNat_zero streamNat_succ streamBit_le_one streamNat_lt streamNat_split lor_add_of_lt lor_mul_of_lt sum_testBit_eq_mod streamNat_byte streamByte streamByte_lt sum_base256 testBit_sum_bytes streamNat_of_byteWindow cbdX cbdX_le testBit_streamNat cbdX_eq_bitSum streamNat_mod streamNat_shiftRight cbdX_eq_bitSum_of_le cbdU16)

open arithmetic.ring_arith (RingElem)

/-! # Modulus bridge: `Polynomial.coerce` (2¹⁶ → 2¹⁰) is a ring homomorphism.

The Rust pipeline computes `mul_transpose` at the physical modulus `2¹⁶`, but the spec
`matVecMul` works at `2¹⁰`.  These lemmas let us push the `2¹⁶ → 2¹⁰` reduction through
`+` and `*`, matching the two computations. -/

/-- The coefficient reduction `x ↦ x.val` is exactly the ring hom `ZMod.castHom`. -/
theorem castHom_eq_val10 (x : ZMod (2 ^ 16)) :
    (ZMod.castHom (show (2 ^ 10 : ℕ) ∣ 2 ^ 16 by norm_num) (ZMod (2 ^ 10))) x
      = (x.val : ZMod (2 ^ 10)) := by
  rw [ZMod.castHom_apply, ZMod.natCast_val]

theorem coerce_getElem10 (a : Spec.Kopis.Polynomial (2 ^ 16)) (i : ℕ) (hi : i < 256) :
    (Spec.Kopis.Polynomial.coerce a (2 ^ 10))[i]'hi = ((a[i]'hi).val : ZMod (2 ^ 10)) := by
  simp only [Spec.Kopis.Polynomial.coerce, Vector.getElem_map]

theorem coerce_getElem!10 (a : Spec.Kopis.Polynomial (2 ^ 16)) (i : ℕ) (hi : i < 256) :
    (Spec.Kopis.Polynomial.coerce a (2 ^ 10))[i]! = ((a[i]!).val : ZMod (2 ^ 10)) := by
  rw [getElem!_pos _ i hi, getElem!_pos a i hi, coerce_getElem10]

/-- `coerce` distributes over polynomial addition. -/
theorem coerce_add10 (a b : Spec.Kopis.Polynomial (2 ^ 16)) :
    Spec.Kopis.Polynomial.coerce (a + b) (2 ^ 10)
      = Spec.Kopis.Polynomial.coerce a (2 ^ 10) + Spec.Kopis.Polynomial.coerce b (2 ^ 10) := by
  apply Vector.ext; intro p hp
  rw [coerce_getElem10 _ p hp,
    show (Spec.Kopis.Polynomial.coerce a (2 ^ 10) + Spec.Kopis.Polynomial.coerce b (2 ^ 10))
        = Spec.Kopis.Polynomial.add (Spec.Kopis.Polynomial.coerce a (2 ^ 10))
            (Spec.Kopis.Polynomial.coerce b (2 ^ 10)) from rfl,
    show (a + b) = Spec.Kopis.Polynomial.add a b from rfl]
  simp only [Spec.Kopis.Polynomial.add, Vector.getElem_zipWith]
  rw [← castHom_eq_val10, map_add, castHom_eq_val10, castHom_eq_val10, coerce_getElem10 a p hp,
    coerce_getElem10 b p hp]

set_option maxHeartbeats 1000000 in
/-- `coerce` distributes over the negacyclic polynomial product. -/
theorem coerce_mul10 (a b : Spec.Kopis.Polynomial (2 ^ 16)) :
    Spec.Kopis.Polynomial.coerce (a * b) (2 ^ 10)
      = Spec.Kopis.Polynomial.coerce a (2 ^ 10) * Spec.Kopis.Polynomial.coerce b (2 ^ 10) := by
  apply Vector.ext; intro p hp
  set f := ZMod.castHom (show (2 ^ 10 : ℕ) ∣ 2 ^ 16 by norm_num) (ZMod (2 ^ 10)) with hf
  rw [coerce_getElem10 _ p hp, show (a * b) = Spec.Kopis.Polynomial.mul a b from rfl, mul_get a b p hp,
    show (Spec.Kopis.Polynomial.coerce a (2 ^ 10) * Spec.Kopis.Polynomial.coerce b (2 ^ 10))
        = Spec.Kopis.Polynomial.mul (Spec.Kopis.Polynomial.coerce a (2 ^ 10))
            (Spec.Kopis.Polynomial.coerce b (2 ^ 10)) from rfl,
    mul_get _ _ p hp, ← castHom_eq_val10]
  simp only [convCoeff, map_sum]
  refine Finset.sum_congr rfl fun i hi => Finset.sum_congr rfl fun j hj => ?_
  have hi256 : i < 256 := Finset.mem_range.mp hi
  have hj256 : j < 256 := Finset.mem_range.mp hj
  have hfa : f (a[i]!) = (Spec.Kopis.Polynomial.coerce a (2 ^ 10))[i]! := by
    rw [castHom_eq_val10, coerce_getElem!10 a i hi256]
  have hfb : f (b[j]!) = (Spec.Kopis.Polynomial.coerce b (2 ^ 10))[j]! := by
    rw [castHom_eq_val10, coerce_getElem!10 b j hj256]
  simp only [convContrib]
  by_cases hij : (i + j) % 256 = p
  · rw [if_pos hij, if_pos hij]
    by_cases hlt : i + j < 256
    · rw [if_pos hlt, if_pos hlt, map_mul, hfa, hfb]
    · rw [if_neg hlt, if_neg hlt, map_neg, map_mul, hfa, hfb]
  · rw [if_neg hij, if_neg hij, map_zero]

/-- `coerce` sends `0` to `0`. -/
theorem coerce_zero10 : Spec.Kopis.Polynomial.coerce (0 : Spec.Kopis.Polynomial (2 ^ 16)) (2 ^ 10)
    = (0 : Spec.Kopis.Polynomial (2 ^ 10)) := by
  apply Vector.ext; intro p hp
  rw [coerce_getElem10 _ p hp]
  show (((Spec.Kopis.Polynomial.zero (2 ^ 16))[p]'hp).val : ZMod (2 ^ 10))
      = (Spec.Kopis.Polynomial.zero (2 ^ 10))[p]'hp
  simp only [Spec.Kopis.Polynomial.zero, Vector.getElem_replicate, ZMod.val_zero, Nat.cast_zero]

/-- `coerce` as a bundled additive homomorphism `Polynomial 2¹⁶ →+ Polynomial 2¹⁰`. -/
def coerceHom10 : Spec.Kopis.Polynomial (2 ^ 16) →+ Spec.Kopis.Polynomial (2 ^ 10) where
  toFun r := Spec.Kopis.Polynomial.coerce r (2 ^ 10)
  map_zero' := coerce_zero10
  map_add' := coerce_add10

/-- `coerce` distributes over a finite sum. -/
theorem coerce_sum10 {ι : Type*} (s : Finset ι) (f : ι → Spec.Kopis.Polynomial (2 ^ 16)) :
    Spec.Kopis.Polynomial.coerce (∑ i ∈ s, f i) (2 ^ 10)
      = ∑ i ∈ s, Spec.Kopis.Polynomial.coerce (f i) (2 ^ 10) :=
  map_sum coerceHom10 f s

end Kopis.Neon.Properties
