-- AUTOGENERATED from Kopis/Properties/MatVecMul.lean by `make generated`.  Do not edit.
-- See NEON_VERIFICATION_PLAN.md phase E: the serial proof, with the extracted
-- constants and this stack's namespace renamed, and nothing else changed.
import Kopis.Bits.Stream
import Kopis.Neon.Properties.GenMatrix
open Aeneas Aeneas.Std Result RustKopisNeon
open scoped BigOperators
namespace Kopis.Neon.Properties

open Kopis.Properties (streamBit streamNat streamNat_zero streamNat_succ streamBit_le_one streamNat_lt streamNat_split lor_add_of_lt lor_mul_of_lt sum_testBit_eq_mod streamNat_byte streamByte streamByte_lt sum_base256 testBit_sum_bytes streamNat_of_byteWindow cbdX cbdX_le testBit_streamNat cbdX_eq_bitSum streamNat_mod streamNat_shiftRight cbdX_eq_bitSum_of_le cbdU16)

set_option maxHeartbeats 1000000

/-- Row `i₀` of `A * v`. -/
theorem matVecMul_get {m ℓ : ℕ} (A : Spec.Kopis.PolyMatrix m ℓ) (v : Spec.Kopis.PolyVector m ℓ)
    (i₀ : ℕ) (hi₀ : i₀ < ℓ) :
    ((A * v))[i₀]'hi₀
      = ∑ j : Fin ℓ, A ⟨i₀, hi₀⟩ j * v[j.val]'j.isLt := by
  simp only [HMul.hMul, Vector.getElem_ofFn]; rfl

end Kopis.Neon.Properties
