-- AUTOGENERATED from Kopis/Properties/NttCrtBlock.lean by `make generated`.  Do not edit.
-- See NEON_VERIFICATION_PLAN.md phase E: the serial proof, with the extracted
-- constants and this stack's namespace renamed, and nothing else changed.
/-
  # Kopis/Properties/NttCrtBlock.lean — the two transforms of one residue block.

  `ntt_block` is eight Cooley-Tukey levels with a Barrett pass after the third, the sixth and the
  eighth; `invntt_block` is eight Gentleman-Sande levels with a Barrett pass after every second,
  then the `256⁻¹·2³²` scaling.  This file chains `Kopis/Properties/NttCrtLevel.lean`'s level
  specs through those schedules, carrying `State` for the value and a magnitude bound for the
  exactness, and instantiates the result at `q₁ = 7681` and `q₂ = 10753`.

  ## Why the growth argument is written the way it is

  `src/backend/crt.rs` gives a crude per-level budget of `0.75q`, which for a run of three
  Cooley-Tukey levels from `q/2` predicts `2.75q` — inside an `i16` lane for both primes, so the
  portable schedule (runs of 3, 3, 2) is covered by it and does *not* need the interval
  propagation the AVX2 schedule rests on.  What it does need is the **sharp** Montgomery bound
  `2¹⁶·|c| ≤ |a|·|z| + 2¹⁵·q` rather than `|c| < q`: with `|c| < q` a three-level run reaches
  `3.5q = 37 635` for `q₂`, which overflows.  The sharp form makes each level's increment
  proportional to the bound already reached, and a single `Bt` per prime covers all three levels
  of a run — which is why the chain below carries one constant rather than three.

  The Gentleman-Sande side is different: its sum path *doubles*, so a run of two levels takes
  `q/2` to `2q`, and that is the whole reason the inverse schedule re-centres twice as often.
-/
import Kopis.Bits.Stream
import Kopis.Neon.Properties.NttCrtLevel

open Aeneas Aeneas.Std Result
open RustKopisNeon

namespace Kopis.Neon.Properties

open Kopis.Properties (streamBit streamNat streamNat_zero streamNat_succ streamBit_le_one streamNat_lt streamNat_split lor_add_of_lt lor_mul_of_lt sum_testBit_eq_mod streamNat_byte streamByte streamByte_lt sum_base256 testBit_sum_bytes streamNat_of_byteWindow cbdX cbdX_le testBit_streamNat cbdX_eq_bitSum streamNat_mod streamNat_shiftRight cbdX_eq_bitSum_of_le cbdU16)

open Kopis.CrtArith Kopis.Avx2.NttAlg Kopis.CrtZeta

set_option maxHeartbeats 1000000

/-! ## One level, as a step of the invariant -/

/-- One Cooley-Tukey level refines the CRT invariant by one layer and adds at most `Bt` to the
magnitude. -/
theorem ct_step {q : ℕ} {nb lenv : ℕ}
    (b : Array I16 256#usize) (SECOND : Bool) (LEN k : Usize) (qv : I16)
    (Q Zb B Bt : ℤ) (Rinv : ZMod q) (ζ : ℕ → ZMod q) (f : ℕ → ZMod q)
    (hlen : LEN.val = lenv) (hlpos : 0 < lenv) (hnb : nb * (2 * lenv) = 256)
    (hnb1 : 1 ≤ nb) (hnb2 : 2 * nb ≤ 256) (hk : k.val + 1 = nb)
    (hqSel : backend.crt.q SECOND = ok qv)
    (hQq : (q : ℤ) = Q) (hqv : qv.val = Q) (hQpos : 0 < Q) (hQlt : Q ≤ 2 ^ 15)
    (hRinv : (2 ^ 16 : ZMod q) * Rinv = 1)
    (hzeta : ZetaOK SECOND Q Zb Rinv ζ) (hZb : 0 ≤ Zb)
    (hsq : ∀ k, 1 ≤ k → k < 256 → ζ k ^ 2 = cst ζ k)
    (hB0 : 0 ≤ B) (hBt0 : 0 ≤ Bt) (hmont : B * Zb < 2 ^ 15 * Q)
    (hBt : B * Zb + 2 ^ 15 * Q ≤ 2 ^ 16 * Bt) (hfit : B + Bt ≤ 32767)
    (hB : ∀ c, c < 256 → |bZ b c| ≤ B)
    (hst : State ζ nb (2 * lenv) 1 f (bR q b)) :
    arithmetic.ntt_crt.ct_level LEN SECOND b k
      ⦃ (rk : Array I16 256#usize × Usize) =>
          State ζ (2 * nb) lenv 1 f (bR q rk.1)
          ∧ (∀ c, c < 256 → |bZ rk.1 c| ≤ B + Bt)
          ∧ rk.2.val = 2 * nb - 1 ⦄ := by
  apply WP.spec_mono (ct_level_spec (nb := nb) (lenv := lenv) b SECOND LEN k qv Q Zb B Bt Rinv ζ
    hlen hlpos hnb hk hqSel hQq hqv hQpos hQlt hRinv hzeta hZb hB0 hBt0 hmont hBt hfit hB)
  rintro rk ⟨hV, hBd, hK⟩
  exact ⟨State_ct hsq hnb1 hnb2 hst hV, hBd, hK⟩

/-- One Gentleman-Sande level merges two layers, doubles the sum path, and doubles the invariant's
scale factor. -/
theorem gs_step {q : ℕ} {nb lenv : ℕ}
    (b : Array I16 256#usize) (SECOND : Bool) (LEN k : Usize) (qv qiv : I16)
    (Q Zb B Bt B2 : ℤ) (Rinv : ZMod q) (ζ : ℕ → ZMod q) (f : ℕ → ZMod q) (cs : ZMod q)
    (hlen : LEN.val = lenv) (hlpos : 0 < lenv) (hnb : nb * (2 * lenv) = 256)
    (hnb1 : 1 ≤ nb) (hnb2 : 2 * nb ≤ 256) (hpow : ∃ j, j < 8 ∧ nb = 2 ^ j)
    (hk : k.val = 2 * nb)
    (hqSel : backend.crt.q SECOND = ok qv) (hqiSel : backend.crt.qinv SECOND = ok qiv)
    (hQq : (q : ℤ) = Q) (hqv : qv.val = Q) (hQpos : 0 < Q) (hQlt : Q ≤ 2 ^ 15)
    (hRinv : (2 ^ 16 : ZMod q) * Rinv = 1)
    (hqiv : (2 ^ 16 : ℤ) ∣ (qiv.val * Q - 1))
    (hzeta : ZetaVal SECOND Zb Rinv ζ) (hZb : 0 ≤ Zb) (hZb32 : Zb ≤ 32767)
    (hsq : ∀ k, 1 ≤ k → k < 256 → ζ k ^ 2 = cst ζ k)
    (hpair : ∀ nb b : ℕ, (∃ j, j < 8 ∧ nb = 2 ^ j) → b < nb →
      ζ (nb + b) * ζ (2 * nb - 1 - b) = -1)
    (hB0 : 0 ≤ B) (hBt0 : 0 ≤ Bt) (hmont : 2 * B * Zb < 2 ^ 15 * Q)
    (hBt : 2 * B * Zb + 2 ^ 15 * Q ≤ 2 ^ 16 * Bt)
    (hdbl : 2 * B ≤ B2) (hBtB2 : Bt ≤ B2) (hfit : B2 ≤ 32767)
    (hB : ∀ c, c < 256 → |bZ b c| ≤ B)
    (hst : State ζ (2 * nb) lenv cs f (bR q b)) :
    arithmetic.ntt_crt.gs_level LEN SECOND b k
      ⦃ (rk : Array I16 256#usize × Usize) =>
          State ζ nb (2 * lenv) (2 * cs) f (bR q rk.1)
          ∧ (∀ c, c < 256 → |bZ rk.1 c| ≤ B2)
          ∧ rk.2.val = nb ⦄ := by
  apply WP.spec_mono (gs_level_spec (nb := nb) (lenv := lenv) b SECOND LEN k qv qiv Q Zb B Bt B2
    Rinv ζ hlen hlpos hnb hk hqSel hqiSel hQq hqv hQpos hQlt hRinv hqiv hzeta hZb hZb32 hB0 hBt0
    hmont hBt hdbl hBtB2 hfit hB)
  rintro rk ⟨hV, hBd, hK⟩
  exact ⟨State_gs hsq hpair hnb1 hnb2 hpow hst hV, hBd, hK⟩

/-- `State` only ever reads indices below 256, so a Barrett pass — which changes no residue —
carries it across. -/
theorem State_congr {q nb mm : ℕ} {ζ : ℕ → ZMod q} {cs : ZMod q} {f a a' : ℕ → ZMod q}
    (hnm : nb * mm = 256) (h : ∀ c, c < 256 → a' c = a c) (hst : State ζ nb mm cs f a) :
    State ζ nb mm cs f a' := by
  intro bb hbb r hr
  have hidx : bb * mm + r < 256 := by
    have h1 : bb + 1 ≤ nb := hbb
    calc bb * mm + r < bb * mm + mm := by omega
      _ = (bb + 1) * mm := by ring
      _ ≤ nb * mm := Nat.mul_le_mul_right mm h1
      _ = 256 := hnm
  rw [h (bb * mm + r) hidx]
  exact hst bb hbb r hr

/-! ## The forward transform of one block

Runs of three, three and two Cooley-Tukey levels, each followed by a Barrett pass.  A single `Bt`
covers every level of every run: the bound is largest at the end of a run, so the hypotheses are
stated there and monotonicity supplies the rest. -/

theorem ntt_block_spec {q : ℕ} (SECOND : Bool) (b : Array I16 256#usize) (qv m : I16)
    (Q Zb M B0 Bt : ℤ) (Rinv : ZMod q) (ζ f : ℕ → ZMod q)
    (hqSel : backend.crt.q SECOND = ok qv) (hmSel : backend.crt.barrett_m SECOND = ok m)
    (hQq : (q : ℤ) = Q) (hqv : qv.val = Q) (hm : m.val = M)
    (hQpos : 0 < Q) (hQlt14 : Q < 2 ^ 14) (hQodd : ¬ (2 ∣ Q))
    (hMpos : 0 < M) (hMlt : M < 2 ^ 15) (hD : |2 ^ 27 - Q * M| ≤ 2047)
    (hRinv : (2 ^ 16 : ZMod q) * Rinv = 1)
    (hzeta : ZetaOK SECOND Q Zb Rinv ζ) (hZb : 0 ≤ Zb)
    (hsq : ∀ k, 1 ≤ k → k < 256 → ζ k ^ 2 = cst ζ k)
    (hB00 : 0 ≤ B0) (hBt0 : 0 ≤ Bt) (hQB0 : Q ≤ 2 * B0 + 1)
    (hmont3 : (B0 + 2 * Bt) * Zb < 2 ^ 15 * Q)
    (hBt3 : (B0 + 2 * Bt) * Zb + 2 ^ 15 * Q ≤ 2 ^ 16 * Bt)
    (hfit3 : B0 + 3 * Bt ≤ 32767)
    (hB : ∀ c, c < 256 → |bZ b c| ≤ B0)
    (hst : State ζ 1 256 1 f (bR q b)) :
    arithmetic.ntt_crt.ntt_block SECOND b
      ⦃ (r : Array I16 256#usize) =>
          (∀ c, c < 256 → 2 * |bZ r c| < Q) ∧ State ζ 256 1 1 f (bR q r) ⦄ := by
  have hQlt : Q ≤ 2 ^ 15 := by omega
  -- monotonicity: the three levels of a run are all covered by the hypotheses at the top
  have hmono : ∀ B : ℤ, 0 ≤ B → B ≤ B0 + 2 * Bt →
      B * Zb < 2 ^ 15 * Q ∧ B * Zb + 2 ^ 15 * Q ≤ 2 ^ 16 * Bt ∧ B + Bt ≤ 32767 := by
    intro B hB0' hBle
    have h1 : B * Zb ≤ (B0 + 2 * Bt) * Zb := by nlinarith
    exact ⟨by linarith, by linarith, by linarith⟩
  -- a Barrett pass returns to `B0`
  have hbar : ∀ (r : Array I16 256#usize), (∀ c, c < 256 → 2 * |bZ r c| < Q) →
      ∀ c, c < 256 → |bZ r c| ≤ B0 := by
    intro r h c hc; have := h c hc; omega
  unfold arithmetic.ntt_crt.ntt_block
  -- level 1: 1 block of 256
  apply WP.spec_bind (ct_step (nb := 1) (lenv := 128) b SECOND 128#usize 0#usize qv Q Zb B0 Bt
    Rinv ζ f rfl (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by simp)
    hqSel hQq hqv hQpos hQlt hRinv hzeta hZb hsq hB00 hBt0
    (hmono B0 hB00 (by linarith)).1 (hmono B0 hB00 (by linarith)).2.1
    (hmono B0 hB00 (by linarith)).2.2 hB hst)
  rintro ⟨b1, k1⟩ ⟨hs1, hd1, hk1⟩
  simp only at hs1 hd1 hk1
  -- level 2: 2 blocks of 128
  apply WP.spec_bind (ct_step (nb := 2) (lenv := 64) b1 SECOND 64#usize k1 qv Q Zb (B0 + Bt) Bt
    Rinv ζ f rfl (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by omega)
    hqSel hQq hqv hQpos hQlt hRinv hzeta hZb hsq (by linarith) hBt0
    (hmono (B0 + Bt) (by linarith) (by linarith)).1
    (hmono (B0 + Bt) (by linarith) (by linarith)).2.1
    (hmono (B0 + Bt) (by linarith) (by linarith)).2.2 hd1 hs1)
  rintro ⟨b2, k2⟩ ⟨hs2, hd2, hk2⟩
  simp only at hs2 hd2 hk2
  -- level 3: 4 blocks of 64
  apply WP.spec_bind (ct_step (nb := 4) (lenv := 32) b2 SECOND 32#usize k2 qv Q Zb (B0 + 2 * Bt) Bt
    Rinv ζ f rfl (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by omega)
    hqSel hQq hqv hQpos hQlt hRinv hzeta hZb hsq (by linarith) hBt0
    (hmono (B0 + 2 * Bt) (by linarith) (by linarith)).1
    (hmono (B0 + 2 * Bt) (by linarith) (by linarith)).2.1
    (hmono (B0 + 2 * Bt) (by linarith) (by linarith)).2.2
    (by intro c hc; have := hd2 c hc; linarith) hs2)
  rintro ⟨b3, k3⟩ ⟨hs3, hd3, hk3⟩
  simp only at hs3 hd3 hk3
  apply WP.spec_bind (barrett_block_spec (q := q) SECOND b3 qv m Q M hqSel hmSel hQq hqv hm
    hQpos hQlt14 hQodd hMpos hMlt hD)
  rintro b4 ⟨hv4, hb4⟩
  have hs4 : State ζ 8 32 1 f (bR q b4) := State_congr (by norm_num) hv4 hs3
  -- level 4: 8 blocks of 32
  apply WP.spec_bind (ct_step (nb := 8) (lenv := 16) b4 SECOND 16#usize k3 qv Q Zb B0 Bt
    Rinv ζ f rfl (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by omega)
    hqSel hQq hqv hQpos hQlt hRinv hzeta hZb hsq hB00 hBt0
    (hmono B0 hB00 (by linarith)).1 (hmono B0 hB00 (by linarith)).2.1
    (hmono B0 hB00 (by linarith)).2.2 (hbar b4 hb4) hs4)
  rintro ⟨b5, k5⟩ ⟨hs5, hd5, hk5⟩
  simp only at hs5 hd5 hk5
  -- level 5: 16 blocks of 16
  apply WP.spec_bind (ct_step (nb := 16) (lenv := 8) b5 SECOND 8#usize k5 qv Q Zb (B0 + Bt) Bt
    Rinv ζ f rfl (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by omega)
    hqSel hQq hqv hQpos hQlt hRinv hzeta hZb hsq (by linarith) hBt0
    (hmono (B0 + Bt) (by linarith) (by linarith)).1
    (hmono (B0 + Bt) (by linarith) (by linarith)).2.1
    (hmono (B0 + Bt) (by linarith) (by linarith)).2.2 hd5 hs5)
  rintro ⟨b6, k6⟩ ⟨hs6, hd6, hk6⟩
  simp only at hs6 hd6 hk6
  -- level 6: 32 blocks of 8
  apply WP.spec_bind (ct_step (nb := 32) (lenv := 4) b6 SECOND 4#usize k6 qv Q Zb (B0 + 2 * Bt) Bt
    Rinv ζ f rfl (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by omega)
    hqSel hQq hqv hQpos hQlt hRinv hzeta hZb hsq (by linarith) hBt0
    (hmono (B0 + 2 * Bt) (by linarith) (by linarith)).1
    (hmono (B0 + 2 * Bt) (by linarith) (by linarith)).2.1
    (hmono (B0 + 2 * Bt) (by linarith) (by linarith)).2.2
    (by intro c hc; have := hd6 c hc; linarith) hs6)
  rintro ⟨b7, k7⟩ ⟨hs7, hd7, hk7⟩
  simp only at hs7 hd7 hk7
  apply WP.spec_bind (barrett_block_spec (q := q) SECOND b7 qv m Q M hqSel hmSel hQq hqv hm
    hQpos hQlt14 hQodd hMpos hMlt hD)
  rintro b8 ⟨hv8, hb8⟩
  have hs8 : State ζ 64 4 1 f (bR q b8) := State_congr (by norm_num) hv8 hs7
  -- level 7: 64 blocks of 4
  apply WP.spec_bind (ct_step (nb := 64) (lenv := 2) b8 SECOND 2#usize k7 qv Q Zb B0 Bt
    Rinv ζ f rfl (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by omega)
    hqSel hQq hqv hQpos hQlt hRinv hzeta hZb hsq hB00 hBt0
    (hmono B0 hB00 (by linarith)).1 (hmono B0 hB00 (by linarith)).2.1
    (hmono B0 hB00 (by linarith)).2.2 (hbar b8 hb8) hs8)
  rintro ⟨b9, k9⟩ ⟨hs9, hd9, hk9⟩
  simp only at hs9 hd9 hk9
  -- level 8: 128 blocks of 2
  apply WP.spec_bind (ct_step (nb := 128) (lenv := 1) b9 SECOND 1#usize k9 qv Q Zb (B0 + Bt) Bt
    Rinv ζ f rfl (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by omega)
    hqSel hQq hqv hQpos hQlt hRinv hzeta hZb hsq (by linarith) hBt0
    (hmono (B0 + Bt) (by linarith) (by linarith)).1
    (hmono (B0 + Bt) (by linarith) (by linarith)).2.1
    (hmono (B0 + Bt) (by linarith) (by linarith)).2.2 hd9 hs9)
  rintro ⟨b10, k10⟩ ⟨hs10, hd10, hk10⟩
  simp only at hs10 hd10 hk10
  apply WP.spec_mono (barrett_block_spec (q := q) SECOND b10 qv m Q M hqSel hmSel hQq hqv hm
    hQpos hQlt14 hQodd hMpos hMlt hD)
  rintro r ⟨hvr, hbr⟩
  exact ⟨hbr, State_congr (by norm_num) hvr hs10⟩

/-! ## The inverse transform of one block

Runs of two Gentleman-Sande levels, because the sum path doubles: from `q/2` a run reaches `2q`,
and a third level would not fit.  The eight levels are followed by the `256⁻¹·2³²` scaling, which
is one `mont_mul` per lane and is what cancels both the Montgomery radix and the factor of two
each layer contributed. -/

/-- The closing scale pass. -/
theorem invntt_scale_loop_spec {q : ℕ} (iter : core.ops.range.Range Usize)
    (b : Array I16 256#usize) (qv scale scale_q : I16) (Q Sb Bin : ℤ) (Rinv sc : ZMod q)
    (hQq : (q : ℤ) = Q) (hqv : qv.val = Q) (hQpos : 0 < Q) (hQlt : Q ≤ 2 ^ 15)
    (hRinv : (2 ^ 16 : ZMod q) * Rinv = 1)
    (hsc : ((scale.val : ℤ) : ZMod q) * Rinv = sc)
    (hscB : |scale.val| ≤ Sb) (hSb : 0 ≤ Sb)
    (hpair : (2 ^ 16 : ℤ) ∣ (scale_q.val * Q - scale.val))
    (hBin : 0 ≤ Bin) (hQBin : Q ≤ Bin) (hmont : Bin * Sb < 2 ^ 15 * Q)
    (hend : iter.«end».val = 256) (hstart : iter.start.val ≤ 256)
    (hB : ∀ c, c < 256 → |bZ b c| ≤ Bin) :
    arithmetic.ntt_crt.invntt_block_loop iter b qv scale scale_q
      ⦃ (r : Array I16 256#usize) =>
          (∀ c, c < iter.start.val → bZ r c = bZ b c) ∧
          (∀ c, iter.start.val ≤ c → c < 256 →
              bR q r c = sc * bR q b c ∧ -Q < bZ r c ∧ bZ r c < Q) ⦄ := by
  unfold arithmetic.ntt_crt.invntt_block_loop
  by_cases hlt : iter.start.val < iter.«end».val
  · let* ⟨ o, iter1, ho, hstart', hend' ⟩ ← core.iter.range.IteratorRange.next_Usize_some_spec
    rw [ho]; simp only
    have hib : iter.start.val < 256 := by omega
    let* ⟨ i1, hi1 ⟩ ← Array.index_usize_spec b iter.start (by simp; omega)
    have hi1v : (i1.val : ℤ) = bZ b iter.start.val := by
      rw [hi1, ← bZ_getElem b iter.start hib]
    have hprodb : |(i1.val : ℤ) * (scale.val : ℤ)| < 2 ^ 15 * Q := by
      calc |(i1.val : ℤ) * (scale.val : ℤ)| = |(i1.val : ℤ)| * |(scale.val : ℤ)| := abs_mul _ _
        _ ≤ Bin * Sb := mul_le_mul (by rw [hi1v]; exact hB _ hib) hscB (abs_nonneg _) hBin
        _ < 2 ^ 15 * Q := hmont
    apply WP.spec_bind (mont_mul_spec i1 scale scale_q qv Q hqv hQpos hQlt hpair hprodb)
    intro i2 hi2
    obtain ⟨h2mod, h2lo, h2hi, _⟩ := hi2
    let* ⟨ a, ha ⟩ ← Array.update_spec b iter.start i2 (by simp; omega)
    have hav : ∀ c, bZ a c = if c = iter.start.val then (i2.val : ℤ) else bZ b c := by
      intro c; rw [ha, bZ_set b iter.start i2 hib c]
    have haB : ∀ c, c < 256 → |bZ a c| ≤ Bin := by
      intro c hc
      rw [hav c]
      by_cases hce : c = iter.start.val
      · rw [if_pos hce, abs_le]; omega
      · rw [if_neg hce]; exact hB c hc
    apply WP.spec_mono (invntt_scale_loop_spec iter1 a qv scale scale_q Q Sb Bin Rinv sc hQq hqv
      hQpos hQlt hRinv hsc hscB hSb hpair hBin hQBin hmont (by rw [hend']; exact hend) (by omega) haB)
    rintro r ⟨hR1, hR2⟩
    have hunch : ∀ c, c < iter.start.val → bZ r c = bZ b c := by
      intro c hc
      rw [hR1 c (by omega), hav c, if_neg (by omega)]
    refine ⟨hunch, ?_⟩
    intro c hc1 hc2
    rcases eq_or_lt_of_le hc1 with hce | hcgt
    · subst hce
      have hthis : bZ r iter.start.val = (i2.val : ℤ) := by
        rw [hR1 iter.start.val (by omega), hav iter.start.val, if_pos rfl]
      refine ⟨?_, by rw [hthis]; omega, by rw [hthis]; omega⟩
      show ((bZ r iter.start.val : ℤ) : ZMod q) = sc * ((bZ b iter.start.val : ℤ) : ZMod q)
      rw [hthis, ← hi1v]
      exact mont_val_ZMod hQq hRinv hsc h2mod
    · have h := hR2 c (by omega) hc2
      rw [bR_congr (show bZ a c = bZ b c from by rw [hav c, if_neg (by omega)])] at h
      exact ⟨h.1, h.2⟩
  · let* ⟨ o, iter1, hnone, _ ⟩ ← core.iter.range.IteratorRange.next_Usize_none_spec
    rw [hnone]; simp only [WP.spec_ok]
    exact ⟨fun c _ => trivial, fun c hc1 hc2 => by omega⟩
termination_by 256 - iter.start.val
decreasing_by scalar_decr_tac

theorem invntt_block_spec {q : ℕ} (SECOND : Bool) (b : Array I16 256#usize)
    (qv m qiv scale : I16)
    (Q Zb M Sb Bin B0 Bt : ℤ) (Rinv sc : ZMod q) (ζ f : ℕ → ZMod q) (cs : ZMod q)
    (hqSel : backend.crt.q SECOND = ok qv) (hmSel : backend.crt.barrett_m SECOND = ok m)
    (hqiSel : backend.crt.qinv SECOND = ok qiv)
    (hscSel : backend.crt.invntt_scale SECOND = ok scale)
    (hQq : (q : ℤ) = Q) (hqv : qv.val = Q) (hm : m.val = M)
    (hQpos : 0 < Q) (hQlt14 : Q < 2 ^ 14) (hQodd : ¬ (2 ∣ Q))
    (hMpos : 0 < M) (hMlt : M < 2 ^ 15) (hD : |2 ^ 27 - Q * M| ≤ 2047)
    (hRinv : (2 ^ 16 : ZMod q) * Rinv = 1)
    (hqiv : (2 ^ 16 : ℤ) ∣ (qiv.val * Q - 1))
    (hzeta : ZetaVal SECOND Zb Rinv ζ) (hZb : 0 ≤ Zb) (hZb32 : Zb ≤ 32767)
    (hsq : ∀ k, 1 ≤ k → k < 256 → ζ k ^ 2 = cst ζ k)
    (hpairz : ∀ nb b : ℕ, (∃ j, j < 8 ∧ nb = 2 ^ j) → b < nb →
      ζ (nb + b) * ζ (2 * nb - 1 - b) = -1)
    (hsc : ((scale.val : ℤ) : ZMod q) * Rinv = sc)
    (hscB : |scale.val| ≤ Sb) (hSb : 0 ≤ Sb)
    (hBin0 : 0 ≤ Bin) (hB00 : 0 ≤ B0) (hB01 : 1 ≤ B0) (hBt0 : 0 ≤ Bt)
    (hB0Bin : B0 ≤ Bin)
    (hQB0 : Q ≤ 2 * B0 + 1) (_hQ4Bin : Q ≤ 4 * Bin)
    (hmontG : 2 * (2 * Bin) * Zb < 2 ^ 15 * Q)
    (hBtG : 2 * (2 * Bin) * Zb + 2 ^ 15 * Q ≤ 2 ^ 16 * Bt)
    (hBtle : Bt ≤ 2 * B0) (hfitG : 4 * Bin ≤ 32767)
    (hmontS : (4 * Bin) * Sb < 2 ^ 15 * Q)
    (hB : ∀ c, c < 256 → |bZ b c| ≤ Bin)
    (hst : State ζ 256 1 cs f (bR q b)) :
    arithmetic.ntt_crt.invntt_block SECOND b
      ⦃ (r : Array I16 256#usize) =>
          (∀ c, c < 256 → -Q < bZ r c ∧ bZ r c < Q)
          ∧ State ζ 1 256 (sc * ((256 : ZMod q) * cs)) f (bR q r) ⦄ := by
  have hQlt : Q ≤ 2 ^ 15 := by omega
  -- every level in the chain runs at a bound `B` with `B0 ≤ B ≤ 2·Bin`
  have hlvl : ∀ B : ℤ, 0 ≤ B → B0 ≤ B → B ≤ 2 * Bin →
      2 * B * Zb < 2 ^ 15 * Q ∧ 2 * B * Zb + 2 ^ 15 * Q ≤ 2 ^ 16 * Bt ∧
      2 * B ≤ 2 * B ∧ Bt ≤ 2 * B ∧ 2 * B ≤ 32767 := by
    intro B hBp hBlo hBhi
    have h1 : 2 * B * Zb ≤ 2 * (2 * Bin) * Zb := by nlinarith
    exact ⟨by linarith, by linarith, le_refl _, by linarith, by linarith⟩
  have hbar : ∀ (r : Array I16 256#usize), (∀ c, c < 256 → 2 * |bZ r c| < Q) →
      ∀ c, c < 256 → |bZ r c| ≤ B0 := by
    intro r h c hc; have := h c hc; omega
  unfold arithmetic.ntt_crt.invntt_block
  rw [hqSel, bind_tc_ok, hscSel, bind_tc_ok, hqiSel, bind_tc_ok]
  simp only [lift, bind_tc_ok]
  have hRDv : (consts.RING_DEG : Usize).val = 256 := by simp only [consts.RING_DEG]; rfl
  have hscqP : (2 ^ 16 : ℤ) ∣ ((core.num.I16.wrapping_mul scale qiv).val * Q - scale.val) := by
    refine mont_pair_of_qinv hqiv ?_
    rw [core.num.I16.wrapping_mul, IScalar.wrapping_mul_val_eq]
    exact bmod_sub_dvd _ _
  -- the eight Gentleman-Sande levels
  apply WP.spec_bind (gs_step (nb := 128) (lenv := 1) b SECOND 1#usize consts.RING_DEG qv qiv
    Q Zb Bin Bt (2 * Bin) Rinv ζ f cs rfl (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    ⟨7, by norm_num⟩ (by rw [hRDv]) hqSel hqiSel hQq hqv hQpos hQlt hRinv hqiv hzeta hZb hZb32
    hsq hpairz hBin0 hBt0 (hlvl Bin hBin0 hB0Bin (by linarith)).1
    (hlvl Bin hBin0 hB0Bin (by linarith)).2.1 (hlvl Bin hBin0 hB0Bin (by linarith)).2.2.1
    (hlvl Bin hBin0 hB0Bin (by linarith)).2.2.2.1
    (hlvl Bin hBin0 hB0Bin (by linarith)).2.2.2.2 hB hst)
  rintro ⟨b1, k1⟩ ⟨hs1, hd1, hk1⟩
  simp only at hs1 hd1 hk1
  apply WP.spec_bind (gs_step (nb := 64) (lenv := 2) b1 SECOND 2#usize k1 qv qiv
    Q Zb (2 * Bin) Bt (4 * Bin) Rinv ζ f (2 * cs) rfl (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) ⟨6, by norm_num⟩ (by omega) hqSel hqiSel hQq hqv hQpos hQlt hRinv hqiv hzeta
    hZb hZb32 hsq hpairz (by linarith) hBt0
    (hlvl (2 * Bin) (by linarith) (by linarith) (by linarith)).1
    (hlvl (2 * Bin) (by linarith) (by linarith) (by linarith)).2.1
    (by linarith) (by linarith [(hlvl (2 * Bin) (by linarith) (by linarith) (by linarith)).2.2.2.1])
    (by linarith) hd1 hs1)
  rintro ⟨b2, k2⟩ ⟨hs2, hd2, hk2⟩
  simp only at hs2 hd2 hk2
  apply WP.spec_bind (barrett_block_spec (q := q) SECOND b2 qv m Q M hqSel hmSel hQq hqv hm
    hQpos hQlt14 hQodd hMpos hMlt hD)
  rintro b3 ⟨hv3, hb3⟩
  have hs3 : State ζ 64 4 (2 * (2 * cs)) f (bR q b3) := State_congr (by norm_num) hv3 hs2
  apply WP.spec_bind (gs_step (nb := 32) (lenv := 4) b3 SECOND 4#usize k2 qv qiv
    Q Zb B0 Bt (2 * B0) Rinv ζ f (2 * (2 * cs)) rfl (by norm_num) (by norm_num) (by norm_num)
    (by norm_num) ⟨5, by norm_num⟩ (by omega) hqSel hqiSel hQq hqv hQpos hQlt hRinv hqiv hzeta
    hZb hZb32 hsq hpairz hB00 hBt0
    (hlvl B0 hB00 (le_refl _) (by linarith)).1 (hlvl B0 hB00 (le_refl _) (by linarith)).2.1
    (le_refl _) hBtle (by linarith) (hbar b3 hb3) hs3)
  rintro ⟨b4, k4⟩ ⟨hs4, hd4, hk4⟩
  simp only at hs4 hd4 hk4
  apply WP.spec_bind (gs_step (nb := 16) (lenv := 8) b4 SECOND 8#usize k4 qv qiv
    Q Zb (2 * B0) Bt (4 * B0) Rinv ζ f (2 * (2 * (2 * cs))) rfl (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) ⟨4, by norm_num⟩ (by omega) hqSel hqiSel hQq hqv hQpos hQlt hRinv
    hqiv hzeta hZb hZb32 hsq hpairz (by linarith) hBt0
    (hlvl (2 * B0) (by linarith) (by linarith) (by linarith)).1
    (hlvl (2 * B0) (by linarith) (by linarith) (by linarith)).2.1
    (by linarith) (by linarith) (by linarith) hd4 hs4)
  rintro ⟨b5, k5⟩ ⟨hs5, hd5, hk5⟩
  simp only at hs5 hd5 hk5
  apply WP.spec_bind (barrett_block_spec (q := q) SECOND b5 qv m Q M hqSel hmSel hQq hqv hm
    hQpos hQlt14 hQodd hMpos hMlt hD)
  rintro b6 ⟨hv6, hb6⟩
  have hs6 : State ζ 16 16 (2 * (2 * (2 * (2 * cs)))) f (bR q b6) :=
    State_congr (by norm_num) hv6 hs5
  apply WP.spec_bind (gs_step (nb := 8) (lenv := 16) b6 SECOND 16#usize k5 qv qiv
    Q Zb B0 Bt (2 * B0) Rinv ζ f (2 * (2 * (2 * (2 * cs)))) rfl (by norm_num) (by norm_num)
    (by norm_num) (by norm_num) ⟨3, by norm_num⟩ (by omega) hqSel hqiSel hQq hqv hQpos hQlt hRinv
    hqiv hzeta hZb hZb32 hsq hpairz hB00 hBt0
    (hlvl B0 hB00 (le_refl _) (by linarith)).1 (hlvl B0 hB00 (le_refl _) (by linarith)).2.1
    (le_refl _) hBtle (by linarith) (hbar b6 hb6) hs6)
  rintro ⟨b7, k7⟩ ⟨hs7, hd7, hk7⟩
  simp only at hs7 hd7 hk7
  apply WP.spec_bind (gs_step (nb := 4) (lenv := 32) b7 SECOND 32#usize k7 qv qiv
    Q Zb (2 * B0) Bt (4 * B0) Rinv ζ f (2 * (2 * (2 * (2 * (2 * cs))))) rfl (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ⟨2, by norm_num⟩ (by omega) hqSel hqiSel hQq hqv
    hQpos hQlt hRinv hqiv hzeta hZb hZb32 hsq hpairz (by linarith) hBt0
    (hlvl (2 * B0) (by linarith) (by linarith) (by linarith)).1
    (hlvl (2 * B0) (by linarith) (by linarith) (by linarith)).2.1
    (by linarith) (by linarith) (by linarith) hd7 hs7)
  rintro ⟨b8, k8⟩ ⟨hs8, hd8, hk8⟩
  simp only at hs8 hd8 hk8
  apply WP.spec_bind (barrett_block_spec (q := q) SECOND b8 qv m Q M hqSel hmSel hQq hqv hm
    hQpos hQlt14 hQodd hMpos hMlt hD)
  rintro b9 ⟨hv9, hb9⟩
  have hs9 : State ζ 4 64 (2 * (2 * (2 * (2 * (2 * (2 * cs)))))) f (bR q b9) :=
    State_congr (by norm_num) hv9 hs8
  apply WP.spec_bind (gs_step (nb := 2) (lenv := 64) b9 SECOND 64#usize k8 qv qiv
    Q Zb B0 Bt (2 * B0) Rinv ζ f (2 * (2 * (2 * (2 * (2 * (2 * cs)))))) rfl (by norm_num)
    (by norm_num) (by norm_num) (by norm_num) ⟨1, by norm_num⟩ (by omega) hqSel hqiSel hQq hqv
    hQpos hQlt hRinv hqiv hzeta hZb hZb32 hsq hpairz hB00 hBt0
    (hlvl B0 hB00 (le_refl _) (by linarith)).1 (hlvl B0 hB00 (le_refl _) (by linarith)).2.1
    (le_refl _) hBtle (by linarith) (hbar b9 hb9) hs9)
  rintro ⟨b10, k10⟩ ⟨hs10, hd10, hk10⟩
  simp only at hs10 hd10 hk10
  apply WP.spec_bind (gs_step (nb := 1) (lenv := 128) b10 SECOND 128#usize k10 qv qiv
    Q Zb (2 * B0) Bt (4 * B0) Rinv ζ f (2 * (2 * (2 * (2 * (2 * (2 * (2 * cs))))))) rfl
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) ⟨0, by norm_num⟩ (by omega) hqSel
    hqiSel hQq hqv hQpos hQlt hRinv hqiv hzeta hZb hZb32 hsq hpairz (by linarith) hBt0
    (hlvl (2 * B0) (by linarith) (by linarith) (by linarith)).1
    (hlvl (2 * B0) (by linarith) (by linarith) (by linarith)).2.1
    (by linarith) (by linarith) (by linarith) hd10 hs10)
  rintro ⟨b11, k11⟩ ⟨hs11, hd11, hk11⟩
  simp only at hs11 hd11 hk11
  -- the closing scale pass
  apply WP.spec_mono (invntt_scale_loop_spec { start := 0#usize, «end» := consts.RING_DEG } b11 qv
    scale (core.num.I16.wrapping_mul scale qiv) Q Sb (4 * B0) Rinv sc hQq hqv hQpos hQlt hRinv hsc
    hscB hSb hscqP (by linarith) (by linarith)
    (by nlinarith) (by rw [hRDv]) (by simp) hd11)
  rintro r ⟨_, hR2⟩
  have hR2' : ∀ c, c < 256 → bR q r c = sc * bR q b11 c ∧ -Q < bZ r c ∧ bZ r c < Q :=
    fun c hc => hR2 c (by simp) hc
  refine ⟨fun c hc => ⟨(hR2' c hc).2.1, (hR2' c hc).2.2⟩, ?_⟩
  refine State_root_intro (fun rr hrr => ?_)
  rw [(hR2' rr hrr).1, State_root hs11 rr hrr]
  ring

end Kopis.Neon.Properties
