-- AUTOGENERATED from Kopis/Properties/NttCrtElem.lean by `make generated`.  Do not edit.
-- See NEON_VERIFICATION_PLAN.md phase E: the serial proof, with the extracted
-- constants and this stack's namespace renamed, and nothing else changed.
/-
  # Kopis/Properties/NttCrtElem.lean — an `NttElem`, and what its 512 lanes mean.

  `from_ring_elem` splits a ring element into its two residue blocks, transforms each, and packs
  them into one `[i16; 512]`: the `q₁` residues at lanes `0 … 255`, the `q₂` residues at
  `256 … 511`.  `NttOK` below is what comes out, and it is the *whole* interface between this
  file and the multiplier — the two `State`s say each half is the leaf-level CRT transform of the
  same coefficient function, and the two magnitude bounds are what the pointwise product needs.

  The `REDUCE` const-generic is the one place the two constructors differ.  Uniform coefficients
  go up to `2¹³`, which exceeds `q₁`, so they get a Barrett pass first; CBD secrets satisfy
  `|·| ≤ μ/2 ≤ 5` and are already centred residues for both primes, so they do not.  That is why
  `from_secret` carries an input hypothesis and `from_uniform` does not.
-/
import Kopis.Neon.Reduce
import Kopis.Bits.Stream
import Kopis.Neon.Properties.NttCrtBlock
import Kopis.Neon.Properties.Ntt

open Aeneas Aeneas.Std Result
open RustKopisNeon

namespace Kopis.Neon.Properties

open Kopis.Properties (streamBit streamNat streamNat_zero streamNat_succ streamBit_le_one streamNat_lt streamNat_split lor_add_of_lt lor_mul_of_lt sum_testBit_eq_mod streamNat_byte streamByte streamByte_lt sum_base256 testBit_sum_bytes streamNat_of_byteWindow cbdX cbdX_le testBit_streamNat cbdX_eq_bitSum streamNat_mod streamNat_shiftRight cbdX_eq_bitSum_of_le cbdU16)

open Kopis.CrtArith Kopis.Avx2.NttAlg Kopis.CrtZeta

set_option maxHeartbeats 1000000

/-! ## The two primes, concretely -/

/-- `q₁ = 7681`. -/
theorem crt_q_false : backend.crt.q false = ok backend.crt.Q1 := by
  unfold backend.crt.q; simp

/-- `q₂ = 10753`. -/
theorem crt_q_true : backend.crt.q true = ok backend.crt.Q2 := by
  unfold backend.crt.q; simp

theorem crt_m_false : backend.crt.barrett_m false = ok backend.crt.Q1_BARRETT_M := by
  unfold backend.crt.barrett_m; simp

theorem crt_m_true : backend.crt.barrett_m true = ok backend.crt.Q2_BARRETT_M := by
  unfold backend.crt.barrett_m; simp

theorem crt_qinv_false : backend.crt.qinv false = ok backend.crt.Q1_INV := by
  unfold backend.crt.qinv; simp

theorem crt_qinv_true : backend.crt.qinv true = ok backend.crt.Q2_INV := by
  unfold backend.crt.qinv; simp

theorem crt_scale_false : backend.crt.invntt_scale false = ok backend.crt.INVNTT_SCALE_1 := by
  unfold backend.crt.invntt_scale; simp

theorem crt_scale_true : backend.crt.invntt_scale true = ok backend.crt.INVNTT_SCALE_2 := by
  unfold backend.crt.invntt_scale; simp

unseal backend.crt.Q1_BARRETT_M in
theorem m1_val : backend.crt.Q1_BARRETT_M.val = 17474 := by decide

unseal backend.crt.Q2_BARRETT_M in
theorem m2_val : backend.crt.Q2_BARRETT_M.val = 12482 := by decide

unseal backend.crt.INVNTT_SCALE_1 in
theorem scale1_val : backend.crt.INVNTT_SCALE_1.val = 1912 := by decide

unseal backend.crt.INVNTT_SCALE_2 in
theorem scale2_val : backend.crt.INVNTT_SCALE_2.val = 2536 := by decide

/-- `2¹⁶ · 900 ≡ 1 (mod q₁)`: the plain twiddle really is the stored entry over the radix. -/
theorem rinv1 : (2 ^ 16 : ZMod 7681) * (900 : ZMod 7681) = 1 := by decide

theorem rinv2 : (2 ^ 16 : ZMod 10753) * (1764 : ZMod 10753) = 1 := by decide

/-! ## The table hypotheses, discharged at both primes -/

theorem zetaOK_q1 : ZetaOK false 7681 3840 (900 : ZMod 7681) zeta1 := by
  intro kk hkk
  obtain ⟨zi, zqi, hzi, hzqi, hziB, hzqiP, hziv⟩ := zeta_table_ok_q1 kk hkk
  refine ⟨zi, zqi, hzi, hzqi, hziB, hzqiP, ?_⟩
  rw [zeta1, zetaQ, zint, ← hziv]

theorem zetaOK_q2 : ZetaOK true 10753 5376 (1764 : ZMod 10753) zeta2 := by
  intro kk hkk
  obtain ⟨zi, zqi, hzi, hzqi, hziB, hzqiP, hziv⟩ := zeta_table_ok_q2 kk hkk
  refine ⟨zi, zqi, hzi, hzqi, hziB, hzqiP, ?_⟩
  rw [zeta2, zetaQ, zint, ← hziv]

theorem zetaVal_q1 : ZetaVal false 3840 (900 : ZMod 7681) zeta1 := by
  intro kk hkk
  obtain ⟨zi, _, hzi, _, hziB, _, hziv⟩ := zeta_table_ok_q1 kk hkk
  exact ⟨zi, hzi, hziB, by rw [zeta1, zetaQ, zint, ← hziv]⟩

theorem zetaVal_q2 : ZetaVal true 5376 (1764 : ZMod 10753) zeta2 := by
  intro kk hkk
  obtain ⟨zi, _, hzi, _, hziB, _, hziv⟩ := zeta_table_ok_q2 kk hkk
  exact ⟨zi, hzi, hziB, by rw [zeta2, zetaQ, zint, ← hziv]⟩

/-! ## `split_and_transform`

The widening loop, then the forward transform of the block it built. -/

/-- A stored `u16` read as an `i16` is `Int.bmod`, which is `signedOfU16`. -/
theorem hcast_i16_signed (v : U16) : (UScalar.hcast IScalarTy.I16 v).val = signedOfU16 v := by
  rw [UScalar.hcast_val_eq, show (2 : ℕ) ^ IScalarTy.I16.numBits = 2 ^ 16 from rfl]
  have h0 : (0 : ℤ) ≤ v.val := Int.natCast_nonneg _
  have h1 : (v.val : ℤ) < 65536 := by scalar_tac
  unfold Int.bmod signedOfU16
  norm_num
  rw [Int.emod_eq_of_lt h0 (by norm_num; omega)]
  split <;> split <;> omega

theorem split_loop_spec {q : ℕ} (REDUCE : Bool) (iter : core.ops.range.Range Usize)
    (elem : Array U16 256#usize) (b : Array I16 256#usize) (qv m : I16) (Q M B0 : ℤ)
    (hQq : (q : ℤ) = Q) (hqv : qv.val = Q) (hm : m.val = M)
    (hQpos : 0 < Q) (hQlt : Q < 2 ^ 14) (hQodd : ¬ (2 ∣ Q))
    (hMpos : 0 < M) (hMlt : M < 2 ^ 15) (hD : |2 ^ 27 - Q * M| ≤ 2047)
    (hQB0 : Q ≤ 2 * B0 + 1)
    (hsmall : REDUCE = false → ∀ c, c < 256 → |signedOfU16 (elem.val[c]!)| ≤ B0)
    (hend : iter.«end».val = 256) (hstart : iter.start.val ≤ 256)
    (hpre : ∀ c, c < iter.start.val →
      |bZ b c| ≤ B0 ∧ ((bZ b c : ℤ) : ZMod q) = ((signedOfU16 (elem.val[c]!) : ℤ) : ZMod q)) :
    arithmetic.ntt_crt.split_and_transform_loop REDUCE iter elem b qv m
      ⦃ (r : Array I16 256#usize) => ∀ c, c < 256 →
          |bZ r c| ≤ B0 ∧
          ((bZ r c : ℤ) : ZMod q) = ((signedOfU16 (elem.val[c]!) : ℤ) : ZMod q) ⦄ := by
  unfold arithmetic.ntt_crt.split_and_transform_loop
  by_cases hlt : iter.start.val < iter.«end».val
  · let* ⟨ o, iter1, ho, hstart', hend' ⟩ ← core.iter.range.IteratorRange.next_Usize_some_spec
    rw [ho]; simp only
    have hib : iter.start.val < 256 := by omega
    let* ⟨ i1, hi1 ⟩ ← Array.index_usize_spec elem iter.start (by simp; omega)
    have hi1e : i1 = elem.val[iter.start.val]! := by
      rw [hi1, getElem!_pos elem.val iter.start.val (by simp; omega)]
    subst hi1e
    simp only [lift, bind_tc_ok]
    -- the widened coefficient, and the optional Barrett pass
    have hstep : ∀ (P : I16 → Prop),
        (∀ x1 : I16, |(x1.val : ℤ)| ≤ B0 →
          ((x1.val : ℤ) : ZMod q) = ((signedOfU16 (elem.val[iter.start.val]!) : ℤ) : ZMod q) →
          P x1) →
        (if REDUCE then
            arithmetic.ntt_crt.barrett (UScalar.hcast IScalarTy.I16 elem.val[iter.start.val]!) m qv
          else ok (UScalar.hcast IScalarTy.I16 elem.val[iter.start.val]!)) ⦃ P ⦄ := by
      intro P hP
      cases hR : REDUCE
      · simp only [Bool.false_eq_true, if_false, WP.spec_ok]
        refine hP _ ?_ ?_
        · rw [hcast_i16_signed]
          exact hsmall hR iter.start.val hib
        · rw [hcast_i16_signed]
      · simp only [if_true]
        apply WP.spec_mono (barrett_spec (UScalar.hcast IScalarTy.I16 elem.val[iter.start.val]!)
          m qv Q M hqv hm hQpos hQlt hQodd hMpos hMlt hD)
        rintro x1 ⟨hmod, hbnd⟩
        refine hP x1 (by omega) ?_
        have hd : ((q : ℤ)) ∣
            ((x1.val : ℤ) - (signedOfU16 (elem.val[iter.start.val]!) : ℤ)) := by
          rw [hQq, ← hcast_i16_signed]; exact hmod
        have h0 : ((((x1.val : ℤ)
            - (signedOfU16 (elem.val[iter.start.val]!) : ℤ)) : ℤ) : ZMod q) = 0 :=
          (ZMod.intCast_zmod_eq_zero_iff_dvd _ q).mpr (by exact_mod_cast hd)
        push_cast at h0
        linear_combination h0
    apply WP.spec_bind (hstep _ (fun x1 h1 h2 => And.intro h1 h2))
    rintro x1 ⟨hx1B, hx1v⟩
    let* ⟨ a, ha ⟩ ← Array.update_spec b iter.start x1 (by simp; omega)
    have hav : ∀ c, bZ a c = if c = iter.start.val then (x1.val : ℤ) else bZ b c := by
      intro c; rw [ha, bZ_set b iter.start x1 hib c]
    apply WP.spec_mono (split_loop_spec REDUCE iter1 elem a qv m Q M B0 hQq hqv hm hQpos hQlt
      hQodd hMpos hMlt hD hQB0 hsmall (by rw [hend']; exact hend) (by omega)
      (by
        intro c hc
        rw [hav c]
        by_cases hce : c = iter.start.val
        · rw [if_pos hce, hce]; exact ⟨hx1B, hx1v⟩
        · rw [if_neg hce]; exact hpre c (by omega)))
    exact fun r h => h
  · let* ⟨ o, iter1, hnone, _ ⟩ ← core.iter.range.IteratorRange.next_Usize_none_spec
    rw [hnone]; simp only [WP.spec_ok]
    exact fun c hc => hpre c (by omega)

/-- **`split_and_transform`.**  The widening loop builds a block congruent to the coefficients,
and `ntt_block` transforms it; the output is centred, which is what the pointwise product's
magnitude bound assumes. -/
theorem split_and_transform_spec {q : ℕ} (SECOND REDUCE : Bool)
    (elem : Array U16 256#usize) (b : Array I16 256#usize) (qv m : I16)
    (Q Zb M B0 Bt : ℤ) (Rinv : ZMod q) (ζ : ℕ → ZMod q)
    (hqSel : backend.crt.q SECOND = ok qv) (hmSel : backend.crt.barrett_m SECOND = ok m)
    (hQq : (q : ℤ) = Q) (hqv : qv.val = Q) (hm : m.val = M)
    (hQpos : 0 < Q) (hQlt14 : Q < 2 ^ 14) (hQodd : ¬ (2 ∣ Q))
    (hMpos : 0 < M) (hMlt : M < 2 ^ 15) (hD : |2 ^ 27 - Q * M| ≤ 2047)
    (hRinv : (2 ^ 16 : ZMod q) * Rinv = 1)
    (hzeta : ZetaOK SECOND Q Zb Rinv ζ) (hZb : 0 ≤ Zb)
    (hsq : ∀ k, 1 ≤ k → k < 256 → ζ k ^ 2 = cst ζ k)
    (hB00 : 0 ≤ B0) (hBt0 : 0 ≤ Bt) (hQB0 : Q ≤ 2 * B0 + 1)
    (hmont3 : (B0 + 2 * Bt) * Zb < 2 ^ 15 * Q)
    (hBt3 : (B0 + 2 * Bt) * Zb + 2 ^ 15 * Q ≤ 2 ^ 16 * Bt)
    (hfit3 : B0 + 3 * Bt ≤ 32767)
    (hsmall : REDUCE = false → ∀ c, c < 256 → |signedOfU16 (elem.val[c]!)| ≤ B0) :
    arithmetic.ntt_crt.split_and_transform SECOND REDUCE elem b
      ⦃ (r : Array I16 256#usize) =>
          (∀ c, c < 256 → 2 * |bZ r c| < Q) ∧
          State ζ 256 1 1 (fun c => ((signedOfU16 (elem.val[c]!) : ℤ) : ZMod q)) (bR q r) ⦄ := by
  unfold arithmetic.ntt_crt.split_and_transform
  rw [hqSel, bind_tc_ok, hmSel, bind_tc_ok]
  apply WP.spec_bind (split_loop_spec (q := q) REDUCE
    { start := 0#usize, «end» := consts.RING_DEG } elem b qv m Q M B0 hQq hqv hm hQpos hQlt14
    hQodd hMpos hMlt hD hQB0 hsmall (by simp only [consts.RING_DEG]; rfl) (by simp)
    (by intro c hc; simp at hc))
  intro b1 hb1
  exact ntt_block_spec SECOND b1 qv m Q Zb M B0 Bt Rinv ζ
    (fun c => ((signedOfU16 (elem.val[c]!) : ℤ) : ZMod q))
    hqSel hmSel hQq hqv hm hQpos hQlt14 hQodd hMpos hMlt hD hRinv hzeta hZb hsq hB00 hBt0 hQB0
    hmont3 hBt3 hfit3 (fun c hc => (hb1 c hc).1)
    (State_root_intro (fun r hr => by
      have := (hb1 r hr).2
      simpa [bR] using this))

/-! ## `from_ring_elem`, and what an `NttElem` means -/

/-- The integer value of lane `i` of an `NttElem`. -/
def eZ (ne : Array I16 512#usize) (i : ℕ) : ℤ := ((ne.val[i]!).val : ℤ)

/-- **What an `NttElem` holds.**  Lanes `0 … 255` are the `q₁` residues of the leaf-level
transform of `g`, lanes `256 … 511` the `q₂` ones, and both are centred — which is exactly the
input `pointwise_mul_acc`'s product bound assumes. -/
def NttOK (g : ℕ → ℤ) (ne : Array I16 512#usize) : Prop :=
  (∀ c, c < 256 → |eZ ne c| ≤ 3840) ∧
  (∀ c, c < 256 → |eZ ne (256 + c)| ≤ 5376) ∧
  State zeta1 256 1 1 (fun c => ((g c : ℤ) : ZMod 7681))
    (fun c => ((eZ ne c : ℤ) : ZMod 7681)) ∧
  State zeta2 256 1 1 (fun c => ((g c : ℤ) : ZMod 10753))
    (fun c => ((eZ ne (256 + c) : ℤ) : ZMod 10753))

theorem from_ring_elem_spec (REDUCE : Bool) (elem : Array U16 256#usize)
    (hsmall : REDUCE = false → ∀ c, c < 256 → |signedOfU16 (elem.val[c]!)| ≤ 3840) :
    arithmetic.ntt_crt.from_ring_elem REDUCE elem
      ⦃ (r : Array I16 512#usize) =>
          NttOK (fun c => signedOfU16 (elem.val[c]!)) r ⦄ := by
  have hRD : (consts.RING_DEG : Usize) = 256#usize := by simp only [consts.RING_DEG]
  unfold arithmetic.ntt_crt.from_ring_elem
  -- the `q₁` block
  apply WP.spec_bind (split_and_transform_spec (q := 7681) false REDUCE elem _
    backend.crt.Q1 backend.crt.Q1_BARRETT_M 7681 3840 17474 3840 4650 (900 : ZMod 7681) zeta1
    crt_q_false crt_m_false (by norm_num) q1_val m1_val (by norm_num) (by norm_num) (by decide)
    (by norm_num) (by norm_num) (by norm_num) rinv1 zetaOK_q1 (by norm_num) zeta1_sq
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (fun h => hsmall h))
  intro b1 hb1
  obtain ⟨hb1B, hb1S⟩ := hb1
  step*
  -- the `q₂` block, written over the scratch buffer the first one used
  apply WP.spec_bind (split_and_transform_spec (q := 10753) true REDUCE elem b1
    backend.crt.Q2 backend.crt.Q2_BARRETT_M 10753 5376 12482 5376 7000 (1764 : ZMod 10753) zeta2
    crt_q_true crt_m_true (by norm_num) q2_val m2_val (by norm_num) (by norm_num) (by decide)
    (by norm_num) (by norm_num) (by norm_num) rinv2 zetaOK_q2 (by norm_num) zeta2_sq
    (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (fun h c hc => le_trans (hsmall h c hc) (by norm_num)))
  intro b2 hb2
  obtain ⟨hb2B, hb2S⟩ := hb2
  step*
  -- the two halves, as they land in the packed buffer
  have hb1len : b1.val.length = 256 := b1.property
  have hb2len : b2.val.length = 256 := b2.property
  have hzlen : (Array.repeat 512#usize (0#i16)).val.length = 512 := by
    have := (Array.repeat 512#usize (0#i16)).property; scalar_tac
  have hmid : ((Array.repeat 512#usize (0#i16)).val.setSlice! 0 b1.val).length = 512 := by
    rw [List.length_setSlice!, hzlen]
  have hRDv : (consts.RING_DEG : Usize).val = 256 := by simp only [consts.RING_DEG]; rfl
  have hval : (index_mut_back1 s5).val
      = ((Array.repeat 512#usize (0#i16)).val.setSlice! 0 b1.val).setSlice! 256 b2.val := by
    rw [s3_post3 s5, s5_post, s4_post, s_post3 s2, s2_post, s1_post, hRDv, Array.val_to_slice,
      Array.val_to_slice]
  have hlow : ∀ c, c < 256 → eZ (index_mut_back1 s5) c = bZ b1 c := by
    intro c hc
    unfold eZ bZ
    rw [hval, List.getElem!_setSlice!_prefix _ _ _ _ (by omega),
      List.getElem!_setSlice!_middle _ _ _ _
        ⟨by omega, by rw [hb1len]; omega, by rw [hzlen]; omega⟩, Nat.sub_zero]
  have hhigh : ∀ c, c < 256 → eZ (index_mut_back1 s5) (256 + c) = bZ b2 c := by
    intro c hc
    unfold eZ bZ
    rw [hval, List.getElem!_setSlice!_middle _ _ _ _
      ⟨by omega, by rw [hb2len]; omega, by rw [hmid]; omega⟩,
      show 256 + c - 256 = c from by omega]
  refine ⟨fun c hc => ?_, fun c hc => ?_, ?_, ?_⟩
  · rw [hlow c hc]; have := hb1B c hc; omega
  · rw [hhigh c hc]; have := hb2B c hc; omega
  · exact State_congr (by norm_num) (fun c hc => by rw [hlow c hc]; rfl) hb1S
  · exact State_congr (by norm_num) (fun c hc => by rw [hhigh c hc]; rfl) hb2S

/-! ## The two `NttElem` constructors

NEON only: both are dispatch points.  `available_ok` says the probe returns; whichever way it
goes, the postcondition is the same one — which is the whole benefit of the two backends now
agreeing on the representation. -/

/-- A stored `u16` read as an `i16` is exactly its `BitVec` signed reading, which is the form the
NEON lemmas use. -/
theorem signedOfU16_toInt (v : U16) : (v.bv).toInt = signedOfU16 v := by
  have hn : v.bv.toNat = v.val := rfl
  have hlt : v.val < 65536 := by have := v.hBounds; scalar_tac
  simp only [BitVec.toInt, signedOfU16, hn]
  norm_num
  split <;> split <;> omega

/-- The NEON stack's `NttOK` and this one are the same predicate, spelled through `i16View`
rather than `eZ`.  Both read element `t` of the same `[i16; 512]`. -/
theorem nttOK_of_avx {g : ℕ → ℤ} {ne : Array I16 512#usize} (h : Kopis.Neon.NttOK g ne) :
    NttOK g ne := h

/-- `NttOK` reads its coefficient function only below 256. -/
theorem NttOK_congr {g g' : ℕ → ℤ} {ne : Array I16 512#usize}
    (h : ∀ c, c < 256 → g c = g' c) (hok : NttOK g ne) : NttOK g' ne := by
  obtain ⟨h1, h2, h3, h4⟩ := hok
  refine ⟨h1, h2, ?_, ?_⟩
  · intro n hn r' hr'
    rw [h3 n hn r' hr']
    exact congrArg _ (Finset.sum_congr rfl fun i hi => by
      show ((g (i * 1 + r') : ℤ) : ZMod 7681) * _ = _
      rw [h (i * 1 + r') (by have := Finset.mem_range.mp hi; omega)])
  · intro n hn r' hr'
    rw [h4 n hn r' hr']
    exact congrArg _ (Finset.sum_congr rfl fun i hi => by
      show ((g (i * 1 + r') : ℤ) : ZMod 10753) * _ = _
      rw [h (i * 1 + r') (by have := Finset.mem_range.mp hi; omega)])

/-- `from_uniform`, with no condition on the input: the coefficient function it transforms is the
*signed* reading of the stored `u16`s. -/
theorem from_uniform_NttOK_signed (elem : arithmetic.ring_arith.RingElem) :
    arithmetic.ntt.NttElem.from_uniform elem
      ⦃ (r : Array I16 512#usize) =>
          NttOK (fun c => signedOfU16 (elem.val[c]!)) r ⦄ := by
  obtain ⟨b, hb⟩ : ∃ b, backend.neon.cpu.available = ok b := ⟨true, rfl⟩
  cases b
  · unfold arithmetic.ntt.NttElem.from_uniform
    rw [hb, bind_tc_ok]
    simp only [Bool.false_eq_true, if_false]
    apply WP.spec_bind (show arithmetic.ntt_crt.from_uniform elem
        ⦃ (r : Array I16 512#usize) =>
            NttOK (fun c => signedOfU16 (elem.val[c]!)) r ⦄ from by
      unfold arithmetic.ntt_crt.from_uniform
      exact from_ring_elem_spec true elem (by simp))
    intro r hr
    simp only [WP.spec_ok]
    exact hr
  · refine WP.spec_mono (Kopis.Neon.elem_from_uniform_NttOK elem
      (fun c => signedOfU16 (elem.val[c]!)) (fun c _ => signedOfU16_toInt _)) ?_
    exact fun r hr => nttOK_of_avx hr

/-- A `u16` below `2¹⁵` reads the same signed or unsigned. -/
theorem signedOfU16_of_small {v : U16} (h : (v.val : ℤ) < 32768) :
    signedOfU16 v = (v.val : ℤ) := by
  unfold signedOfU16; rw [if_pos h]

theorem from_secret_NttOK (elem : arithmetic.ring_arith.RingElem)
    (hs : ∀ c, c < 256 → |signedOfU16 (elem.val[c]!)| ≤ 3840) :
    arithmetic.ntt.NttElem.from_secret elem
      ⦃ (r : Array I16 512#usize) =>
          NttOK (fun c => signedOfU16 (elem.val[c]!)) r ⦄ := by
  obtain ⟨b, hb⟩ : ∃ b, backend.neon.cpu.available = ok b := ⟨true, rfl⟩
  cases b
  · unfold arithmetic.ntt.NttElem.from_secret
    rw [hb, bind_tc_ok]
    simp only [Bool.false_eq_true, if_false]
    apply WP.spec_bind (show arithmetic.ntt_crt.from_secret elem
        ⦃ (r : Array I16 512#usize) =>
            NttOK (fun c => signedOfU16 (elem.val[c]!)) r ⦄ from by
      unfold arithmetic.ntt_crt.from_secret
      exact from_ring_elem_spec false elem (fun _ => hs))
    intro r hr
    simp only [WP.spec_ok]
    exact hr
  · refine WP.spec_mono (Kopis.Neon.elem_from_secret_NttOK elem
      (fun c => signedOfU16 (elem.val[c]!)) (fun c _ => signedOfU16_toInt _)
      (fun c hc => by have := hs c hc; omega) (fun c hc => by have := hs c hc; omega)) ?_
    exact fun r hr => nttOK_of_avx hr

end Kopis.Neon.Properties
