-- AUTOGENERATED from Kopis/Properties/RingArith.lean by `make generated`.  Do not edit.
-- See NEON_VERIFICATION_PLAN.md phase E: the serial proof, with the extracted
-- constants and this stack's namespace renamed, and nothing else changed.
/-
  # Kopis/Properties/RingArith.lean — Correspondence proofs for ring-element arithmetic.

  Bridges the Aeneas-extracted Rust ring element (`RingElem = [u16; 256]`,
  `ExtractedRustNeon`) to the audited spec ring element
  (`Spec.Kopis.Polynomial (2^16)`, `Spec/Kopis/Spec.lean`).

  ## Abstraction relation

  The Rust `RingElem` stores 256 coefficients as `u16`, and `RingElem::sub`
  subtracts them with `u16::wrapping_sub`, i.e. arithmetic modulo `2^16`.  The spec
  `Spec.Kopis.Polynomial.sub` is generic in the coefficient modulus `m` and
  uses `ZMod m` subtraction, so the faithful correspondence is at `m = 2^16`:
  `toRingElem` maps each stored `u16` to its class in `ZMod (2^16)`.

  (Kopis' *logical* moduli are `2^13`/`2^10`/`2^1`; those are recovered from the
  physical `2^16` representative by `Spec.Kopis.Polynomial.coerce`, which is a
  ring hom and hence commutes with `sub`.  Proving the correspondence at the
  physical `2^16` is therefore the strongest statement about what the code
  computes.)

  ## What is here

  `RingElem::sub`, the two shifts, and `wrapping_add_to_all` — the `RingElem` operations
  the Rust still has — plus the spec-side closed form of the negacyclic product
  (`convCoeff` / `mul_get`), which `NttBridge` and the `CoerceBridge`s consume.

  `RingElem::add` and `RingElem::mul` are *not* here: the `Add`/`Mul` impls on `&RingElem`
  were deleted from the Rust along with the old schoolbook/Karatsuba multiplier, and ring
  products now go through the NTT.  `NttBridge.lean` proves that path
  (`ntt_mul_spec` / `ntt_mul_transpose_spec`).
-/
import Kopis.Bits.Stream
import ExtractedRustNeon
import Spec.Kopis.Spec

open Aeneas Aeneas.Std Result
open RustKopisNeon

namespace Kopis.Neon.Properties

open Kopis.Properties (streamBit streamNat streamNat_zero streamNat_succ streamBit_le_one streamNat_lt streamNat_split lor_add_of_lt lor_mul_of_lt sum_testBit_eq_mod streamNat_byte streamByte streamByte_lt sum_base256 testBit_sum_bytes streamNat_of_byteWindow cbdX cbdX_le testBit_streamNat cbdX_eq_bitSum streamNat_mod streamNat_shiftRight cbdX_eq_bitSum_of_le cbdU16)

/-- The Rust ring element: 256 `u16` coefficients. -/
abbrev RingElem := arithmetic.plain_arith.RingElem

/-- Abstraction relation: interpret the stored `u16` coefficients as an element
of the spec ring `Spec.Kopis.Polynomial (2^16) = Vector (ZMod (2^16)) 256`,
coefficient `i` being that of `Xⁱ`. -/
def toRingElem (a : RingElem) : Spec.Kopis.Polynomial (2 ^ 16) :=
  Vector.ofFn fun (i : Fin 256) =>
    ((a.val[i.val]'(by have := a.property; grind)).val : ZMod (2 ^ 16))

/-- `Vector.ofFn` computes to `f` at every index (helper mirroring the MLKEM
proofs). -/
private theorem Vector_get_ofFn_aux {n : Nat} {α : Type*} (f : Fin n → α) (i : Fin n) :
    (Vector.ofFn f).get i = f i := by
  obtain ⟨i, hi⟩ := i
  show (Vector.ofFn f)[i] = _
  rw [Vector.getElem_ofFn]

set_option maxHeartbeats 1000000

/-- Casting a `u16` wrapping sum into `ZMod (2^16)` is the `ZMod` sum of the
casts (the wrap `% 2^16` is absorbed by the quotient). -/
private theorem wrapping_add_toZMod (x y : U16) :
    (((core.num.U16.wrapping_add x y).val : ℕ) : ZMod (2 ^ 16))
      = (x.val : ZMod (2 ^ 16)) + (y.val : ZMod (2 ^ 16)) := by
  have hsize : UScalar.size .U16 = 2 ^ 16 := by rw [UScalar.size_def]; rfl
  rw [core.num.U16.wrapping_add_val_eq, hsize, ZMod.natCast_mod, Nat.cast_add]

/-- Casting a `u16` wrapping difference into `ZMod (2^16)` is the `ZMod` difference. -/
private theorem wrapping_sub_toZMod (x y : U16) :
    (((core.num.U16.wrapping_sub x y).val : ℕ) : ZMod (2 ^ 16))
      = (x.val : ZMod (2 ^ 16)) - (y.val : ZMod (2 ^ 16)) := by
  have hsize : UScalar.size .U16 = 2 ^ 16 := by rw [UScalar.size_def]; rfl
  have hy : y.val ≤ 2 ^ 16 := by have := U16.lt_succ_max y; omega
  rw [core.num.U16.wrapping_sub_val_eq, hsize, ZMod.natCast_mod, Nat.cast_add, Nat.cast_sub hy]
  rw [ZMod.natCast_self]
  ring

/-! ## `IterMut` step specs (generic; replicated from the MLKEM proofs, which live
in a different library — these depend only on Aeneas' `core.slice.iter`). -/

@[step]
theorem iter_mut_spec {T : Type} (s : Slice T) :
  core.slice.Slice.iter_mut s ⦃ p =>
    p.1.slice = s ∧ p.1.i = 0 ∧ ∀ it', p.2 it' = it'.slice ⦄ := by
  simp [core.slice.Slice.iter_mut]

@[step]
theorem iter_mut_next_spec {T : Type}
  (it : core.slice.iter.IterMut T)
  (h : it.i < it.slice.len) :
  core.slice.iter.IteratorIterMut.next it
  ⦃ p =>
    let (o, it', back) := p
    o = some (it.slice[it.i]) ∧
    it'.slice = it.slice ∧
    it'.i = it.i + 1 ∧
    (∀ it'', back it'' none = it'') ∧
    (∀ it'' x, back it'' (some x) = { it'' with slice := it''.slice.setAtNat it.i x })
  ⦄ := by
  simp only [core.slice.iter.IteratorIterMut.next, h, ↓reduceDIte]
  simp

@[step]
theorem iter_mut_next_spec_none {T : Type}
  (it : core.slice.iter.IterMut T)
  (h : it.i ≥ it.slice.len) :
  core.slice.iter.IteratorIterMut.next it
  ⦃ p =>
    let (o, it', back) := p
    o = none ∧ it' = it ∧ ∀ it'' ox, back it'' ox = it''
  ⦄ := by
  simp only [core.slice.iter.IteratorIterMut.next]
  split
  · agrind
  · simp

/-! ## `RingElem::sub` (`src/arithmetic/plain_arith.rs`) -/

/-- **Loop spec** for the `sub` loop (mirrors `add_loop_spec`). -/
theorem sub_loop_spec
    (iter : core.ops.range.Range Usize)
    (self other ret : RingElem)
    (h_start : iter.start.val ≤ 256) (h_end : iter.«end».val = 256) :
    SharedARingElem.Insts.CoreOpsArithSubSharedARingElemRingElem.sub_loop
        iter self other ret
      ⦃ (r : RingElem) =>
          toRingElem r = Vector.ofFn fun (j : Fin 256) =>
            if j.val < iter.start.val then (toRingElem ret).get j
            else (toRingElem self).get j - (toRingElem other).get j ⦄ := by
  unfold SharedARingElem.Insts.CoreOpsArithSubSharedARingElemRingElem.sub_loop
  by_cases hlt : iter.start.val < iter.«end».val
  · let* ⟨ o, iter1, ho, hstart', hend' ⟩ ← core.iter.range.IteratorRange.next_Usize_some_spec
    rw [ho]
    simp only
    have hi_lt : iter.start.val < 256 := by scalar_tac
    let* ⟨ i1, hi1 ⟩ ← Array.index_usize_spec
    let* ⟨ i2, hi2 ⟩ ← Array.index_usize_spec
    simp only [lift]
    let* ⟨ a, ha_eq ⟩ ← Array.update_spec
    have h_start_new : iter1.start.val ≤ 256 := by rw [hstart']; scalar_tac
    have h_end_new : iter1.«end».val = 256 := by rw [hend']; exact h_end
    apply WP.spec_mono
      (sub_loop_spec iter1 self other a h_start_new h_end_new)
    rintro r h_eq_r
    rw [h_eq_r]
    apply Vector.ext
    intro j hj
    rw [Vector.getElem_ofFn, Vector.getElem_ofFn]
    show (if ↑(⟨j, hj⟩ : Fin 256) < iter1.start.val then _ else _) = _
    rw [hstart']
    by_cases hj_lt_new : j < iter.start.val + 1
    · rw [if_pos hj_lt_new]
      by_cases hj_eq : j = iter.start.val
      · subst hj_eq
        rw [if_neg (Nat.lt_irrefl _)]
        unfold toRingElem
        simp only [Vector_get_ofFn_aux]
        rw [ha_eq]
        simp only [Array.set_val_eq]
        rw [List.getElem_set_self]
        rw [hi1, hi2]
        exact wrapping_sub_toZMod _ _
      · have hj_lt : j < iter.start.val := by scalar_tac
        rw [if_pos hj_lt]
        unfold toRingElem
        simp only [Vector_get_ofFn_aux]
        rw [ha_eq]
        simp only [Array.set_val_eq]
        rw [List.getElem_set_ne (Ne.symm hj_eq)]
    · push Not at hj_lt_new
      rw [if_neg (by scalar_tac : ¬ j < iter.start.val + 1)]
      rw [if_neg (by scalar_tac : ¬ j < iter.start.val)]
  · have h_start_eq : iter.start.val = 256 := by scalar_tac
    let* ⟨ o, iter1, hnone, _ ⟩ ← core.iter.range.IteratorRange.next_Usize_none_spec
    rw [hnone]
    simp only [WP.spec_ok]
    rw [h_start_eq]
    conv_rhs =>
      rw [show (fun (j : Fin 256) =>
              if j.val < 256 then Vector.get (toRingElem ret) j
              else Vector.get (toRingElem self) j - Vector.get (toRingElem other) j) =
            (fun (j : Fin 256) => (toRingElem ret)[j.val]) from
          funext (fun j => if_pos j.isLt)]
    exact Vector.ofFn_getElem.symm
termination_by iter.«end».val - iter.start.val
decreasing_by scalar_decr_tac

/-- **Wrapper spec** for `RingElem::sub` — matches `Spec.Kopis.Polynomial.sub`. -/
theorem sub_spec (self other : RingElem) :
    SharedARingElem.Insts.CoreOpsArithSubSharedARingElemRingElem.sub self other
      ⦃ (r : RingElem) =>
          toRingElem r = Spec.Kopis.Polynomial.sub (toRingElem self) (toRingElem other) ⦄ := by
  unfold SharedARingElem.Insts.CoreOpsArithSubSharedARingElemRingElem.sub
  have h_end : (consts.RING_DEG).val = 256 := by simp [consts.RING_DEG]
  rw [show (arithmetic.plain_arith.RingElem.Insts.CoreDefaultDefault.default : Result RingElem)
        = ok (Array.repeat 256#usize 0#u16) from rfl]
  simp only [bind_tc_ok]
  apply WP.spec_mono
    (sub_loop_spec { start := 0#usize, «end» := consts.RING_DEG } self other
      (Array.repeat 256#usize 0#u16) (by scalar_tac) h_end)
  rintro r h_eq_r
  rw [h_eq_r]
  apply Vector.ext
  intro j hj
  rw [Vector.getElem_ofFn]
  show (if (⟨j, hj⟩ : Fin 256).val < (0#usize).val then _ else _) = _
  rw [if_neg (by simp)]
  unfold Spec.Kopis.Polynomial.sub
  rw [Vector.getElem_zipWith]
  rfl

/-! ## The negacyclic product on the spec side

  `RingElem::add` and `RingElem::mul` are gone from the Rust: the `Add`/`Mul` impls on
  `&RingElem` were deleted with the old schoolbook/Karatsuba multiplier, and products now
  go through the NTT (`arithmetic.ntt_arith.NttMatrix.mul`, proved in `NttBridge.lean` by
  `ntt_mul_spec` / `ntt_mul_transpose_spec`).  The correspondence proofs for those two
  operations went with them.

  What stays here is the part that never mentioned Rust: the closed form `convCoeff` of a
  coefficient of `Spec.Kopis.Polynomial.mul`, and `mul_get`, which proves the audited spec's
  double `Id.run` loop computes it.  `NttBridge` and `CoerceBridge`/`CoerceBridge10` are the
  consumers. -/

open scoped BigOperators

/-- Coefficient `m` of a stored `u16` list, as an element of `ZMod (2^16)`. -/
private def zc (l : List U16) (m : ℕ) : ZMod (2 ^ 16) := ((l[m]!).val : ZMod (2 ^ 16))

/-- Indexed-invariant evaluator for an `Id.run` `forIn'` loop over a `List` (replicated
locally from the `Serialize` module). -/
private theorem forIn'_getElem_indexed {α : Type} {β : Type} {m : Nat} :
    ∀ (xs : List α) (init : Vector β m)
    (body : (a : α) → a ∈ xs → Vector β m → Id (ForInStep (Vector β m)))
    (i : Nat) (hi : i < m) (val : β)
    (P : Nat → Vector β m → Prop)
    (hInit : P 0 init)
    (hFinal : ∀ dw, P xs.length dw → dw[i] = val)
    (_hStep : ∀ (k : Nat) (hk : k < xs.length) b, P k b →
      ∀ a (ha : a ∈ xs), a = xs[k]'hk →
      ∃ b', body a ha b = pure (ForInStep.yield b') ∧ P (k + 1) b'),
    (Id.run (forIn' xs init body))[i] = val := by
  intro xs; induction xs with
  | nil => intro init body i hi val P hInit hFinal _hStep; exact hFinal init hInit
  | cons x xs ih =>
    intro init body i hi val P hInit hFinal hStep
    simp only [List.forIn'_cons, Id.run, Bind.bind]
    obtain ⟨b', hb'_eq, hb'_P⟩ := hStep 0 (Nat.zero_lt_succ _) init hInit x (.head _) rfl
    conv_lhs => arg 1; rw [hb'_eq]
    exact ih b' (fun a' mm b => body a' (.tail _ mm) b) i hi val (fun k => P (k + 1))
      hb'_P
      (fun dw hP => hFinal dw (by rwa [List.length_cons]))
      (fun k hk b hPk a ha heq => by
        have hk' : k + 1 < (x :: xs).length := by simp; omega
        exact hStep (k + 1) hk' b hPk a (.tail _ ha) (by simp [heq]))

variable {m : ℕ}

/-- Contribution of the term `aᵢ·bⱼ` to output coefficient `p` in the negacyclic product. -/
def convContrib (a b : Spec.Kopis.Polynomial m) (i j p : ℕ) : ZMod m :=
  if (i + j) % 256 = p then (if i + j < 256 then a[i]! * b[j]! else -(a[i]! * b[j]!)) else 0

/-- Closed form of coefficient `p` of the negacyclic product. -/
def convCoeff (a b : Spec.Kopis.Polynomial m) (p : ℕ) : ZMod m :=
  ∑ i ∈ Finset.range 256, ∑ j ∈ Finset.range 256, convContrib a b i j p

set_option maxRecDepth 8000 in
theorem mul_get (a b : Spec.Kopis.Polynomial m) (p : ℕ) (hp : p < 256) :
    (Spec.Kopis.Polynomial.mul a b)[p]'hp = convCoeff a b p := by
  unfold Spec.Kopis.Polynomial.mul
  simp only [Aeneas.SRRange.forIn'_eq_forIn'_range', Aeneas.SRRange.size, Nat.sub_zero,
    Nat.add_sub_cancel, Nat.div_one]
  refine forIn'_getElem_indexed (List.range' 0 256) _ _ p hp _
    (P := fun I c => c[p]'hp = ∑ i ∈ Finset.range I, ∑ j ∈ Finset.range 256, convContrib a b i j p)
    ?hInit ?hFinal ?hStep
  case hInit =>
    show (Spec.Kopis.Polynomial.zero m)[p] = _
    simp [Spec.Kopis.Polynomial.zero, Vector.getElem_replicate]
  case hFinal =>
    intro dw hP
    rw [show (List.range' 0 256).length = 256 from by simp] at hP
    exact hP
  case hStep =>
    intro k hk c hPc a' ha' ha'eq
    have ha'k : a' = k := by rw [ha'eq]; simp [List.getElem_range']
    have ha'256 : a' < 256 := by rw [ha'k]; simpa using hk
    refine ⟨_, rfl, ?_⟩
    -- evaluate the inner loop over `j` via a second application of the indexed evaluator
    refine forIn'_getElem_indexed (List.range' 0 256) c _ p hp _
      (P := fun J cc => cc[p]'hp = (∑ i ∈ Finset.range k, ∑ j ∈ Finset.range 256, convContrib a b i j p)
        + ∑ j ∈ Finset.range J, convContrib a b a' j p)
      ?hI ?hF ?hS
    · rw [hPc]; simp
    · intro dw hP
      rw [show (List.range' 0 256).length = 256 from by simp] at hP
      rw [hP, ha'k]; exact (Finset.sum_range_succ _ k).symm
    · intro j hjk cc hPcc aa haa haaeq
      have haaj : aa = j := by rw [haaeq]; simp [List.getElem_range']
      subst haaj
      have haa256 : aa < 256 := by simpa using hjk
      rw [Finset.sum_range_succ]
      by_cases hC : a' + aa < 256
      · refine ⟨_, by rw [if_pos hC]; rfl, ?_⟩
        rw [Vector.getElem_set]
        by_cases hpk : (a' + aa) % 256 = p
        · rw [if_pos hpk, ← getElem!_pos cc ((a' + aa) % 256) (by rw [hpk]; exact hp), hpk,
            getElem!_pos cc p hp, hPcc, convContrib, if_pos hpk, if_pos hC,
            getElem!_pos a a' ha'256, getElem!_pos b aa haa256]
          ring
        · rw [if_neg hpk, hPcc, convContrib, if_neg hpk, add_zero]
      · refine ⟨_, by rw [if_neg hC]; rfl, ?_⟩
        rw [Vector.getElem_set]
        by_cases hpk : (a' + aa) % 256 = p
        · rw [if_pos hpk, ← getElem!_pos cc ((a' + aa) % 256) (by rw [hpk]; exact hp), hpk,
            getElem!_pos cc p hp, hPcc, convContrib, if_pos hpk, if_neg hC,
            getElem!_pos a a' ha'256, getElem!_pos b aa haa256]
          ring
        · rw [if_neg hpk, hPcc, convContrib, if_neg hpk, add_zero]

/-- Coefficient `i` of `toRingElem x` is the `ZMod` image `zc x.val i`. -/
private theorem toRingElem_getElem (x : RingElem) (i : ℕ) (hi : i < 256) :
    (toRingElem x)[i]! = zc x.val i := by
  rw [getElem!_pos (toRingElem x) i hi]
  unfold toRingElem zc
  rw [Vector.getElem_ofFn, getElem!_pos x.val i (by have := x.property; scalar_tac)]

/-! ## `RingElem::shift_right` / `RingElem::shift_left`

Both iterate over the coefficient slice via `IterMut`, replacing each `u16`
coefficient `c` by `c >> shift` (resp. `c << shift`).  The Rust `u16` shift is
only defined for `shift < 16`, so the correspondence carries that precondition
(matching every call site in the KEM, where the shift amounts are small).

The loop threads an outer write-back continuation `back`; the specs mirror the
canonical `IterMut` framing pattern (three predicates on `back`: length
preserved, positions `[0, i)` already shifted, positions `[i, len)` pass
through). -/

/-- **Loop spec** for `shift_right_loop`.  Positions `[0, iter.i)` of the result
hold the right-shifted originals; positions `[iter.i, len)` are untouched. -/
theorem shift_right_loop_spec
    (iter : core.slice.iter.IterMut U16)
    (back : core.slice.iter.IterMut U16 → core.slice.iter.IterMut U16)
    (shift : Usize) (hshift : shift.val < 16)
    (orig_slice : Slice U16)
    (h_slice : iter.slice = orig_slice)
    (h_iter_i : iter.i ≤ orig_slice.length)
    (hback_len : ∀ (im : core.slice.iter.IterMut U16),
      im.slice.length = orig_slice.length → (back im).slice.length = orig_slice.length)
    (hback_writes : ∀ (im : core.slice.iter.IterMut U16)
      (him : im.slice.length = orig_slice.length)
      (j : Nat) (_hj : j < iter.i),
        ((back im).slice.val[j]'(by have := hback_len im him; have := h_iter_i; scalar_tac)).val
          = (orig_slice.val[j]'(by have := h_iter_i; scalar_tac)).val >>> shift.val)
    (hback_rest : ∀ (im : core.slice.iter.IterMut U16)
      (him : im.slice.length = orig_slice.length)
      (j : Nat) (_hj_ge : iter.i ≤ j) (_hj_lt : j < orig_slice.length),
        (back im).slice.val[j]'(by have := hback_len im him; scalar_tac)
          = im.slice.val[j]'(by scalar_tac)) :
    arithmetic.plain_arith.RingElem.shift_right_loop iter back shift
      ⦃ (r : core.slice.iter.IterMut U16) =>
          ∃ (h_len : r.slice.length = orig_slice.length),
            ∀ (j : Nat) (_hj : j < orig_slice.length),
              (r.slice.val[j]'(by have := h_len; scalar_tac)).val
                = (orig_slice.val[j]'(by scalar_tac)).val >>> shift.val ⦄ := by
  unfold arithmetic.plain_arith.RingElem.shift_right_loop
  by_cases hlt : iter.i < iter.slice.len
  · -- SOME branch
    let* ⟨ o, iter1, next_back, h_all ⟩ ← iter_mut_next_spec
    obtain ⟨ho, hit2_slice, hit2_i, _, hsome_set⟩ := h_all
    rw [ho]
    simp only []
    have hi_pe : iter.slice.length = orig_slice.length := by rw [h_slice]
    have hi_lt : iter.i < orig_slice.length := by rw [← hi_pe]; scalar_tac
    let* ⟨ coeff1, hcoeff1_val, hcoeff1_bv ⟩ ← U16.ShiftRight_spec
    apply WP.spec_mono
      (shift_right_loop_spec iter1 (fun im => back (next_back im (some coeff1))) shift hshift
        orig_slice (by rw [hit2_slice, h_slice]) (by rw [hit2_i]; scalar_tac) ?len ?writes ?rest)
    case len =>
      intro im him
      have him_set : (next_back im (some coeff1)).slice.length = orig_slice.length := by
        rw [hsome_set]; simp only; rw [Slice.setAtNat_length]; exact him
      exact hback_len _ him_set
    case writes =>
      intro im him j hj
      rw [hit2_i] at hj
      have him_set : (next_back im (some coeff1)).slice.length = orig_slice.length := by
        rw [hsome_set]; simp only; rw [Slice.setAtNat_length]; exact him
      by_cases hji : j = iter.i
      · subst hji
        have hbk_len := hback_len _ him_set
        have hrest := hback_rest (next_back im (some coeff1)) him_set iter.i (le_refl _) hi_lt
        have hkey : (back (next_back im (some coeff1))).slice.val[iter.i]'(by
            have := hbk_len; scalar_tac) = coeff1 := by
          apply hrest.trans
          simp only [hsome_set]
          simp_lists [Slice.getElem_Nat_setAtNat_eq]
        rw [show ((back (next_back im (some coeff1))).slice.val[iter.i]'(by
              have := hbk_len; scalar_tac)).val = coeff1.val from by rw [hkey], hcoeff1_val]
        have hlv : iter.slice.val = orig_slice.val := by rw [h_slice]
        have helem : iter.slice[iter.i]'(by have := hi_lt; have := hi_pe; scalar_tac)
            = orig_slice.val[iter.i]'(by have := hi_lt; scalar_tac) := List.getElem_of_eq hlv _
        exact congrArg (fun x => x.val >>> shift.val) helem
      · have hjlt : j < iter.i := by omega
        exact hback_writes (next_back im (some coeff1)) him_set j hjlt
    case rest =>
      intro im him j hj_ge hj_lt
      rw [hit2_i] at hj_ge
      have him_set : (next_back im (some coeff1)).slice.length = orig_slice.length := by
        rw [hsome_set]; simp only; rw [Slice.setAtNat_length]; exact him
      have hrest := hback_rest (next_back im (some coeff1)) him_set j (by omega) hj_lt
      have hkey : (next_back im (some coeff1)).slice.val[j]'(by
          have := him_set; scalar_tac) = im.slice.val[j]'(by scalar_tac) := by
        simp only [hsome_set]
        simp_lists [Slice.getElem_Nat_setAtNat_ne]
      exact hrest.trans hkey
    intro r hpost; exact hpost
  · -- NONE branch
    have hge : iter.i ≥ iter.slice.len := by scalar_tac
    have hi_eq : iter.i = orig_slice.length := by
      have hpe : iter.slice.length = orig_slice.length := by rw [h_slice]
      have : iter.slice.len.val = orig_slice.length := by
        rw [← hpe]; simp [Slice.len, Slice.length]
      scalar_tac
    let* ⟨ o, iter1, next_back, h_all ⟩ ← iter_mut_next_spec_none
    obtain ⟨ho, hit2_eq, hsome_back⟩ := h_all
    rw [ho]
    show (Result.ok (back (next_back iter1 none))) ⦃ _ ⦄
    rw [hsome_back, hit2_eq]
    have hit_pe : iter.slice.length = orig_slice.length := by rw [h_slice]
    refine ⟨hback_len iter hit_pe, ?_⟩
    intro j hj
    exact hback_writes iter hit_pe j (hi_eq ▸ hj)
  termination_by iter.slice.len.val - iter.i
  decreasing_by scalar_decr_tac

/-- **Correctness of `RingElem::shift_right`** (for `shift < 16`): computes the
audited coefficient-wise right shift `Spec.Kopis.Polynomial.shiftRight`. -/
theorem shift_right_spec (self : RingElem) (shift : Usize) (hshift : shift.val < 16) :
    arithmetic.plain_arith.RingElem.shift_right self shift
      ⦃ (r : RingElem) =>
          toRingElem r = Spec.Kopis.Polynomial.shiftRight (toRingElem self) shift.val ⦄ := by
  unfold arithmetic.plain_arith.RingElem.shift_right
  let* ⟨ s, to_back, hs_val, hto_back ⟩ ← Array.to_slice_mut_spec
  let* ⟨ it0, it_back, h_it_slice, h_it_zero, h_it_back ⟩ ← iter_mut_spec
  let* ⟨ r_iter, hr_len, hr_writes ⟩ ←
    shift_right_loop_spec it0 (fun im => im) shift hshift it0.slice rfl
      (by rw [h_it_zero]; exact Nat.zero_le _)
      (fun _ him => him)
      (fun _ _ j hj => by rw [h_it_zero] at hj; omega)
      (fun _ _ _ _ _ => rfl)
  simp only [h_it_back]
  apply Vector.ext
  intro j hj
  have hs_len : s.length = 256 := by simp only [Slice.length, hs_val]; exact self.property
  have hit_len : it0.slice.length = 256 := by rw [h_it_slice]; exact hs_len
  have hj_s : j < it0.slice.length := by scalar_tac
  have hri_len : r_iter.slice.length = 256 := by rw [hr_len]; exact hit_len
  have h_val_eq : (to_back r_iter.slice).val = r_iter.slice.val := by
    rw [hto_back]; exact Std.Array.from_slice_val self r_iter.slice hri_len
  have htb_len : (to_back r_iter.slice).val.length = 256 := by rw [h_val_eq]; exact hri_len
  unfold toRingElem Spec.Kopis.Polynomial.shiftRight
  rw [Vector.getElem_ofFn, Vector.getElem_map, Vector.getElem_ofFn]
  -- LHS coefficient
  have hval : ((to_back r_iter.slice).val[j]'(by scalar_tac)).val
      = (it0.slice.val[j]'(by scalar_tac)).val >>> shift.val := by
    have h1 : (to_back r_iter.slice).val[j]'(by scalar_tac)
        = r_iter.slice.val[j]'(by scalar_tac) := List.getElem_of_eq h_val_eq _
    rw [h1]; exact hr_writes j hj_s
  -- Both sides equal ((self.val[j].val >>> shift) : ZMod (2^16))
  have hself : (it0.slice.val[j]'hj_s).val = (self.val[j]'(by have := self.property; grind)).val :=
    congrArg (·.val) (List.getElem_of_eq
      (show (it0.slice.val : List U16) = self.val by rw [h_it_slice]; exact hs_val) _)
  have hlt16 : (self.val[j]'(by have := self.property; grind)).val < 2 ^ 16 := by scalar_tac
  rw [hval]; congr 1; congr 1
  exact hself.trans (ZMod.val_natCast_of_lt hlt16).symm

/-- **Loop spec** for `shift_left_loop`.  Positions `[0, iter.i)` of the result
hold the (mod-`2¹⁶`) left-shifted originals; `[iter.i, len)` are untouched. -/
theorem shift_left_loop_spec
    (iter : core.slice.iter.IterMut U16)
    (back : core.slice.iter.IterMut U16 → core.slice.iter.IterMut U16)
    (shift : Usize) (hshift : shift.val < 16)
    (orig_slice : Slice U16)
    (h_slice : iter.slice = orig_slice)
    (h_iter_i : iter.i ≤ orig_slice.length)
    (hback_len : ∀ (im : core.slice.iter.IterMut U16),
      im.slice.length = orig_slice.length → (back im).slice.length = orig_slice.length)
    (hback_writes : ∀ (im : core.slice.iter.IterMut U16)
      (him : im.slice.length = orig_slice.length)
      (j : Nat) (_hj : j < iter.i),
        ((back im).slice.val[j]'(by have := hback_len im him; have := h_iter_i; scalar_tac)).val
          = ((orig_slice.val[j]'(by have := h_iter_i; scalar_tac)).val <<< shift.val) % U16.size)
    (hback_rest : ∀ (im : core.slice.iter.IterMut U16)
      (him : im.slice.length = orig_slice.length)
      (j : Nat) (_hj_ge : iter.i ≤ j) (_hj_lt : j < orig_slice.length),
        (back im).slice.val[j]'(by have := hback_len im him; scalar_tac)
          = im.slice.val[j]'(by scalar_tac)) :
    arithmetic.plain_arith.RingElem.shift_left_loop iter back shift
      ⦃ (r : core.slice.iter.IterMut U16) =>
          ∃ (h_len : r.slice.length = orig_slice.length),
            ∀ (j : Nat) (_hj : j < orig_slice.length),
              (r.slice.val[j]'(by have := h_len; scalar_tac)).val
                = ((orig_slice.val[j]'(by scalar_tac)).val <<< shift.val) % U16.size ⦄ := by
  unfold arithmetic.plain_arith.RingElem.shift_left_loop
  by_cases hlt : iter.i < iter.slice.len
  · -- SOME branch
    let* ⟨ o, iter1, next_back, h_all ⟩ ← iter_mut_next_spec
    obtain ⟨ho, hit2_slice, hit2_i, _, hsome_set⟩ := h_all
    rw [ho]
    simp only []
    have hi_pe : iter.slice.length = orig_slice.length := by rw [h_slice]
    have hi_lt : iter.i < orig_slice.length := by rw [← hi_pe]; scalar_tac
    let* ⟨ coeff1, hcoeff1_val, hcoeff1_bv ⟩ ← U16.ShiftLeft_spec
    apply WP.spec_mono
      (shift_left_loop_spec iter1 (fun im => back (next_back im (some coeff1))) shift hshift
        orig_slice (by rw [hit2_slice, h_slice]) (by rw [hit2_i]; scalar_tac) ?len ?writes ?rest)
    case len =>
      intro im him
      have him_set : (next_back im (some coeff1)).slice.length = orig_slice.length := by
        rw [hsome_set]; simp only; rw [Slice.setAtNat_length]; exact him
      exact hback_len _ him_set
    case writes =>
      intro im him j hj
      rw [hit2_i] at hj
      have him_set : (next_back im (some coeff1)).slice.length = orig_slice.length := by
        rw [hsome_set]; simp only; rw [Slice.setAtNat_length]; exact him
      by_cases hji : j = iter.i
      · subst hji
        have hbk_len := hback_len _ him_set
        have hrest := hback_rest (next_back im (some coeff1)) him_set iter.i (le_refl _) hi_lt
        have hkey : (back (next_back im (some coeff1))).slice.val[iter.i]'(by
            have := hbk_len; scalar_tac) = coeff1 := by
          apply hrest.trans
          simp only [hsome_set]
          simp_lists [Slice.getElem_Nat_setAtNat_eq]
        rw [show ((back (next_back im (some coeff1))).slice.val[iter.i]'(by
              have := hbk_len; scalar_tac)).val = coeff1.val from by rw [hkey], hcoeff1_val]
        have hlv : iter.slice.val = orig_slice.val := by rw [h_slice]
        have helem : iter.slice[iter.i]'(by have := hi_lt; have := hi_pe; scalar_tac)
            = orig_slice.val[iter.i]'(by have := hi_lt; scalar_tac) := List.getElem_of_eq hlv _
        first
          | exact congrArg (fun x => x.val >>> shift.val) helem
          | exact congrArg (fun x => (x.val <<< shift.val) % U16.size) helem
      · have hjlt : j < iter.i := by omega
        exact hback_writes (next_back im (some coeff1)) him_set j hjlt
    case rest =>
      intro im him j hj_ge hj_lt
      rw [hit2_i] at hj_ge
      have him_set : (next_back im (some coeff1)).slice.length = orig_slice.length := by
        rw [hsome_set]; simp only; rw [Slice.setAtNat_length]; exact him
      have hrest := hback_rest (next_back im (some coeff1)) him_set j (by omega) hj_lt
      have hkey : (next_back im (some coeff1)).slice.val[j]'(by
          have := him_set; scalar_tac) = im.slice.val[j]'(by scalar_tac) := by
        simp only [hsome_set]
        simp_lists [Slice.getElem_Nat_setAtNat_ne]
      exact hrest.trans hkey
    intro r hpost; exact hpost
  · -- NONE branch
    have hge : iter.i ≥ iter.slice.len := by scalar_tac
    have hi_eq : iter.i = orig_slice.length := by
      have hpe : iter.slice.length = orig_slice.length := by rw [h_slice]
      have : iter.slice.len.val = orig_slice.length := by
        rw [← hpe]; simp [Slice.len, Slice.length]
      scalar_tac
    let* ⟨ o, iter1, next_back, h_all ⟩ ← iter_mut_next_spec_none
    obtain ⟨ho, hit2_eq, hsome_back⟩ := h_all
    rw [ho]
    show (Result.ok (back (next_back iter1 none))) ⦃ _ ⦄
    rw [hsome_back, hit2_eq]
    have hit_pe : iter.slice.length = orig_slice.length := by rw [h_slice]
    refine ⟨hback_len iter hit_pe, ?_⟩
    intro j hj
    exact hback_writes iter hit_pe j (hi_eq ▸ hj)
  termination_by iter.slice.len.val - iter.i
  decreasing_by scalar_decr_tac

/-- **Correctness of `RingElem::shift_left`** (for `shift < 16`): computes the
audited coefficient-wise left shift `Spec.Kopis.Polynomial.shiftLeft` (the cast
back into `ZMod (2¹⁶)` performs the `mod 2¹⁶` reduction the `u16` shift does). -/
theorem shift_left_spec (self : RingElem) (shift : Usize) (hshift : shift.val < 16) :
    arithmetic.plain_arith.RingElem.shift_left self shift
      ⦃ (r : RingElem) =>
          toRingElem r = Spec.Kopis.Polynomial.shiftLeft (toRingElem self) shift.val ⦄ := by
  unfold arithmetic.plain_arith.RingElem.shift_left
  let* ⟨ s, to_back, hs_val, hto_back ⟩ ← Array.to_slice_mut_spec
  let* ⟨ it0, it_back, h_it_slice, h_it_zero, h_it_back ⟩ ← iter_mut_spec
  let* ⟨ r_iter, hr_len, hr_writes ⟩ ←
    shift_left_loop_spec it0 (fun im => im) shift hshift it0.slice rfl
      (by rw [h_it_zero]; exact Nat.zero_le _)
      (fun _ him => him)
      (fun _ _ j hj => by rw [h_it_zero] at hj; omega)
      (fun _ _ _ _ _ => rfl)
  simp only [h_it_back]
  apply Vector.ext
  intro j hj
  have hs_len : s.length = 256 := by simp only [Slice.length, hs_val]; exact self.property
  have hit_len : it0.slice.length = 256 := by rw [h_it_slice]; exact hs_len
  have hj_s : j < it0.slice.length := by scalar_tac
  have hri_len : r_iter.slice.length = 256 := by rw [hr_len]; exact hit_len
  have h_val_eq : (to_back r_iter.slice).val = r_iter.slice.val := by
    rw [hto_back]; exact Std.Array.from_slice_val self r_iter.slice hri_len
  have htb_len : (to_back r_iter.slice).val.length = 256 := by rw [h_val_eq]; exact hri_len
  have hUsize : U16.size = 2 ^ 16 := by simp [U16.size, U16.numBits]
  unfold toRingElem Spec.Kopis.Polynomial.shiftLeft
  rw [Vector.getElem_ofFn, Vector.getElem_map, Vector.getElem_ofFn]
  have hval : ((to_back r_iter.slice).val[j]'(by scalar_tac)).val
      = ((it0.slice.val[j]'(by scalar_tac)).val <<< shift.val) % U16.size := by
    have h1 : (to_back r_iter.slice).val[j]'(by scalar_tac)
        = r_iter.slice.val[j]'(by scalar_tac) := List.getElem_of_eq h_val_eq _
    rw [h1]; exact hr_writes j hj_s
  have hself : (it0.slice.val[j]'hj_s).val = (self.val[j]'(by have := self.property; grind)).val :=
    congrArg (·.val) (List.getElem_of_eq
      (show (it0.slice.val : List U16) = self.val by rw [h_it_slice]; exact hs_val) _)
  have hlt16 : (self.val[j]'(by have := self.property; grind)).val < 2 ^ 16 := by scalar_tac
  rw [hval, hUsize, ZMod.natCast_mod]; congr 1; congr 1
  exact hself.trans (ZMod.val_natCast_of_lt hlt16).symm

/-! ## `RingElem::wrapping_add_to_all` — add a fixed `u16` to every coefficient
(mod 2¹⁶).  Same `IterMut` skeleton as the shifts; the loop invariant is stated
at the `u16`-element level (`= wrapping_add orig val`) and cast to `ZMod` via
`wrapping_add_toZMod`. -/

/-- **Loop spec** for `wrapping_add_to_all_loop`. -/
theorem wrapping_add_to_all_loop_spec
    (iter : core.slice.iter.IterMut U16)
    (back : core.slice.iter.IterMut U16 → core.slice.iter.IterMut U16)
    (val : U16)
    (orig_slice : Slice U16)
    (h_slice : iter.slice = orig_slice)
    (h_iter_i : iter.i ≤ orig_slice.length)
    (hback_len : ∀ (im : core.slice.iter.IterMut U16),
      im.slice.length = orig_slice.length → (back im).slice.length = orig_slice.length)
    (hback_writes : ∀ (im : core.slice.iter.IterMut U16)
      (him : im.slice.length = orig_slice.length)
      (j : Nat) (_hj : j < iter.i),
        (back im).slice.val[j]'(by have := hback_len im him; have := h_iter_i; scalar_tac)
          = core.num.U16.wrapping_add (orig_slice.val[j]'(by have := h_iter_i; scalar_tac)) val)
    (hback_rest : ∀ (im : core.slice.iter.IterMut U16)
      (him : im.slice.length = orig_slice.length)
      (j : Nat) (_hj_ge : iter.i ≤ j) (_hj_lt : j < orig_slice.length),
        (back im).slice.val[j]'(by have := hback_len im him; scalar_tac)
          = im.slice.val[j]'(by scalar_tac)) :
    arithmetic.plain_arith.RingElem.wrapping_add_to_all_loop iter back val
      ⦃ (r : core.slice.iter.IterMut U16) =>
          ∃ (h_len : r.slice.length = orig_slice.length),
            ∀ (j : Nat) (_hj : j < orig_slice.length),
              r.slice.val[j]'(by have := h_len; scalar_tac)
                = core.num.U16.wrapping_add (orig_slice.val[j]'(by scalar_tac)) val ⦄ := by
  unfold arithmetic.plain_arith.RingElem.wrapping_add_to_all_loop
  by_cases hlt : iter.i < iter.slice.len
  · let* ⟨ o, iter1, next_back, h_all ⟩ ← iter_mut_next_spec
    obtain ⟨ho, hit2_slice, hit2_i, _, hsome_set⟩ := h_all
    rw [ho]
    simp only []
    have hi_pe : iter.slice.length = orig_slice.length := by rw [h_slice]
    have hi_lt : iter.i < orig_slice.length := by rw [← hi_pe]; scalar_tac
    simp only [lift, bind_tc_ok]
    set coeff1 := core.num.U16.wrapping_add iter.slice[iter.i] val with hc1
    apply WP.spec_mono
      (wrapping_add_to_all_loop_spec iter1 (fun im => back (next_back im (some coeff1))) val
        orig_slice (by rw [hit2_slice, h_slice]) (by rw [hit2_i]; scalar_tac) ?len ?writes ?rest)
    case len =>
      intro im him
      have him_set : (next_back im (some coeff1)).slice.length = orig_slice.length := by
        rw [hsome_set]; simp only; rw [Slice.setAtNat_length]; exact him
      exact hback_len _ him_set
    case writes =>
      intro im him j hj
      rw [hit2_i] at hj
      have him_set : (next_back im (some coeff1)).slice.length = orig_slice.length := by
        rw [hsome_set]; simp only; rw [Slice.setAtNat_length]; exact him
      by_cases hji : j = iter.i
      · subst hji
        have hbk_len := hback_len _ him_set
        have hrest := hback_rest (next_back im (some coeff1)) him_set iter.i (le_refl _) hi_lt
        have hkey : (back (next_back im (some coeff1))).slice.val[iter.i]'(by
            have := hbk_len; scalar_tac) = coeff1 := by
          apply hrest.trans
          simp only [hsome_set]
          simp_lists [Slice.getElem_Nat_setAtNat_eq]
        have hlv : iter.slice.val = orig_slice.val := by rw [h_slice]
        have helem : iter.slice[iter.i]'(by have := hi_lt; have := hi_pe; scalar_tac)
            = orig_slice.val[iter.i]'(by have := hi_lt; scalar_tac) := List.getElem_of_eq hlv _
        rw [hkey, hc1]; exact congrArg (fun x => core.num.U16.wrapping_add x val) helem
      · have hjlt : j < iter.i := by omega
        exact hback_writes (next_back im (some coeff1)) him_set j hjlt
    case rest =>
      intro im him j hj_ge hj_lt
      rw [hit2_i] at hj_ge
      have him_set : (next_back im (some coeff1)).slice.length = orig_slice.length := by
        rw [hsome_set]; simp only; rw [Slice.setAtNat_length]; exact him
      have hrest := hback_rest (next_back im (some coeff1)) him_set j (by omega) hj_lt
      have hkey : (next_back im (some coeff1)).slice.val[j]'(by
          have := him_set; scalar_tac) = im.slice.val[j]'(by scalar_tac) := by
        simp only [hsome_set]
        simp_lists [Slice.getElem_Nat_setAtNat_ne]
      exact hrest.trans hkey
    intro r hpost; exact hpost
  · have hge : iter.i ≥ iter.slice.len := by scalar_tac
    have hi_eq : iter.i = orig_slice.length := by
      have hpe : iter.slice.length = orig_slice.length := by rw [h_slice]
      have : iter.slice.len.val = orig_slice.length := by
        rw [← hpe]; simp [Slice.len, Slice.length]
      scalar_tac
    let* ⟨ o, iter1, next_back, h_all ⟩ ← iter_mut_next_spec_none
    obtain ⟨ho, hit2_eq, hsome_back⟩ := h_all
    rw [ho]
    show (Result.ok (back (next_back iter1 none))) ⦃ _ ⦄
    rw [hsome_back, hit2_eq]
    have hit_pe : iter.slice.length = orig_slice.length := by rw [h_slice]
    refine ⟨hback_len iter hit_pe, ?_⟩
    intro j hj
    exact hback_writes iter hit_pe j (hi_eq ▸ hj)
  termination_by iter.slice.len.val - iter.i
  decreasing_by scalar_decr_tac

/-- **Correctness of `RingElem::wrapping_add_to_all`**: adds the constant `val` to
every coefficient (mod 2¹⁶), i.e. `+ Polynomial.const val` on the abstraction. -/
theorem wrapping_add_to_all_spec (self : RingElem) (val : U16) :
    arithmetic.plain_arith.RingElem.wrapping_add_to_all self val
      ⦃ (r : RingElem) =>
          toRingElem r = Spec.Kopis.Polynomial.add (toRingElem self)
            (Spec.Kopis.Polynomial.const (2 ^ 16) ((val.val : ZMod (2 ^ 16)))) ⦄ := by
  unfold arithmetic.plain_arith.RingElem.wrapping_add_to_all
  let* ⟨ s, to_back, hs_val, hto_back ⟩ ← Array.to_slice_mut_spec
  let* ⟨ it0, it_back, h_it_slice, h_it_zero, h_it_back ⟩ ← iter_mut_spec
  let* ⟨ r_iter, hr_len, hr_writes ⟩ ←
    wrapping_add_to_all_loop_spec it0 (fun im => im) val it0.slice rfl
      (by rw [h_it_zero]; exact Nat.zero_le _)
      (fun _ him => him)
      (fun _ _ j hj => by rw [h_it_zero] at hj; omega)
      (fun _ _ _ _ _ => rfl)
  simp only [h_it_back]
  apply Vector.ext
  intro j hj
  have hs_len : s.length = 256 := by simp only [Slice.length, hs_val]; exact self.property
  have hit_len : it0.slice.length = 256 := by rw [h_it_slice]; exact hs_len
  have hj_s : j < it0.slice.length := by scalar_tac
  have hri_len : r_iter.slice.length = 256 := by rw [hr_len]; exact hit_len
  have h_val_eq : (to_back r_iter.slice).val = r_iter.slice.val := by
    rw [hto_back]; exact Std.Array.from_slice_val self r_iter.slice hri_len
  have htb_len : (to_back r_iter.slice).val.length = 256 := by rw [h_val_eq]; exact hri_len
  unfold toRingElem Spec.Kopis.Polynomial.const Spec.Kopis.Polynomial.add
  rw [Vector.getElem_ofFn, Vector.getElem_zipWith, Vector.getElem_ofFn, Vector.getElem_replicate]
  -- element equality
  have hval : (to_back r_iter.slice).val[j]'(by scalar_tac)
      = core.num.U16.wrapping_add (it0.slice.val[j]'(by scalar_tac)) val := by
    have h1 : (to_back r_iter.slice).val[j]'(by scalar_tac)
        = r_iter.slice.val[j]'(by scalar_tac) := List.getElem_of_eq h_val_eq _
    rw [h1]; exact hr_writes j hj_s
  have hself : (it0.slice.val[j]'hj_s) = self.val[j]'(by have := self.property; grind) :=
    List.getElem_of_eq (show (it0.slice.val : List U16) = self.val by rw [h_it_slice]; exact hs_val) _
  rw [show ((to_back r_iter.slice).val[j]'(by scalar_tac)).val
        = (core.num.U16.wrapping_add (self.val[j]'(by have := self.property; grind)) val).val
        from by rw [hval, hself]]
  rw [wrapping_add_toZMod]
end Kopis.Neon.Properties
