-- AUTOGENERATED from Kopis/Properties/RoundTop.lean by `make generated`.  Do not edit.
-- See NEON_VERIFICATION_PLAN.md phase E: the serial proof, with the extracted
-- constants and this stack's namespace renamed, and nothing else changed.
import Kopis.Bits.Stream
import Kopis.Neon.Properties.ProdBridge
import Kopis.Neon.Properties.RoundBridge
import Kopis.Neon.Properties.MatrixArith
open Aeneas Aeneas.Std Result RustKopisNeon
open scoped BigOperators
namespace Kopis.Neon.Properties

open Kopis.Properties (streamBit streamNat streamNat_zero streamNat_succ streamBit_le_one streamNat_lt streamNat_split lor_add_of_lt lor_mul_of_lt sum_testBit_eq_mod streamNat_byte streamByte streamByte_lt sum_base256 testBit_sum_bytes streamNat_of_byteWindow cbdX cbdX_le testBit_streamNat cbdX_eq_bitSum streamNat_mod streamNat_shiftRight cbdX_eq_bitSum_of_le cbdU16)

open arithmetic.matrix_arith (Matrix)
open arithmetic.ring_arith (RingElem)

set_option maxHeartbeats 1000000

/-- `toRingElem`'s coefficient value is the physical `u16` value. -/
theorem toRingElem_coeff_val (re : RingElem) (k : ℕ) (hk : k < 256) :
    ((toRingElem re)[k]!).val = (re.val[k]!).val := by
  have hb : k < re.val.length := by have := re.property; grind
  have hlt : (re.val[k]'hb).val < 2 ^ 16 := by
    have h := (re.val[k]'hb).hBounds; simpa only [UScalarTy.numBits] using h
  rw [getElem!_pos (toRingElem re) k hk, getElem!_pos re.val k hb]
  simp only [toRingElem, Vector.getElem_ofFn]
  rw [ZMod.val_natCast, Nat.mod_eq_of_lt hlt]

/-- **Full CompressToR10 correspondence (Rust side).** -/
theorem prod2_roundR10_bridge {L : Usize} (mat_a : Matrix L L) (vec_s : Matrix L 1#usize)
    (prod prod1 prod2 : Matrix L 1#usize) (i : ℕ) (hi : i < L.val)
    (hmt : ∀ i₀ : ℕ, i₀ < L.val → toRingElem ((prod.val[i₀]!).val[0]!)
        = ∑ ii ∈ Finset.range L.val,
            toRingElem ((mat_a.val[ii]!).val[i₀]!) * toRingElem ((vec_s.val[ii]!).val[0]!))
    (hw : toRingElem ((prod1.val[i]!).val[0]!)
        = addC 4#u16 (toRingElem ((prod.val[i]!).val[0]!)))
    (hs : toRingElem ((prod2.val[i]!).val[0]!)
        = Spec.Kopis.Polynomial.shiftRight (toRingElem ((prod1.val[i]!).val[0]!)) 3) :
    toPolyN 10 ((prod2.val[i]!).val[0]!)
      = (Spec.Kopis.CompressToR10 L.val
          (Spec.Kopis.matVecMul (Matrix.transpose (toMatrix13 mat_a)) (toVector13 vec_s)))[i]'hi := by
  haveI : NeZero ((2 : ℕ) ^ 10) := ⟨by positivity⟩
  apply Vector.ext
  intro k hk
  apply ZMod.val_injective
  set vv := Spec.Kopis.matVecMul (Matrix.transpose (toMatrix13 mat_a)) (toVector13 vec_s) with hvv
  rw [roundR10_coeff vv i hi k hk,
    ← getElem!_pos (toPolyN 10 ((prod2.val[i]!).val[0]!)) k hk, toPolyN_val 10 _ k hk,
    ← toRingElem_coeff_val _ k hk, getElem!_pos _ k hk, hs]
  simp only [Spec.Kopis.Polynomial.shiftRight, Vector.getElem_map, ZMod.val_natCast]
  -- prod1 coeff = prod coeff + 4 (mod 2^16)
  have h4 : (4 : ZMod (2 ^ 16)).val = 4 := by decide
  have hp1 : ((toRingElem ((prod1.val[i]!).val[0]!))[k]'hk).val
      = (((toRingElem ((prod.val[i]!).val[0]!))[k]'hk).val + 4) % 2 ^ 16 := by
    rw [hw]
    show (((Spec.Kopis.Polynomial.add (toRingElem ((prod.val[i]!).val[0]!))
        (Spec.Kopis.Polynomial.const (2 ^ 16) ((4#u16).val : ZMod (2 ^ 16))))[k]'hk).val : ℕ) = _
    have hc4 : ((4#u16).val : ZMod (2 ^ 16)) = 4 := by decide
    simp only [Spec.Kopis.Polynomial.add, Vector.getElem_zipWith, Spec.Kopis.Polynomial.const,
      Vector.getElem_replicate, hc4, ZMod.val_add, h4]
  rw [hp1]
  set c := ((toRingElem ((prod.val[i]!).val[0]!))[k]'hk).val with hc
  rw [Nat.mod_mod_of_dvd _ (show (2 : ℕ) ^ 10 ∣ 2 ^ 16 from by norm_num), round10_bridge c]
  -- vv[i][k].val = c % 2^13
  have hvvc : ((vv[i]'hi)[k]'hk).val = c % 2 ^ 13 := by
    have hb := prod_matVecMul_bridge mat_a vec_s prod i hi hmt
    rw [hvv, ← hb, coerce_getElem _ k hk, ZMod.val_natCast, ← hc]
  rw [hvvc]

end Kopis.Neon.Properties
