-- AUTOGENERATED from Kopis/Properties/SerializeSpec2.lean by `make generated`.  Do not edit.
-- See NEON_VERIFICATION_PLAN.md phase E: the serial proof, with the extracted
-- constants and this stack's namespace renamed, and nothing else changed.
import Kopis.Bits.Stream
import Kopis.Neon.Properties.SerializeSpec
open Aeneas Aeneas.Std Result
open scoped BigOperators
namespace Kopis.Neon.Properties

open Kopis.Properties (streamBit streamNat streamNat_zero streamNat_succ streamBit_le_one streamNat_lt streamNat_split lor_add_of_lt lor_mul_of_lt sum_testBit_eq_mod streamNat_byte streamByte streamByte_lt sum_base256 testBit_sum_bytes streamNat_of_byteWindow cbdX cbdX_le testBit_streamNat cbdX_eq_bitSum streamNat_mod streamNat_shiftRight cbdX_eq_bitSum_of_le cbdU16)

set_option maxHeartbeats 2000000
set_option maxRecDepth 4000

/-- Generic invariant-threading for an `Id.run` `forIn'` loop. -/
private theorem forIn'_inv {α : Type} {β : Type} :
    ∀ (xs : List α) (init : β)
    (body : (a : α) → a ∈ xs → β → Id (ForInStep β))
    (P : Nat → β → Prop)
    (_hInit : P 0 init)
    (_hStep : ∀ (k : Nat) (hk : k < xs.length) b, P k b →
      ∀ a (ha : a ∈ xs), a = xs[k]'hk →
      ∃ b', body a ha b = pure (ForInStep.yield b') ∧ P (k + 1) b'),
    P xs.length (Id.run (forIn' xs init body)) := by
  intro xs; induction xs with
  | nil => intro init body P hInit _; exact hInit
  | cons x xs ih =>
    intro init body P hInit hStep
    obtain ⟨b', hb'_eq, hb'_P⟩ := hStep 0 (Nat.zero_lt_succ _) init hInit x (.head _) rfl
    have hrun : Id.run (forIn' (x :: xs) init body)
        = Id.run (forIn' xs b' (fun a' mm b => body a' (.tail _ mm) b)) := by
      simp only [List.forIn'_cons, Id.run, Bind.bind, hb'_eq]; rfl
    rw [show (x :: xs).length = xs.length + 1 from rfl, hrun]
    exact ih b' (fun a' mm b => body a' (.tail _ mm) b) (fun k => P (k + 1)) hb'_P
      (fun k hk b hPk a ha heq => by
        have hk' : k + 1 < (x :: xs).length := by simp; omega
        exact hStep (k + 1) hk' b hPk a (.tail _ ha) (by simp [heq]))

private theorem forIn'_inv' {α : Type} {β : Type} (xs : List α) (init : β)
    (body : (a : α) → a ∈ xs → β → Id (ForInStep β)) (P : Nat → β → Prop) (n : Nat)
    (hn : xs.length = n) (hInit : P 0 init)
    (hStep : ∀ (k : Nat) (hk : k < xs.length) b, P k b →
      ∀ a (ha : a ∈ xs), a = xs[k]'hk →
      ∃ b', body a ha b = pure (ForInStep.yield b') ∧ P (k + 1) b') :
    P n (Id.run (forIn' xs init body)) :=
  hn ▸ forIn'_inv xs init body P hInit hStep

/-- Same as `forIn'_inv'` but concluding about the bare `forIn'` (no `Id.run`), for use
where the loop is bound directly inside another `do`-block. -/
private theorem forIn'_inv'_run {α : Type} {β : Type} (xs : List α) (init : β)
    (body : (a : α) → a ∈ xs → β → Id (ForInStep β)) (P : Nat → β → Prop) (n : Nat)
    (hn : xs.length = n) (hInit : P 0 init)
    (hStep : ∀ (k : Nat) (hk : k < xs.length) b, P k b →
      ∀ a (ha : a ∈ xs), a = xs[k]'hk →
      ∃ b', body a ha b = pure (ForInStep.yield b') ∧ P (k + 1) b') :
    P n (forIn' xs init body) :=
  forIn'_inv' xs init body P n hn hInit hStep

private theorem vget_set {N : ℕ} {γ : Type*} (v : Vector γ N) (i : ℕ) (x : γ) (hi : i < N)
    (k : ℕ) (hk : k < N) : (v.set i x)[k]'hk = if k = i then x else v[k]'hk := by
  rw [Vector.getElem_set]; split_ifs with h1 h2 h2 <;> first | rfl | omega

/-- `Bool.ofNat ((x / 2^s) % 2) = x.testBit s`. -/
private theorem ofNat_div_mod_eq_testBit (x s : ℕ) : Bool.ofNat ((x / 2 ^ s) % 2) = x.testBit s := by
  rw [Nat.testBit_eq_decide_div_mod_eq]
  rcases Nat.mod_two_eq_zero_or_one (x / 2 ^ s) with h | h <;> simp [h, Bool.ofNat]

private theorem bitsToBytes_run {N : ℕ} (comp : Id (Vector Bool (8 * N))) :
    Id.run (do let b ← comp; pure (Spec.bitsToBytes b)) = Spec.bitsToBytes (Id.run comp) := rfl

/-- **The serialize bit-correspondence.**  Bit `j` of byte `p` of `serialize n r` is bit
`(8p+j) mod n` of coefficient `(8p+j)/n`. -/
theorem serialize_byte_bit (n : ℕ) (r : Spec.Kopis.Polynomial (2 ^ n)) (p j : ℕ)
    (hp : p < 32 * n) (hj : j < 8) (hn : 0 < n) :
    ((Spec.Kopis.serialize n r)[p]'hp).toNat.testBit j
      = (r[(8 * p + j) / n]'(by rw [Nat.div_lt_iff_lt_mul hn]; omega)).val.testBit
          ((8 * p + j) % n) := by
  unfold Spec.Kopis.serialize
  rw [bitsToBytes_run, Spec.bitsToBytes_testBit _ p hp j hj]
  set m := 8 * p + j with hmdef
  have hm_lt : m < 8 * (32 * n) := by omega
  have hi0 : m / n < 256 := by rw [Nat.div_lt_iff_lt_mul hn]; omega
  have hs0 : m % n < n := Nat.mod_lt m hn
  have hri : m / n < (256 : ℕ) := hi0
  -- outer loop invariant
  simp only [Aeneas.SRRange.forIn'_eq_forIn'_range', Aeneas.SRRange.size, Nat.sub_zero,
    Nat.add_sub_cancel, Nat.div_one]
  rw [show (r[m / n]'hi0).val.testBit (m % n)
      = if m / n < 256 then (r[m / n]'hi0).val.testBit (m % n)
        else false from (if_pos hi0).symm]
  refine forIn'_inv' (List.range' 0 256) _ _
    (fun cnt (b : Vector Bool (8 * (32 * n))) =>
      b[m]'hm_lt = if m / n < cnt
        then (r[m / n]'hi0).val.testBit (m % n) else false)
    256 (by simp) ?init ?step
  case init =>
    simp only [Nat.not_lt_zero, if_false, Vector.getElem_replicate]
  case step =>
    intro cnt hcnt b hb x hx hxeq
    have hx_val : x = cnt := by rw [hxeq]; simp [List.getElem_range']
    subst hx_val
    have hx_lt : x < 256 := by simpa using hcnt
    refine ⟨_, rfl, ?_⟩
    -- align the outer target with the inner-loop final state
    rw [show (if m / n < x + 1 then (r[m / n]'hi0).val.testBit (m % n) else false)
          = if (x = m / n ∧ m % n < n) then (r[m / n]'hi0).val.testBit (m % n) else b[m]'hm_lt from by
        rw [hb]; simp only [hs0, and_true]; split_ifs <;> first | rfl | omega]
    -- inner loop invariant: `a = r[x].val / 2^cnt2`, and bit `m` set iff processed
    refine (forIn'_inv'_run (List.range' 0 n) (⟨r[x].val, b⟩ : MProd ℕ (Vector Bool (8 * (32 * n))))
      (fun j2 hj2 st => do
        pure PUnit.unit
        pure (ForInStep.yield ⟨st.fst / 2, st.snd.set (n * x + j2) (Bool.ofNat (st.fst % 2)) (by
          have := List.mem_range'.mp hj2
          calc n * x + j2 < n * x + n := by omega
            _ = n * (x + 1) := by rw [Nat.mul_succ]
            _ ≤ n * 256 := Nat.mul_le_mul_left n (by omega)
            _ = 8 * (32 * n) := by ring)⟩))
      (fun cnt2 (st : MProd ℕ (Vector Bool (8 * (32 * n)))) =>
        st.fst = r[x].val / 2 ^ cnt2 ∧
        st.snd[m]'hm_lt = if (x = m / n ∧ m % n < cnt2)
          then (r[m / n]'hi0).val.testBit (m % n) else b[m]'hm_lt)
      n (by simp) ?inInit ?inStep).2
    case inInit =>
      exact ⟨by rw [pow_zero, Nat.div_one], by simp only [Nat.not_lt_zero, and_false, if_false]⟩
    case inStep =>
      intro c2 hc2 st hst j2 hj2 hj2eq
      have hj2_val : j2 = c2 := by rw [hj2eq]; simp [List.getElem_range']
      have hc2_lt : c2 < n := by simpa using hc2
      obtain ⟨hst1, hst2⟩ := hst
      refine ⟨_, rfl, ?_, ?_⟩
      · rw [hst1, pow_succ, Nat.div_div_eq_div_mul]
      · rw [vget_set _ (n * x + j2) _ (by
          calc n * x + j2 < n * x + n := by omega
            _ = n * (x + 1) := by rw [Nat.mul_succ]
            _ ≤ n * 256 := Nat.mul_le_mul_left n (by omega)
            _ = 8 * (32 * n) := by ring) m hm_lt]
        by_cases hmeq : m = n * x + j2
        · have hmc : m = n * x + c2 := by rw [hmeq, hj2_val]
          have hd : m / n = x := by
            rw [hmc, Nat.mul_add_div hn, Nat.div_eq_of_lt hc2_lt, Nat.add_zero]
          have hmod : m % n = c2 := by rw [hmc, Nat.mul_add_mod, Nat.mod_eq_of_lt hc2_lt]
          rw [if_pos hmeq, hst1, ofNat_div_mod_eq_testBit, if_pos ⟨hd.symm, by omega⟩]
          simp only [hd, hmod]
        · rw [if_neg hmeq, hst2]
          by_cases hxc : x = m / n
          · have hne : m % n ≠ c2 := by
              intro h
              apply hmeq
              have hmm : m = n * x + c2 := by
                conv_lhs => rw [← Nat.div_add_mod m n]
                rw [← hxc, h]
              rw [hmm, hj2_val]
            split_ifs with h1 h2 <;> first | rfl | (exfalso; omega)
          · simp only [hxc, false_and, if_false]

/-- Spec-side byte value: byte `p` of `serialize n r` is byte `p` of the packed bit-stream
`∑ᵢ r[i].val · 2^(n·i)`. -/
theorem serialize_byteVal (n : ℕ) (r : Spec.Kopis.Polynomial (2 ^ n)) (p : ℕ)
    (hp : p < 32 * n) (hn : 0 < n) :
    ((Spec.Kopis.serialize n r)[p]'hp).toNat
      = (∑ i ∈ Finset.range 256, (r[i]!).val * 2 ^ (n * i)) / 256 ^ p % 256 := by
  haveI : NeZero (2 ^ n) := ⟨by positivity⟩
  apply byte_eq
  · exact ((Spec.Kopis.serialize n r)[p]'hp).isLt
  · exact Nat.mod_lt _ (by norm_num)
  · intro j hj
    rw [serialize_byte_bit n r p j hp hj hn, byte_testBit _ p j hj]
    set q := (8 * p + j) / n with hqdef
    set s := (8 * p + j) % n with hsdef
    have hq_lt : q < 256 := by rw [hqdef, Nat.div_lt_iff_lt_mul hn]; omega
    have hs_lt : s < n := by rw [hsdef]; exact Nat.mod_lt _ hn
    have hqs : n * q + s = 8 * p + j := by rw [hqdef, hsdef]; exact Nat.div_add_mod _ _
    have hpk := packed_testBit (fun i => (r[i]!).val) n 256
      (fun i => by simpa using ZMod.val_lt (r[i]!)) q s hs_lt hq_lt
    rw [hqs] at hpk
    rw [hpk]
    exact (congrArg (fun z => z.val.testBit s) (getElem!_pos r q hq_lt)).symm
