-- AUTOGENERATED from Kopis/Properties/Serialize10.lean by `make generated`.  Do not edit.
-- See NEON_VERIFICATION_PLAN.md phase E: the serial proof, with the extracted
-- constants and this stack's namespace renamed, and nothing else changed.
/-
  # Kopis/Properties/Serialize10.lean — the branchless 10-bit serializer.

  `RingElem::serialize` dispatches to `ser::serialize_10` when `bits_per_elem` is
  `MODULUS_P_BITS`, which is the hot width (public-key and ciphertext vectors).  That
  fast path packs four coefficients into five bytes with fixed shifts instead of running
  the generic sliding-window serializer.

  It is proved here against exactly the same postcondition the generic path gets from
  `ser_serialize_spec`, namely `byteVal r 320 = packedVal data 10 256`, so
  `ring_serialize_spec` can dispatch without its callers noticing.  That mirrors the
  Rust test `specialized_ser_matches_generic`.

  The arithmetic core is `group_bytes`: the five bytes written for group `g` are the
  base-256 digits of `d₀ + d₁·2¹⁰ + d₂·2²⁰ + d₃·2³⁰`, the four 10-bit coefficients of
  that group packed little-endian.
-/
import Kopis.Bits.Stream
import Kopis.Neon.Properties.SerializeEnc2
open Aeneas Aeneas.Std Result RustKopisNeon
open Spec (𝔹)
open scoped BigOperators

namespace Kopis.Neon.Properties

open Kopis.Properties (streamBit streamNat streamNat_zero streamNat_succ streamBit_le_one streamNat_lt streamNat_split lor_add_of_lt lor_mul_of_lt sum_testBit_eq_mod streamNat_byte streamByte streamByte_lt sum_base256 testBit_sum_bytes streamNat_of_byteWindow cbdX cbdX_le testBit_streamNat cbdX_eq_bitSum streamNat_mod streamNat_shiftRight cbdX_eq_bitSum_of_le cbdU16)

set_option maxHeartbeats 1000000

/-! ## The packed value of one 4-coefficient group -/

/-- The little-endian packing of four 10-bit values. -/
def groupVal (d0 d1 d2 d3 : ℕ) : ℕ := d0 + d1 * 2 ^ 10 + d2 * 2 ^ 20 + d3 * 2 ^ 30

theorem groupVal_lt {d0 d1 d2 d3 : ℕ} (h0 : d0 < 2 ^ 10) (h1 : d1 < 2 ^ 10)
    (h2 : d2 < 2 ^ 10) (h3 : d3 < 2 ^ 10) : groupVal d0 d1 d2 d3 < 2 ^ 40 := by
  unfold groupVal; omega

/-- Byte 0 of the group: the low 8 bits of `d₀`. -/
theorem groupVal_byte0 {d0 d1 d2 d3 : ℕ} :
    groupVal d0 d1 d2 d3 % 256 = d0 % 256 := by
  unfold groupVal
  omega

/-- Byte 1: `d₀ >>> 8` in the low 2 bits, `d₁` in the top 6. -/
theorem groupVal_byte1 {d0 d1 d2 d3 : ℕ} (_h0 : d0 < 2 ^ 10) :
    groupVal d0 d1 d2 d3 / 256 % 256 = (d0 / 256 + d1 * 4) % 256 := by
  unfold groupVal
  rw [show d0 + d1 * 2 ^ 10 + d2 * 2 ^ 20 + d3 * 2 ^ 30
        = d0 % 256 + 256 * (d0 / 256 + d1 * 4 + d2 * 2 ^ 12 + d3 * 2 ^ 22) from by omega,
    Nat.add_mul_div_left _ _ (by norm_num), Nat.div_eq_of_lt (by omega), Nat.zero_add]
  omega

/-- Byte 2: `d₁ >>> 6` in the low 4 bits, `d₂` in the top 4. -/
theorem groupVal_byte2 {d0 d1 d2 d3 : ℕ} (h0 : d0 < 2 ^ 10) (_h1 : d1 < 2 ^ 10) :
    groupVal d0 d1 d2 d3 / 256 ^ 2 % 256 = (d1 / 64 + d2 * 16) % 256 := by
  unfold groupVal
  rw [show d0 + d1 * 2 ^ 10 + d2 * 2 ^ 20 + d3 * 2 ^ 30
        = (d0 + d1 % 64 * 2 ^ 10)
          + 256 ^ 2 * (d1 / 64 + d2 * 16 + d3 * 2 ^ 14) from by
      rw [show (256 : ℕ) ^ 2 = 65536 from by norm_num]; omega,
    Nat.add_mul_div_left _ _ (by norm_num), Nat.div_eq_of_lt (by
      rw [show (256 : ℕ) ^ 2 = 65536 from by norm_num]; omega), Nat.zero_add]
  omega

/-- Byte 3: `d₂ >>> 4` in the low 6 bits, `d₃` in the top 2. -/
theorem groupVal_byte3 {d0 d1 d2 d3 : ℕ} (h0 : d0 < 2 ^ 10) (h1 : d1 < 2 ^ 10)
    (_h2 : d2 < 2 ^ 10) :
    groupVal d0 d1 d2 d3 / 256 ^ 3 % 256 = (d2 / 16 + d3 * 64) % 256 := by
  unfold groupVal
  rw [show d0 + d1 * 2 ^ 10 + d2 * 2 ^ 20 + d3 * 2 ^ 30
        = (d0 + d1 * 2 ^ 10 + d2 % 16 * 2 ^ 20)
          + 256 ^ 3 * (d2 / 16 + d3 * 64) from by
      rw [show (256 : ℕ) ^ 3 = 16777216 from by norm_num]; omega,
    Nat.add_mul_div_left _ _ (by norm_num), Nat.div_eq_of_lt (by
      rw [show (256 : ℕ) ^ 3 = 16777216 from by norm_num]; omega), Nat.zero_add]

/-- Byte 4: the top 8 bits of `d₃`. -/
theorem groupVal_byte4 {d0 d1 d2 d3 : ℕ} (h0 : d0 < 2 ^ 10) (h1 : d1 < 2 ^ 10)
    (h2 : d2 < 2 ^ 10) (h3 : d3 < 2 ^ 10) :
    groupVal d0 d1 d2 d3 / 256 ^ 4 % 256 = d3 / 4 := by
  unfold groupVal
  rw [show d0 + d1 * 2 ^ 10 + d2 * 2 ^ 20 + d3 * 2 ^ 30
        = (d0 + d1 * 2 ^ 10 + d2 * 2 ^ 20 + d3 % 4 * 2 ^ 30)
          + 256 ^ 4 * (d3 / 4) from by
      rw [show (256 : ℕ) ^ 4 = 4294967296 from by norm_num]; omega,
    Nat.add_mul_div_left _ _ (by norm_num), Nat.div_eq_of_lt (by
      rw [show (256 : ℕ) ^ 4 = 4294967296 from by norm_num]; omega), Nat.zero_add,
    Nat.mod_eq_of_lt (by omega)]


/-! ## The extracted loop -/

/-- The `|k| data[o+k] & 0x3ff` closure reads a coefficient masked to 10 bits. -/
theorem serialize_10_closure_spec (data : Array U16 256#usize) (o k : Usize)
    (hlt : o.val + k.val < 256) :
    ser.serialize_10.closure.Insts.CoreOpsFunctionFnTupleUsizeU16.call (data, o) k
      ⦃ (r : U16) => r.val = (data.val[o.val + k.val]!).val % 2 ^ 10 ⦄ := by
  unfold ser.serialize_10.closure.Insts.CoreOpsFunctionFnTupleUsizeU16.call
  let* ⟨ i1, hi1 ⟩ ← Std.Usize.add_spec (x := o) (y := k) (by scalar_tac)
  have hdlen : data.val.length = 256 := data.property
  have hi1lt : i1.val < data.val.length := by rw [hi1, hdlen]; omega
  let* ⟨ i2, hi2 ⟩ ← Array.index_usize_spec
  have : (i2 &&& 1023#u16).val = i2.val % 2 ^ 10 := by
    rw [UScalar.val_and, show (1023#u16).val = 2 ^ 10 - 1 from rfl,
      Nat.and_two_pow_sub_one_eq_mod]
  rw [this, hi2, ← getElem!_pos data.val i1.val hi1lt, hi1]

/-- **`serialize_10_loop` invariant.**  After the groups `[0, iter.start)`, the first
`5·iter.start` output bytes are the base-256 digits of the first `4·iter.start` packed
coefficients. -/
theorem serialize_10_loop_spec (iter : core.ops.range.Range Usize)
    (data : Array U16 256#usize) (out_buf : Array U8 320#usize)
    (hend : iter.«end».val = 64) (hstart : iter.start.val ≤ 64)
    (hinv : byteVal (Array.to_slice out_buf) (5 * iter.start.val)
      = packedVal (Array.to_slice data) 10 (4 * iter.start.val)) :
    ser.serialize_10_loop iter data out_buf
      ⦃ (r : Array U8 320#usize) =>
          byteVal (Array.to_slice r) 320 = packedVal (Array.to_slice data) 10 256 ⦄ := by
  unfold ser.serialize_10_loop
  have hob_len : out_buf.val.length = 320 := out_buf.property
  by_cases hlt : iter.start.val < iter.«end».val
  · let* ⟨ g, iter1, ho, hstart', hend' ⟩ ← core.iter.range.IteratorRange.next_Usize_some_spec
    rw [ho]; simp only
    have hg : iter.start.val < 64 := by omega
    let* ⟨ o1, ho1 ⟩ ← Std.Usize.mul_spec (x := 4#usize) (y := iter.start) (by scalar_tac)
    have ho1v : o1.val = 4 * iter.start.val := by rw [ho1]
    let* ⟨ b, hb ⟩ ← Std.Usize.mul_spec (x := 5#usize) (y := iter.start) (by scalar_tac)
    have hbv : b.val = 5 * iter.start.val := by rw [hb]
    have hd : ∀ t : ℕ, t < 4 → o1.val + t < 256 := by intro t ht; rw [ho1v]; omega
    have h16 : U16.size = 2 ^ 16 := by simp [Std.U16.size, Std.U16.numBits]
    -- d0 and byte 0
    let* ⟨ c0, hc0 ⟩ ← serialize_10_closure_spec data o1 0#usize (by
      have := hd 0 (by norm_num); simpa using this)
    have hc0v : c0.val = (data.val[4 * iter.start.val]!).val % 2 ^ 10 := by
      rw [hc0, show o1.val + 0 = 4 * iter.start.val from by rw [ho1v]; omega]
    have hc0lt : c0.val < 2 ^ 10 := by rw [hc0v]; exact Nat.mod_lt _ (by norm_num)
    rw [show lift (UScalar.cast (src_ty := .U16) .U8 c0)
        = ok (UScalar.cast (src_ty := .U16) .U8 c0) from rfl, bind_tc_ok]
    let* ⟨ ob1, hob1 ⟩ ← Array.update_spec
    -- d1 and byte 1
    let* ⟨ s0, hs0, hs0bv ⟩ ← Std.U16.ShiftRight_IScalar_spec c0 8#i32 (by decide) (by decide)
    let* ⟨ c1, hc1 ⟩ ← serialize_10_closure_spec data o1 1#usize (by
      have := hd 1 (by norm_num); simpa using this)
    have hc1v : c1.val = (data.val[4 * iter.start.val + 1]!).val % 2 ^ 10 := by
      rw [hc1, show o1.val + 1 = 4 * iter.start.val + 1 from by rw [ho1v]]
    have hc1lt : c1.val < 2 ^ 10 := by rw [hc1v]; exact Nat.mod_lt _ (by norm_num)
    let* ⟨ sl1, hsl1, hsl1bv ⟩ ← Std.U16.ShiftLeft_IScalar_spec c1 2#i32 (by decide) (by decide)
    have hsl1v : sl1.val = c1.val * 4 := by
      rw [hsl1, Nat.shiftLeft_eq, Nat.mod_eq_of_lt (show c1.val * 2 ^ 2 < U16.size from by
        rw [h16]; omega)]
      ring
    rw [show lift (s0 ||| sl1) = ok (s0 ||| sl1) from rfl, bind_tc_ok]
    have hor1 : (s0 ||| sl1).val = c0.val / 256 + c1.val * 4 := by
      rw [UScalar.val_or, hs0, hsl1v, show c1.val * 4 = c1.val * 2 ^ 2 from by ring,
        lor_mul_of_lt (show c0.val >>> 8 < 2 ^ 2 from by
          rw [Nat.shiftRight_eq_div_pow]; omega), Nat.shiftRight_eq_div_pow]
    let* ⟨ i6, hi6 ⟩ ← Std.Usize.add_spec (x := b) (y := 1#usize) (by scalar_tac)
    rw [show lift (UScalar.cast (src_ty := .U16) .U8 (s0 ||| sl1))
        = ok (UScalar.cast (src_ty := .U16) .U8 (s0 ||| sl1)) from rfl, bind_tc_ok]
    let* ⟨ ob2, hob2 ⟩ ← Array.update_spec
    -- d2 and byte 2
    let* ⟨ s1, hs1, hs1bv ⟩ ← Std.U16.ShiftRight_IScalar_spec c1 6#i32 (by decide) (by decide)
    let* ⟨ c2, hc2 ⟩ ← serialize_10_closure_spec data o1 2#usize (by
      have := hd 2 (by norm_num); simpa using this)
    have hc2v : c2.val = (data.val[4 * iter.start.val + 2]!).val % 2 ^ 10 := by
      rw [hc2, show o1.val + 2 = 4 * iter.start.val + 2 from by rw [ho1v]]
    have hc2lt : c2.val < 2 ^ 10 := by rw [hc2v]; exact Nat.mod_lt _ (by norm_num)
    let* ⟨ sl2, hsl2, hsl2bv ⟩ ← Std.U16.ShiftLeft_IScalar_spec c2 4#i32 (by decide) (by decide)
    have hsl2v : sl2.val = c2.val * 16 := by
      rw [hsl2, Nat.shiftLeft_eq, Nat.mod_eq_of_lt (show c2.val * 2 ^ 4 < U16.size from by
        rw [h16]; omega)]
      ring
    rw [show lift (s1 ||| sl2) = ok (s1 ||| sl2) from rfl, bind_tc_ok]
    have hor2 : (s1 ||| sl2).val = c1.val / 64 + c2.val * 16 := by
      rw [UScalar.val_or, hs1, hsl2v, show c2.val * 16 = c2.val * 2 ^ 4 from by ring,
        lor_mul_of_lt (show c1.val >>> 6 < 2 ^ 4 from by
          rw [Nat.shiftRight_eq_div_pow]; omega), Nat.shiftRight_eq_div_pow]
    let* ⟨ i12, hi12 ⟩ ← Std.Usize.add_spec (x := b) (y := 2#usize) (by scalar_tac)
    rw [show lift (UScalar.cast (src_ty := .U16) .U8 (s1 ||| sl2))
        = ok (UScalar.cast (src_ty := .U16) .U8 (s1 ||| sl2)) from rfl, bind_tc_ok]
    let* ⟨ ob3, hob3 ⟩ ← Array.update_spec
    -- d3 and bytes 3, 4
    let* ⟨ s2, hs2, hs2bv ⟩ ← Std.U16.ShiftRight_IScalar_spec c2 4#i32 (by decide) (by decide)
    let* ⟨ c3, hc3 ⟩ ← serialize_10_closure_spec data o1 3#usize (by
      have := hd 3 (by norm_num); simpa using this)
    have hc3v : c3.val = (data.val[4 * iter.start.val + 3]!).val % 2 ^ 10 := by
      rw [hc3, show o1.val + 3 = 4 * iter.start.val + 3 from by rw [ho1v]]
    have hc3lt : c3.val < 2 ^ 10 := by rw [hc3v]; exact Nat.mod_lt _ (by norm_num)
    let* ⟨ sl3, hsl3, hsl3bv ⟩ ← Std.U16.ShiftLeft_IScalar_spec c3 6#i32 (by decide) (by decide)
    have hsl3v : sl3.val = c3.val * 64 := by
      rw [hsl3, Nat.shiftLeft_eq, Nat.mod_eq_of_lt (show c3.val * 2 ^ 6 < U16.size from by
        rw [h16]; omega)]
      ring
    rw [show lift (s2 ||| sl3) = ok (s2 ||| sl3) from rfl, bind_tc_ok]
    have hor3 : (s2 ||| sl3).val = c2.val / 16 + c3.val * 64 := by
      rw [UScalar.val_or, hs2, hsl3v, show c3.val * 64 = c3.val * 2 ^ 6 from by ring,
        lor_mul_of_lt (show c2.val >>> 4 < 2 ^ 6 from by
          rw [Nat.shiftRight_eq_div_pow]; omega), Nat.shiftRight_eq_div_pow]
    let* ⟨ i18, hi18 ⟩ ← Std.Usize.add_spec (x := b) (y := 3#usize) (by scalar_tac)
    rw [show lift (UScalar.cast (src_ty := .U16) .U8 (s2 ||| sl3))
        = ok (UScalar.cast (src_ty := .U16) .U8 (s2 ||| sl3)) from rfl, bind_tc_ok]
    let* ⟨ ob4, hob4 ⟩ ← Array.update_spec
    let* ⟨ s3, hs3, hs3bv ⟩ ← Std.U16.ShiftRight_IScalar_spec c3 2#i32 (by decide) (by decide)
    let* ⟨ i21, hi21 ⟩ ← Std.Usize.add_spec (x := b) (y := 4#usize) (by scalar_tac)
    rw [show lift (UScalar.cast (src_ty := .U16) .U8 s3)
        = ok (UScalar.cast (src_ty := .U16) .U8 s3) from rfl, bind_tc_ok]
    let* ⟨ a, ha ⟩ ← Array.update_spec
    -- the five bytes written for this group
    have hu8 : ∀ x : U16, (UScalar.cast (src_ty := .U16) .U8 x).val = x.val % 256 := by
      intro x; rw [UScalar.cast_val_eq]; rfl
    set V := groupVal c0.val c1.val c2.val c3.val with hV
    have hVlt : V < 2 ^ 40 := groupVal_lt hc0lt hc1lt hc2lt hc3lt
    have hav : a.val = ((((out_buf.val.set b.val (UScalar.cast .U8 c0)).set (b.val + 1)
          (UScalar.cast .U8 (s0 ||| sl1))).set (b.val + 2)
          (UScalar.cast .U8 (s1 ||| sl2))).set (b.val + 3)
          (UScalar.cast .U8 (s2 ||| sl3))).set (b.val + 4) (UScalar.cast .U8 s3) := by
      rw [ha, Array.set_val_eq, hi21, hob4, Array.set_val_eq, hi18, hob3, Array.set_val_eq, hi12,
        hob2, Array.set_val_eq, hi6, hob1, Array.set_val_eq]
    have hlen_a : a.val.length = 320 := by
      rw [hav]; simp only [List.length_set]; exact hob_len
    -- byte q of the group is digit q of V
    have hgb : ∀ q, q < 5 → (a.val[5 * iter.start.val + q]!).val = V / 256 ^ q % 256 := by
      intro q hq
      rw [hav, hbv,
        getElem!_pos _ _ (by simp only [List.length_set]; rw [hob_len]; omega)]
      simp only [List.getElem_set]
      have hq5 : q = 0 ∨ q = 1 ∨ q = 2 ∨ q = 3 ∨ q = 4 := by omega
      rcases hq5 with rfl | rfl | rfl | rfl | rfl
      · rw [if_neg (by omega), if_neg (by omega), if_neg (by omega), if_neg (by omega),
          if_pos (by omega), hu8, hV, pow_zero, Nat.div_one, groupVal_byte0]
      · rw [if_neg (by omega), if_neg (by omega), if_neg (by omega), if_pos (by omega),
          hu8, hor1, hV, pow_one, groupVal_byte1 hc0lt]
      · rw [if_neg (by omega), if_neg (by omega), if_pos (by omega), hu8, hor2, hV,
          groupVal_byte2 hc0lt hc1lt]
      · rw [if_neg (by omega), if_pos (by omega), hu8, hor3, hV,
          groupVal_byte3 hc0lt hc1lt hc2lt]
      · rw [if_pos (by omega), hu8, hs3, Nat.shiftRight_eq_div_pow, hV,
          groupVal_byte4 hc0lt hc1lt hc2lt hc3lt, Nat.mod_eq_of_lt (by omega)]
    -- the prefix below 5g is untouched
    have hpref : byteVal (Array.to_slice a) (5 * iter.start.val)
        = byteVal (Array.to_slice out_buf) (5 * iter.start.val) := by
      refine byteVal_congr _ _ _ (fun q hq => ?_)
      rw [Array.val_to_slice, Array.val_to_slice, hav, hbv]
      rw [getElem!_pos _ _ (by simp only [List.length_set]; rw [hob_len]; omega),
        getElem!_pos _ _ (by rw [hob_len]; omega)]
      simp only [List.getElem_set]
      rw [if_neg (by omega), if_neg (by omega), if_neg (by omega), if_neg (by omega),
        if_neg (by omega)]
    -- accumulate
    apply WP.spec_mono (serialize_10_loop_spec iter1 data a (by rw [hend']; exact hend)
      (by rw [hstart']; omega) ?inv)
    case inv =>
      rw [hstart', show 5 * (iter.start.val + 1) = 5 * iter.start.val + 5 from by ring,
        byteVal_split _ (5 * iter.start.val) _ (by omega), hpref, hinv,
        show 4 * (iter.start.val + 1) = 4 * iter.start.val + 1 + 1 + 1 + 1 from by ring,
        packedVal_succ, packedVal_succ, packedVal_succ, packedVal_succ]
      have hsum : (∑ q ∈ Finset.range (5 * iter.start.val + 5 - 5 * iter.start.val),
          ((Array.to_slice a).val[5 * iter.start.val + q]!).val * 256 ^ q) = V := by
        rw [show 5 * iter.start.val + 5 - 5 * iter.start.val = 5 from by omega]
        simp only [Array.val_to_slice]
        rw [Finset.sum_range_succ, Finset.sum_range_succ, Finset.sum_range_succ,
          Finset.sum_range_succ, Finset.sum_range_one,
          hgb 0 (by norm_num), hgb 1 (by norm_num), hgb 2 (by norm_num),
          hgb 3 (by norm_num), hgb 4 (by norm_num)]
        norm_num
        omega
      rw [hsum]
      simp only [Array.val_to_slice]
      rw [← hc0v, ← hc1v, ← hc2v, ← hc3v, hV]
      unfold groupVal
      rw [show (256 : ℕ) ^ (5 * iter.start.val) = 2 ^ (40 * iter.start.val) from by
          rw [show (256 : ℕ) = 2 ^ 8 from by norm_num, ← pow_mul]; ring_nf,
        show 10 * (4 * iter.start.val) = 40 * iter.start.val from by ring,
        show 10 * (4 * iter.start.val + 1) = 40 * iter.start.val + 10 from by ring,
        show 10 * (4 * iter.start.val + 1 + 1) = 40 * iter.start.val + 20 from by ring,
        show 10 * (4 * iter.start.val + 1 + 1 + 1) = 40 * iter.start.val + 30 from by ring,
        pow_add, pow_add, pow_add]
      ring
    intro r hr; exact hr
  · let* ⟨ o, iter1, ho, hiter1 ⟩ ← core.iter.range.IteratorRange.next_Usize_none_spec
    rw [ho]; simp only
    have : iter.start.val = 64 := by omega
    rw [this] at hinv
    simpa using hinv
  termination_by iter.«end».val - iter.start.val
  decreasing_by scalar_decr_tac


/-- **`ser::serialize_10` matches the generic serializer's postcondition.**  The whole
320-byte output is the base-256 representation of the 256 coefficients packed 10 bits
each — exactly what `ser_serialize_spec` establishes for the generic path at `n = 10`. -/
theorem serialize_10_spec (data : Array U16 256#usize) (out_buf : Array U8 320#usize) :
    ser.serialize_10 data out_buf
      ⦃ (r : Array U8 320#usize) =>
          byteVal (Array.to_slice r) 320 = packedVal (Array.to_slice data) 10 256 ⦄ := by
  unfold ser.serialize_10
  exact serialize_10_loop_spec _ data out_buf rfl (by simp)
    (by simp [byteVal, packedVal])

end Kopis.Neon.Properties
