-- AUTOGENERATED from Kopis/Properties/SubtleModel.lean by `make generated`.  Do not edit.
-- See NEON_VERIFICATION_PLAN.md phase E: the serial proof, with the extracted
-- constants and this stack's namespace renamed, and nothing else changed.
import Kopis.Bits.Stream
import Kopis.Neon.Properties.Serialize
open Aeneas Aeneas.Std Result RustKopisNeon
open Spec (𝔹)
namespace Kopis.Neon.Properties

open Kopis.Properties (streamBit streamNat streamNat_zero streamNat_succ streamBit_le_one streamNat_lt streamNat_split lor_add_of_lt lor_mul_of_lt sum_testBit_eq_mod streamNat_byte streamByte streamByte_lt sum_base256 testBit_sum_bytes streamNat_of_byteWindow cbdX cbdX_le testBit_streamNat cbdX_eq_bitSum streamNat_mod streamNat_shiftRight cbdX_eq_bitSum_of_le cbdU16)

/-! ## Constant-time primitive model (`subtle` crate trust boundary)

The `subtle` crate's `ConstantTimeEq`/`ConditionallySelectable` are external and
Aeneas-axiomatised as opaque.  We model their *functional* behaviour (ignoring the
constant-time guarantee, which is a side-channel property invisible to the value spec):
`ct_eq a b` yields a `Choice` set exactly when `a = b`, and `conditional_select a b c`
returns `b` when the choice is set, `a` otherwise. -/

/-- The boolean a `subtle.Choice` stands for. -/
opaque choiceModel : subtle.Choice → Bool

/-- `ct_eq` on `U8` slices: the resulting `Choice` is set iff the slices are equal. -/
@[step] axiom ct_eq_slice_u8_spec (a b : Slice U8) :
    Slice.Insts.SubtleConstantTimeEq.ct_eq U8.Insts.SubtleConstantTimeEq a b
      ⦃ (c : subtle.Choice) => choiceModel c = decide (a.val = b.val) ⦄

/-- `conditional_select a b c` on `U8` arrays returns `b` if `c` is set, else `a`. -/
@[step] axiom conditional_select_array_u8_spec {N : Usize} (a b : Array U8 N) (ch : subtle.Choice) :
    Array.Insts.SubtleConditionallySelectable.conditional_select
        U8.Insts.SubtleConditionallySelectable a b ch
      ⦃ (r : Array U8 N) => r = if choiceModel ch = true then b else a ⦄

/-- `·.bv : U8 → BitVec 8` is injective (a `UScalar` is determined by its bit-vector). -/
theorem u8_bv_injective : Function.Injective (fun (x : U8) => x.bv) := by
  intro x y h
  apply UScalar.eq_of_val_eq
  have h2 := congrArg BitVec.toNat h
  rwa [U8.bv_toNat, U8.bv_toNat] at h2

/-- `sliceToBytes` is injective on equal-length `U8` slices: two byte-vectors coincide iff
the underlying `U8` slices do. -/
theorem sliceToBytes_inj (a b : Slice U8) (n : ℕ) (ha : a.length = n) (hb : b.length = n) :
    sliceToBytes a n ha = sliceToBytes b n hb ↔ a.val = b.val := by
  constructor
  · intro h
    have h2 := congrArg Vector.toList h
    rw [sliceToBytes_toList, sliceToBytes_toList] at h2
    exact List.map_injective_iff.mpr u8_bv_injective h2
  · intro h
    apply Vector.toList_inj.mp
    rw [sliceToBytes_toList, sliceToBytes_toList, h]

end Kopis.Neon.Properties
