-- Kopis KEM: Aeneas-extracted Rust code + correspondence proofs.
-- Build with `lake build Kopis`.
import ExtractedRust
import Kopis.Properties.RingArith
import Kopis.Properties.Serialize
import Kopis.Properties.GenMatrix
import Kopis.Properties.MatrixArith
import Kopis.Properties.MulTranspose
import Kopis.Properties.Ntt
import Kopis.Properties.NttReduce
import Kopis.Properties.NttForward
import Kopis.Properties.NttMul
import Kopis.Properties.NttBridge
import Kopis.Properties.NttInverse
import Kopis.Properties.GenSecretLoops
import Kopis.Properties.GenSecretSpec
import Kopis.Properties.GenSecretTop
import Kopis.Properties.SerializeEnc
import Kopis.Properties.SerializeEnc2
import Kopis.Properties.SerializeSpec
import Kopis.Properties.SerializeSpec2
import Kopis.Properties.SerializeTop
import Kopis.Properties.RoundBridge
import Kopis.Properties.CoerceBridge
import Kopis.Properties.MatrixSerialize
import Kopis.Properties.MatVecMul
import Kopis.Properties.ProdBridge
import Kopis.Properties.RoundTop
import Kopis.Properties.PkeSerialize
import Kopis.Properties.PkeHash
import Kopis.Properties.ExpandDecap
import Kopis.Properties.MatrixMul
import Kopis.Properties.CoerceBridge10
import Kopis.Properties.InnerProduct
import Kopis.Properties.RoundRt
import Kopis.Properties.ProdBridgeNT
import Kopis.Properties.EncryptGlue
import Kopis.Properties.DeserializeMsg
import Kopis.Properties.PkeEncryptTop
import Kopis.Properties.RoundR1
import Kopis.Properties.DecryptGlue
import Kopis.Properties.DeserializeVec
import Kopis.Properties.DeserializeCm
import Kopis.Properties.PkeDecryptTop
import Kopis.Properties.KemEncap
import Kopis.Properties.Hash
import Kopis.Properties.SubtleModel
import Kopis.Properties.KemDecap
import Kopis.Properties.Impls
import Kopis.Properties.EncodeRoundtrip
import Kopis.Properties.KeyGen
import Kopis.Properties.KeyGenHyps
import Kopis.Properties.KeyGenCapstone
import Kopis.Properties.PkeFromBytes
import Kopis.Properties.SerializeRoundtrip
import Kopis.Properties.KemFromBytes
