import Lake
open Lake DSL

-- We use the aeneas library version given by AENEAS_VERSION.txt in the root of this crate
def aeneasRev : String := (include_str "../AENEAS_VERSION.txt").trimAscii.toString
require aeneas from git "https://github.com/AeneasVerif/aeneas.git"
  @ aeneasRev / "backends/lean"

package «kopis»

-- Aeneas-extracted Rust code with the `serial` backend. Generated by `../extract_rust_to_lean.sh`.
lean_lib «ExtractedRustSerial» where
  -- This is all auto-generated, so disable style linting warnings
  leanOptions := #[⟨`linter.style.nameCheck, false⟩]

-- Aeneas-extracted Rust code with the `avx2` backend. Generated by `../extract_rust_to_lean.sh`.
lean_lib «ExtractedRustAvx2» where
  -- This is all auto-generated, so disable style linting warnings
  leanOptions := #[⟨`linter.style.nameCheck, false⟩]

-- Aeneas-extracted Rust code with the `neon` backend. Generated by `../extract_rust_to_lean.sh`.
lean_lib «ExtractedRustNeon» where
  -- This is all auto-generated, so disable style linting warnings
  leanOptions := #[⟨`linter.style.nameCheck, false⟩]

lean_lib «KopisAvx2» where
  roots := #[`Kopis.Avx2]
lean_lib «KopisNeon» where
  roots := #[`Kopis.Neon]

/- `Kopis/Avx2/Properties/*.lean` is a renaming of `Kopis/Properties/*.lean`, autogenerated by
`scripts/gen_avx2_twins.py`. It is a separate library from `KopisAvx2` so that its compilation
status doesn't affect the rest of the build. -/
lean_lib «KopisAvx2Properties» where
  roots := #[`Kopis.Avx2.Properties]
  globs := #[.andSubmodules `Kopis.Avx2.Properties]

/-- The same, for NEON: `Kopis/Neon/Properties/*.lean` from `scripts/gen_neon_twins.py`. -/
lean_lib «KopisNeonProperties» where
  roots := #[`Kopis.Neon.Properties]
  globs := #[.andSubmodules `Kopis.Neon.Properties]

-- Contains the Kopis, TurboSHAKE, and SHA-3 specs
lean_lib «Spec»

-- Library with Rust serial impl as well as all theorems about it
@[default_target]
lean_lib «Kopis»

-- Contains all the main theorems we prove about our Rust impl with serial backend
@[default_target]
lean_lib «TopLevelTheoremsSerial»

-- Contains all the main theorems we prove about our Rust impl with AVX2 backend
lean_lib «TopLevelTheoremsAvx2»

-- Contains all the main theorems we prove about our Rust impl with NEON backend
lean_lib «TopLevelTheoremsNeon»

-- Contains all the axioms we need in our proofs
@[default_target]
lean_lib «TrustBase»

-- Library with all the known-answer tests for the Lean impls of Kopis and TurboSHAKE
lean_lib «SpecTests» where
  globs := #[.andSubmodules `SpecTests]

-- Runs all the known-answer tests for the Lean impls of Kopis and TurboSHAKE
lean_exe kopisTests where
  root := `SpecTests.Kopis.Run

-- Runs known-answer tests for AVX2 intrinsics
lean_exe avx2Tests where
  root := `SpecTests.Avx2.Run

-- Runs known-answer tests for NEON intrinsics
lean_exe neonTests where
  root := `SpecTests.Neon.Run
