-- AUTOGENERATED from TopLevelTheoremsSerial.lean by `make generated`.  Do not edit.
import Kopis.Neon.Properties

open Aeneas Aeneas.Std Result
open Spec (𝔹)

open Kopis.Neon
namespace Kopis.TopLevelNeon

set_option maxRecDepth 8000

/-- We introduce the `⦃ … ⦄` postcondition notation. Whenever we use this, it means the computation
succeeds (no panic or UB), and has the property defined by `p`. This theorem isn't strictly
necessary, but it demonstrates the notation. -/
theorem triple_means_success {α : Type} {x : Result α} {p : α → Prop} (h : x ⦃ p ⦄) :
    ∃ v, x = ok v ∧ p v :=
  Kopis.Neon.Properties.triple_means_success h

/-- Converts a Rust `[u8; n]` to a Lean bye array `𝔹 n` -/
def arrayToBytes {n : Usize} (a : Array U8 n) : 𝔹 (n : ℕ) :=
  Vector.ofFn fun (i : Fin (n : ℕ)) => (a.val[i.val]'(by have := a.property; grind)).bv

/-- The three parameter sets, as an index to quantify over. -/
inductive Size | k512 | k768 | k1024

namespace Size

/-- The Rust const generic `ℓ`: the module rank. -/
def L : Size → Usize | .k512 => 2#usize | .k768 => 3#usize | .k1024 => 4#usize
/-- The Rust const generic `μ`: the CBD parameter. -/
def MU : Size → Usize | .k512 => 10#usize | .k768 => 8#usize | .k1024 => 6#usize
/-- The spec's name for the same parameter set. -/
def ps : Size → Spec.Kopis.ParameterSet
  | .k512 => .Kopis_512 | .k768 => .Kopis_768 | .k1024 => .Kopis_1024
/-- Serialized public key, in bytes. -/
def pkLen : Size → Usize | .k512 => 672#usize | .k768 => 992#usize | .k1024 => 1312#usize
/-- Ciphertext, in bytes. -/
def ctLen : Size → Usize | .k512 => 736#usize | .k768 => 1088#usize | .k1024 => 1472#usize

/-- `KemSecretKey::public_key` at each size. -/
noncomputable def publicKey : (s : Size) →
    RustKopisNeon.kem.KemSecretKey s.L → Result (RustKopisNeon.kem.KemPublicKey s.L)
  | .k512 => RustKopisNeon.impls.kopis512.KemSecretKey2.public_key
  | .k768 => RustKopisNeon.impls.kopis768.KemSecretKey3.public_key
  | .k1024 => RustKopisNeon.impls.kopis1024.KemSecretKey4.public_key

/-- `KemPublicKey::from_bytes` at each size. -/
noncomputable def fromBytes : (s : Size) →
    Array U8 s.pkLen → Result (RustKopisNeon.kem.KemPublicKey s.L)
  | .k512 => RustKopisNeon.impls.kopis512.KemPublicKey2.from_bytes
  | .k768 => RustKopisNeon.impls.kopis768.KemPublicKey3.from_bytes
  | .k1024 => RustKopisNeon.impls.kopis1024.KemPublicKey4.from_bytes

/-- `KemPublicKey::to_bytes` at each size.  This is the serializer a caller reaches for; it
allocates its own buffer, where `PkePublicKey::serialize` writes into one it is handed. -/
noncomputable def toBytes : (s : Size) →
    RustKopisNeon.kem.KemPublicKey s.L → Result (Array U8 s.pkLen)
  | .k512 => RustKopisNeon.impls.kopis512.KemPublicKey2.to_bytes
  | .k768 => RustKopisNeon.impls.kopis768.KemPublicKey3.to_bytes
  | .k1024 => RustKopisNeon.impls.kopis1024.KemPublicKey4.to_bytes

/-- `KemPublicKey::encapsulate_deterministic` at each size. -/
noncomputable def encap : (s : Size) →
    RustKopisNeon.kem.KemPublicKey s.L → Array U8 32#usize →
      Result (Array U8 s.ctLen × RustKopisNeon.kem.SharedSecret)
  | .k512 => RustKopisNeon.impls.kopis512.KemPublicKey2.encapsulate_deterministic
  | .k768 => RustKopisNeon.impls.kopis768.KemPublicKey3.encapsulate_deterministic
  | .k1024 => RustKopisNeon.impls.kopis1024.KemPublicKey4.encapsulate_deterministic

/-- `KemSecretKey::decapsulate` at each size. -/
noncomputable def decap : (s : Size) →
    RustKopisNeon.kem.KemSecretKey s.L → Array U8 s.ctLen →
      Result RustKopisNeon.kem.SharedSecret
  | .k512 => RustKopisNeon.impls.kopis512.KemSecretKey2.decapsulate
  | .k768 => RustKopisNeon.impls.kopis768.KemSecretKey3.decapsulate
  | .k1024 => RustKopisNeon.impls.kopis1024.KemSecretKey4.decapsulate

-- The spec's sizes are the Rust ones
theorem pkSize (s : Size) : Spec.Kopis.pkSize s.ps = s.pkLen.val := by cases s <;> rfl
theorem ctSize (s : Size) : Spec.Kopis.ctSize s.ps = s.ctLen.val := by cases s <;> rfl

end Size

/-- keygen → pubkey → to_bytes matches the spec -/
theorem keygen_then_to_bytes : ∀ (s : Size) (seed : Array U8 32#usize),
    (do let ksk ← RustKopisNeon.kem.KemSecretKey.expand_from_seed s.L s.MU seed
        let kpk ← s.publicKey ksk
        s.toBytes kpk)
      ⦃ (r : Array U8 s.pkLen) =>
          (arrayToBytes r).toList
            = (Spec.Kopis.ExpandSecretKey s.ps (arrayToBytes seed)).2.2.1.toList ⦄
  | .k512, seed => Kopis.Neon.Properties.kopis512_keygen_to_bytes_spec seed
  | .k768, seed => Kopis.Neon.Properties.kopis768_keygen_to_bytes_spec seed
  | .k1024, seed => Kopis.Neon.Properties.kopis1024_keygen_to_bytes_spec seed

/-- keygen → pubkey → encapsulate matches the spec -/
theorem keygen_then_encapsulate : ∀ (s : Size) (seed randomness : Array U8 32#usize),
    (do let ksk ← RustKopisNeon.kem.KemSecretKey.expand_from_seed s.L s.MU seed
        let kpk ← s.publicKey ksk
        s.encap kpk randomness)
      ⦃ (ct : Array U8 s.ctLen) (ss : RustKopisNeon.kem.SharedSecret) =>
          let spec := Spec.Kopis.KemEncap s.ps (arrayToBytes randomness)
                        (Spec.Kopis.SkToPk s.ps (arrayToBytes seed))
          arrayToBytes ct = s.ctSize ▸ spec.2 ∧
          arrayToBytes ss = spec.1 ⦄
  | .k512, seed, randomness => Kopis.Neon.Properties.kopis512_keygen_encap_spec seed randomness
  | .k768, seed, randomness => Kopis.Neon.Properties.kopis768_keygen_encap_spec seed randomness
  | .k1024, seed, randomness => Kopis.Neon.Properties.kopis1024_keygen_encap_spec seed randomness

/-- from_bytes → encapsulate matches the spec -/
theorem from_bytes_then_encapsulate : ∀ (s : Size) (pk_bytes : Array U8 s.pkLen)
    (randomness : Array U8 32#usize),
    (do let kpk ← s.fromBytes pk_bytes
        s.encap kpk randomness)
      ⦃ (ct : Array U8 s.ctLen) (ss : RustKopisNeon.kem.SharedSecret) =>
          let spec := Spec.Kopis.KemEncap s.ps (arrayToBytes randomness)
                        (s.pkSize ▸ arrayToBytes pk_bytes)
          arrayToBytes ct = s.ctSize ▸ spec.2 ∧
          arrayToBytes ss = spec.1 ⦄
  | .k512, pk, r => Kopis.Neon.Properties.kopis512_from_bytes_encap_spec pk r
  | .k768, pk, r => Kopis.Neon.Properties.kopis768_from_bytes_encap_spec pk r
  | .k1024, pk, r => Kopis.Neon.Properties.kopis1024_from_bytes_encap_spec pk r

/-- from_bytes → to_bytes matches the spec -/
theorem from_bytes_then_to_bytes : ∀ (s : Size) (pk_bytes : Array U8 s.pkLen),
    (do let kpk ← s.fromBytes pk_bytes
        s.toBytes kpk)
      ⦃ (r : Array U8 s.pkLen) => arrayToBytes r = arrayToBytes pk_bytes ⦄
  | .k512, pk => Kopis.Neon.Properties.kopis512_from_bytes_to_bytes_spec pk
  | .k768, pk => Kopis.Neon.Properties.kopis768_from_bytes_to_bytes_spec pk
  | .k1024, pk => Kopis.Neon.Properties.kopis1024_from_bytes_to_bytes_spec pk

/-- keygen → decapsulate matches the spec -/
theorem keygen_then_decapsulate : ∀ (s : Size) (seed : Array U8 32#usize)
    (ek : Array U8 s.ctLen),
    (do let ksk ← RustKopisNeon.kem.KemSecretKey.expand_from_seed s.L s.MU seed
        s.decap ksk ek)
      ⦃ (r : RustKopisNeon.kem.SharedSecret) =>
          arrayToBytes r
            = Spec.Kopis.KemDecap s.ps (arrayToBytes seed)
                (s.ctSize ▸ arrayToBytes ek) ⦄
  | .k512, seed, ek => Kopis.Neon.Properties.kopis512_keygen_decap_spec seed ek
  | .k768, seed, ek => Kopis.Neon.Properties.kopis768_keygen_decap_spec seed ek
  | .k1024, seed, ek => Kopis.Neon.Properties.kopis1024_keygen_decap_spec seed ek

end Kopis.TopLevelNeon
