-- AUTOGENERATED from TopLevelTheoremsSerial.lean by `make generated`.  Do not edit.
import Kopis.Neon.Properties

/-!
# Top-level theorems — the audit surface for `kopis-rs`

This file exists to be **read by a human**. Everything else in `Kopis/Properties/`
is machinery; this is the summary you have to agree with in order to believe the
claim "the `kopis-rs` Rust crate is formally verified".

Nothing here is re-proved. Every theorem below is discharged by handing back the
theorem proved elsewhere in the library, so a restatement that drifted from what
was actually proved would fail to compile. Reading this file is therefore
equivalent to reading the real statements, without reading the proofs.

## The claim, in one sentence

For every input, the Rust implementation of key generation, encapsulation and
decapsulation **terminates without panicking** and returns exactly what the
audited specification in `Spec/Kopis/Spec.lean` says it should.

## Reading guide: which world does a name come from?

Nothing is `open`ed in this file except the Aeneas framework itself (`Array`, `Slice`,
`U8`, `Usize`, `Result`, the `⦃ … ⦄` notation), which belongs to none of the three
worlds below. Every other name therefore carries a prefix saying what it is:

| prefix | world | status |
| ------ | ----- | ------ |
| `RustKopisNeon.…` | the **extracted Rust** (`ExtractedRustNeon.lean`, from `../src/*.rs`) | trusted |
| `Spec.…` | the **audited specification** (`Spec/Kopis/Spec.lean`) | trusted |
| `Properties.…` | the **translation layer** (`Kopis/Properties/`) | proved — see §2 |

`RustKopisNeon.…` is trusted because the charon/aeneas extraction is; `Spec.…` because you have
read it against `kopis-spec.md` and `make test-kopis-spec` passes. `Properties.…` is
proved, but it is where a statement could be made vacuous, so §2 pins it down.

So `RustKopisNeon.kem.KemSecretKey.expand_from_seed` is Rust, `Spec.Kopis.ExpandDecapKey` is the
specification it is claimed to implement, and `Properties.arrayToBytes` is the glue that
lets the two be compared. A theorem is a claim about the Rust exactly when a
`RustKopisNeon.…` name appears to the left of its `⦃ … ⦄`.

The `RustKopisNeon` name is not what the Rust crate is called — the crate is `kopis`. It is
imposed by `../extract_rust_to_lean.sh` via aeneas's `-namespace` flag, precisely so that
extracted names cannot be mistaken for Lean-side ones. (Without it the extracted
namespace would be `kopis`, one capital letter away from `Kopis`, this development.)

The suffix on that name is the backend. `../extract_rust_to_lean.sh` extracts the crate once
per backend — the portable build and the x86 build — into a namespace and a file of its own,
and there is one copy of *this* file per extraction, all generated from the portable one by
`make -C lean generated`. So the prefix on the names below is what tells you which backend you
are reading about, and it is the only thing that differs between the copies: the statements
are identical, because the Rust API is.

What each backend *assumes* is not identical, and is deliberately not here — it is in
`TrustBase.lean`, which carries one entry per backend and checks each against its own theorems.
Read that file for the backend you care about; in particular, an accelerated build assumes the
semantics of every SIMD instruction it uses, which the portable build does not.

The proof files under `Kopis/Properties/` do *not* follow this convention — they `open`
everything, because they are dense tactic scripts where the terseness pays. This file is
the one written to be read.

## What you have to check by hand

The Lean kernel checks the proofs. It cannot check that the *statements* say
something meaningful, so these four things are on you:

1. **§2 — the translation layer.** The theorems relate Rust values to spec values
   through functions like `arrayToBytes`. If one of those quietly threw away
   information, the theorems would be true but vacuous. §2 pins down what each
   one does.
2. **§3 — the theorem statements.** That they really do cover the operations you
   care about, applied to arbitrary inputs.
3. **The trust base — `TrustBase.lean`.** The nine assumptions this development
   makes, and why each is there. The build fails if that list ever changes. §4
   below is a summary and a pointer.
4. **§5 — the gaps.** What is deliberately *not* covered.

Two things outside this file remain trusted no matter how carefully you read it:
the audited spec really does describe Kopis (check `Spec/Kopis/Spec.lean` against
`kopis-spec.md`, and note that `make test-kopis-spec` runs it against the test
vectors), and the charon/aeneas extraction really did produce `ExtractedRustNeon.lean`
from `../src/*.rs`.
-/

-- Deliberately minimal: only the Aeneas framework is opened, so every name below
-- carries a prefix identifying which world it comes from (see the reading guide).
open Aeneas Aeneas.Std Result
open Spec (𝔹)

open Kopis.Neon
namespace Kopis.TopLevelNeon

set_option maxRecDepth 8000

/-! ## §1. What the `⦃ … ⦄` notation asserts

Every theorem below has the shape `<rust computation> ⦃ (r : _) => <property of r> ⦄`.
That is Aeneas's total-correctness postcondition, and it is stronger than it
looks: aeneas compiles Rust into a `Result` monad whose failure cases are `fail`
(a panic — arithmetic overflow, array bounds violation, explicit `panic!`,
failed `assert!`) and `div` (nontermination). The postcondition is *false* for
both, so asserting it also asserts that neither happens.

The theorem below makes that explicit, and it is the reason no separate
"does not panic" claim is needed: it is already inside each theorem in §3, for
all inputs, with no side conditions. -/

/-- A `⦃ … ⦄` postcondition says the computation **succeeds** — no panic, no
overflow, no out-of-bounds access, no divergence — *and* its result satisfies the
stated property. -/
theorem triple_means_success {α : Type} {x : Result α} {p : α → Prop} (h : x ⦃ p ⦄) :
    ∃ v, x = ok v ∧ p v := by
  cases x with
  | ok v => exact ⟨v, rfl, h⟩
  | fail e => simp [Aeneas.Std.WP.spec, Aeneas.Std.WP.theta] at h
  | div => simp [Aeneas.Std.WP.spec, Aeneas.Std.WP.theta] at h

/-! ## §2. The translation layer

The Rust side and the spec side use different types, so the theorems are stated
modulo translation functions. These are the place where a "proof" could be made
to say nothing at all — e.g. a translation that mapped every key to the empty
list would make correspondence trivial. So each one is pinned down here.

There are only two, and they are both boring, which is the point. -/

/-- **`arrayToBytes` is byte-for-byte identity.** A Rust `[u8; n]` becomes the
spec's `𝔹 n` by mapping each `U8` to its bit-vector, in order. Nothing is
reordered, truncated, padded or reinterpreted — the underlying byte list is
preserved exactly.

This single translation covers every seed, ciphertext, shared secret and matrix
seed in §3. (`Kopis/Properties/` also defines thin wrappers over it — `skBytes`,
`matSeedBytes` — that only re-index the length; the statements below are written
in terms of `arrayToBytes` directly so that no wrapper has to be trusted here.) -/
theorem arrayToBytes_is_identity {n : Usize} (a : Array U8 n) :
    (Properties.arrayToBytes a).toList = a.val.map (·.bv) :=
  Kopis.Neon.Properties.arrayToBytes_toList a

/-! ### The public key translation, and why it is not question-begging

`pkStructBytes` is the one translation that is not the identity: a Rust
`PkePublicKey` is a *struct* (a matrix of polynomials plus a 32-byte seed), while
the spec's `pk` is a flat byte string. `pkStructBytes` declares the struct's
meaning to be `serialize(vec) ‖ matrix_seed`.

Taken alone that would be an assumption — we would be *defining* the struct to
mean whatever makes the theorems come out right. It is not an assumption,
because the Rust crate's own serializer is proved to emit exactly those bytes.
`pk_serialize_matches_translation` below is that link: whatever
`PkePublicKey::serialize` writes into the output buffer is precisely the spec
serialization of the vector followed by the matrix seed. So a caller who
serializes a public key and puts it on the wire transmits exactly the byte string
the spec calls `pk`. -/

/-- **The Rust public-key serializer emits exactly the bytes `pkStructBytes`
claims.** This is what makes the public-key translation honest rather than
circular. (The two hypotheses are shape side conditions: the output buffer has
the right length, and the serialized size fits in a `usize`.) -/
theorem pk_serialize_matches_translation {L : Usize} (self : RustKopisNeon.pke.PkePublicKey L)
    (out_buf : Slice U8) (hlen : out_buf.val.length = L.val * 320 + 32)
    (hfit : L.val * 10 * 256 ≤ Usize.max) :
    RustKopisNeon.pke.PkePublicKey.serialize self out_buf
      ⦃ (r : Slice U8) => r.length = L.val * (32 * 10) + 32 ∧
          r.val.map (·.bv)
            = (Properties.vecBytesFlat self).toList
            ++ (Properties.arrayToBytes self.matrix_seed).toList ⦄ :=
  Kopis.Neon.Properties.pke_serialize_spec self out_buf hlen hfit

/-! ## §3. The theorems

Four operations × three parameter sets. Every one is **unconditional**: the only
arguments are the inputs themselves, there are no hypotheses to discharge and no
side conditions hiding a restricted input range. Read them as:

> for *all* seeds / ciphertexts / randomness, the Rust computation succeeds and
> its output equals the spec's.

The `2#usize`/`10#usize`-style literals are the Rust const generics `ℓ` and `μ`:
(2, 10) is Kopis-512, (3, 8) is Kopis-768, (4, 6) is Kopis-1024. -/

/-! ### §3.1 Key generation — `expand_from_seed` matches `ExpandDecapKey`

`KemSecretKey::expand_from_seed` is what `Kopis512SecretKey::expand_from_seed`
and (via a random seed) `Kopis512SecretKey::generate` call. The conjuncts below say
that the *observable* components of the resulting key are the corresponding components
of the spec's `ExpandDecapKey`: the implicit-rejection seed `z`, the serialized public
key, and its hash.

`ExpandDecapKey` returns its components as a nested tuple, so the `let` block at the top
of each statement below names them once — `z`, `pk`, `pkHash` — instead of leaving
`.2.2.1`-style projections scattered through the conjuncts. Those are plain `let`s and
definitionally transparent, so the statement is the same proposition as the projected
form; they buy readability and nothing else.

**Why the in-memory secret and public matrix are not stated here.** The internal fields
`pke_sk : NttMatrix L 1` and `pke_pk.mat_a_ntt : NttMatrix L L` hold NTT-domain data —
an invertible linear image of the coefficient form, not the coefficient form itself.
Earlier versions of these theorems characterised them coefficient-wise, via a
representation-bridging function from stored NTT data back to coefficients. That is a
claim about *representation*, not about behaviour, and stating it forced a bridging
definition into the audit surface that a reader would then have to check is the right
one. It has been dropped, for two reasons.

First, neither field is observable. `KemSecretKey`'s wire form is the 32-byte `seed`
it stores (see `seed()` in `src/kem.rs`); the expanded `pke_sk` never reaches a byte
buffer. `mat_a_ntt` is likewise never serialized — `PkePublicKey::serialize` writes
`vec_bytes || matrix_seed` and `from_bytes` re-derives the matrix, which is exactly
what the `pkStructBytes` conjunct below already pins down, byte for byte.

Second, both fields are pinned *behaviourally*, and more strongly, by the composite
theorems that follow. §3.2 (`kopisNNN_keygen_then_encapsulate`) runs encapsulation
against the generated key: encapsulation multiplies by `mat_a_ntt`, so a wrong matrix
gives ciphertext bytes that differ from `KemEncap`'s. §3.3
(`kopisNNN_keygen_then_decapsulate`) runs decapsulation, which multiplies by `pke_sk`,
against the spec's `KemDecap` — and `KemDecap` re-derives the secret from the seed, so a
wrong stored secret gives a different shared secret. Between them, every use the library
makes of these two fields is covered at the byte level, with no representation bridge
anywhere in the statement. -/

/-- **Kopis-512 key generation matches the spec.** -/
theorem kopis512_keygen (seed : Array U8 32#usize) :
    RustKopisNeon.kem.KemSecretKey.expand_from_seed 2#usize 10#usize seed
      ⦃ (ksk : RustKopisNeon.kem.KemSecretKey 2#usize) =>
          -- the spec's key-expansion output, with its observable components named
          let dk     := Spec.Kopis.ExpandDecapKey .Kopis_512 (Properties.arrayToBytes seed)
          let z      := dk.2.1      -- the implicit-rejection seed
          let pk     := dk.2.2.1    -- the serialized public key
          let pkHash := dk.2.2.2    -- and its hash
          Properties.arrayToBytes ksk.z = z ∧
          Properties.pkStructBytes ksk.pke_pk .Kopis_512 rfl = pk ∧
          Properties.arrayToBytes ksk.hash_pke_pk = pkHash ⦄ := by
  apply Aeneas.Std.WP.spec_mono (Kopis.Neon.Properties.expand_from_seed_spec 2#usize 10#usize seed
    .Kopis_512 rfl rfl (by decide) (by decide) (by scalar_tac) (by decide) (by decide))
  rintro ksk ⟨⟨_S, _hSfwd, _hSvec, _hSbnd⟩, hz, hpkb, hhash,
    ⟨_Am, _hAfwd, _hAmat, _hAbnd⟩, ⟨_V, _hVfwd, _hVbnd, _hVbytes⟩⟩
  exact ⟨hz, hpkb, hhash⟩

/-- **Kopis-768 key generation matches the spec.** -/
theorem kopis768_keygen (seed : Array U8 32#usize) :
    RustKopisNeon.kem.KemSecretKey.expand_from_seed 3#usize 8#usize seed
      ⦃ (ksk : RustKopisNeon.kem.KemSecretKey 3#usize) =>
          -- the spec's key-expansion output, with its observable components named
          let dk     := Spec.Kopis.ExpandDecapKey .Kopis_768 (Properties.arrayToBytes seed)
          let z      := dk.2.1      -- the implicit-rejection seed
          let pk     := dk.2.2.1    -- the serialized public key
          let pkHash := dk.2.2.2    -- and its hash
          Properties.arrayToBytes ksk.z = z ∧
          Properties.pkStructBytes ksk.pke_pk .Kopis_768 rfl = pk ∧
          Properties.arrayToBytes ksk.hash_pke_pk = pkHash ⦄ := by
  apply Aeneas.Std.WP.spec_mono (Kopis.Neon.Properties.expand_from_seed_spec 3#usize 8#usize seed
    .Kopis_768 rfl rfl (by decide) (by decide) (by scalar_tac) (by decide) (by decide))
  rintro ksk ⟨⟨_S, _hSfwd, _hSvec, _hSbnd⟩, hz, hpkb, hhash,
    ⟨_Am, _hAfwd, _hAmat, _hAbnd⟩, ⟨_V, _hVfwd, _hVbnd, _hVbytes⟩⟩
  exact ⟨hz, hpkb, hhash⟩

/-- **Kopis-1024 key generation matches the spec.** -/
theorem kopis1024_keygen (seed : Array U8 32#usize) :
    RustKopisNeon.kem.KemSecretKey.expand_from_seed 4#usize 6#usize seed
      ⦃ (ksk : RustKopisNeon.kem.KemSecretKey 4#usize) =>
          -- the spec's key-expansion output, with its observable components named
          let dk     := Spec.Kopis.ExpandDecapKey .Kopis_1024 (Properties.arrayToBytes seed)
          let z      := dk.2.1      -- the implicit-rejection seed
          let pk     := dk.2.2.1    -- the serialized public key
          let pkHash := dk.2.2.2    -- and its hash
          Properties.arrayToBytes ksk.z = z ∧
          Properties.pkStructBytes ksk.pke_pk .Kopis_1024 rfl = pk ∧
          Properties.arrayToBytes ksk.hash_pke_pk = pkHash ⦄ := by
  apply Aeneas.Std.WP.spec_mono (Kopis.Neon.Properties.expand_from_seed_spec 4#usize 6#usize seed
    .Kopis_1024 rfl rfl (by decide) (by decide) (by scalar_tac) (by decide) (by decide))
  rintro ksk ⟨⟨_S, _hSfwd, _hSvec, _hSbnd⟩, hz, hpkb, hhash,
    ⟨_Am, _hAfwd, _hAmat, _hAbnd⟩, ⟨_V, _hVfwd, _hVbnd, _hVbytes⟩⟩
  exact ⟨hz, hpkb, hhash⟩

/-! ### §3.2 Encapsulation — key generation then encapsulate matches `KemEncap`

These state the composite operation a user actually performs: generate a secret
key from a seed, derive the public key, encapsulate to it. The result is the
spec's `KemEncap` applied to the spec's `SkToPk` of the same seed — so the two
halves agree about what the public key is, which is what makes the composition
meaningful rather than each half matching a different notion of "public key".

Note this is needed separately from encapsulating to a deserialized public key.
This is because the public key you get from keygen is not the result of
deserialization. Of course, this should not matter, but you have to prove that. -/

/-- **Kopis-512: key-gen → public key → encapsulate matches `KemEncap`.** -/
theorem kopis512_keygen_then_encapsulate (seed randomness : Array U8 32#usize) :
    (do let ksk ← RustKopisNeon.kem.KemSecretKey.expand_from_seed 2#usize 10#usize seed
        let kpk ← RustKopisNeon.impls.kopis512.Kopis512SecretKey.public_key ksk
        RustKopisNeon.impls.kopis512.Kopis512PublicKey.encapsulate_deterministic kpk randomness)
      ⦃ (ct : Array U8 736#usize) (ss : RustKopisNeon.impls.SharedSecret) =>
          -- the spec's encapsulation, with its two components named
          let specRes   := Spec.Kopis.KemEncap .Kopis_512 (Properties.arrayToBytes randomness)
                          (Spec.Kopis.SkToPk .Kopis_512 (Properties.arrayToBytes seed))
          let specSs := specRes.1      -- the spec returns (shared secret, ciphertext) …
          let specCt := specRes.2      -- … i.e. the opposite order from Rust
          Properties.arrayToBytes ct = specCt ∧
          Properties.arrayToBytes ss = specSs ⦄ :=
  Kopis.Neon.Properties.kopis512_keygen_encap_spec seed randomness

/-- **Kopis-768: key-gen → public key → encapsulate matches `KemEncap`.** -/
theorem kopis768_keygen_then_encapsulate (seed randomness : Array U8 32#usize) :
    (do let ksk ← RustKopisNeon.kem.KemSecretKey.expand_from_seed 3#usize 8#usize seed
        let kpk ← RustKopisNeon.impls.kopis768.Kopis768SecretKey.public_key ksk
        RustKopisNeon.impls.kopis768.Kopis768PublicKey.encapsulate_deterministic kpk randomness)
      ⦃ (ct : Array U8 1088#usize) (ss : RustKopisNeon.impls.SharedSecret) =>
          -- the spec's encapsulation, with its two components named
          let specRes   := Spec.Kopis.KemEncap .Kopis_768 (Properties.arrayToBytes randomness)
                          (Spec.Kopis.SkToPk .Kopis_768 (Properties.arrayToBytes seed))
          let specSs := specRes.1      -- the spec returns (shared secret, ciphertext) …
          let specCt := specRes.2      -- … i.e. the opposite order from Rust
          Properties.arrayToBytes ct = specCt ∧
          Properties.arrayToBytes ss = specSs ⦄ :=
  Kopis.Neon.Properties.kopis768_keygen_encap_spec seed randomness

/-- **Kopis-1024: key-gen → public key → encapsulate matches `KemEncap`.** -/
theorem kopis1024_keygen_then_encapsulate (seed randomness : Array U8 32#usize) :
    (do let ksk ← RustKopisNeon.kem.KemSecretKey.expand_from_seed 4#usize 6#usize seed
        let kpk ← RustKopisNeon.impls.kopis1024.Kopis1024SecretKey.public_key ksk
        RustKopisNeon.impls.kopis1024.Kopis1024PublicKey.encapsulate_deterministic kpk randomness)
      ⦃ (ct : Array U8 1472#usize) (ss : RustKopisNeon.impls.SharedSecret) =>
          -- the spec's encapsulation, with its two components named
          let specRes   := Spec.Kopis.KemEncap .Kopis_1024 (Properties.arrayToBytes randomness)
                          (Spec.Kopis.SkToPk .Kopis_1024 (Properties.arrayToBytes seed))
          let specSs := specRes.1      -- the spec returns (shared secret, ciphertext) …
          let specCt := specRes.2      -- … i.e. the opposite order from Rust
          Properties.arrayToBytes ct = specCt ∧
          Properties.arrayToBytes ss = specSs ⦄ :=
  Kopis.Neon.Properties.kopis1024_keygen_encap_spec seed randomness

/-! ### §3.2b Receiving a public key — parse then encapsulate matches `KemEncap`

The theorems above start from a locally generated key. These start from a public key
*received as bytes*, which is what a caller does with a key off the wire: parse it with
`from_bytes`, then encapsulate to it. The result is the spec's `KemEncap` applied to
exactly those bytes.

Nothing constrains the input bytes beyond their length, so a malformed or
adversarially chosen public-key encoding is covered — and, this being a `⦃ … ⦄` triple,
the composite is also proved not to panic on one.

The `let` block names the spec's two components for the same reason as in §3.2. -/

/-- **Kopis-512: parse a received public key, then encapsulate to it.** -/
theorem kopis512_from_bytes_then_encapsulate (pk_bytes : Array U8 672#usize)
    (randomness : Array U8 32#usize) :
    (do let kpk ← RustKopisNeon.impls.kopis512.Kopis512PublicKey.from_bytes pk_bytes
        RustKopisNeon.impls.kopis512.Kopis512PublicKey.encapsulate_deterministic kpk randomness)
      ⦃ (ct : Array U8 736#usize) (ss : RustKopisNeon.impls.SharedSecret) =>
          -- the spec's encapsulation, with its two components named
          let spec   := Spec.Kopis.KemEncap .Kopis_512 (Properties.arrayToBytes randomness)
                          (Properties.arrayToBytes pk_bytes)
          let specSs := spec.1      -- the spec returns (shared secret, ciphertext) …
          let specCt := spec.2      -- … i.e. the opposite order from Rust
          Properties.arrayToBytes ct = specCt ∧
          Properties.arrayToBytes ss = specSs ⦄ :=
  Kopis.Neon.Properties.kopis512_from_bytes_encap_spec pk_bytes randomness

/-- **Kopis-768: parse a received public key, then encapsulate to it.** -/
theorem kopis768_from_bytes_then_encapsulate (pk_bytes : Array U8 992#usize)
    (randomness : Array U8 32#usize) :
    (do let kpk ← RustKopisNeon.impls.kopis768.Kopis768PublicKey.from_bytes pk_bytes
        RustKopisNeon.impls.kopis768.Kopis768PublicKey.encapsulate_deterministic kpk randomness)
      ⦃ (ct : Array U8 1088#usize) (ss : RustKopisNeon.impls.SharedSecret) =>
          -- the spec's encapsulation, with its two components named
          let spec   := Spec.Kopis.KemEncap .Kopis_768 (Properties.arrayToBytes randomness)
                          (Properties.arrayToBytes pk_bytes)
          let specSs := spec.1      -- the spec returns (shared secret, ciphertext) …
          let specCt := spec.2      -- … i.e. the opposite order from Rust
          Properties.arrayToBytes ct = specCt ∧
          Properties.arrayToBytes ss = specSs ⦄ :=
  Kopis.Neon.Properties.kopis768_from_bytes_encap_spec pk_bytes randomness

/-- **Kopis-1024: parse a received public key, then encapsulate to it.** -/
theorem kopis1024_from_bytes_then_encapsulate (pk_bytes : Array U8 1312#usize)
    (randomness : Array U8 32#usize) :
    (do let kpk ← RustKopisNeon.impls.kopis1024.Kopis1024PublicKey.from_bytes pk_bytes
        RustKopisNeon.impls.kopis1024.Kopis1024PublicKey.encapsulate_deterministic kpk randomness)
      ⦃ (ct : Array U8 1472#usize) (ss : RustKopisNeon.impls.SharedSecret) =>
          -- the spec's encapsulation, with its two components named
          let spec   := Spec.Kopis.KemEncap .Kopis_1024 (Properties.arrayToBytes randomness)
                          (Properties.arrayToBytes pk_bytes)
          let specSs := spec.1      -- the spec returns (shared secret, ciphertext) …
          let specCt := spec.2      -- … i.e. the opposite order from Rust
          Properties.arrayToBytes ct = specCt ∧
          Properties.arrayToBytes ss = specSs ⦄ :=
  Kopis.Neon.Properties.kopis1024_from_bytes_encap_spec pk_bytes randomness

/-! ### §3.3 Decapsulation — key generation then decapsulate matches `KemDecap`

Note what is *not* assumed: the ciphertext `ek` is an arbitrary byte array, not
one produced by encapsulation. So this covers the adversarial case — malformed,
adversarially chosen and replayed ciphertexts included — and in particular the
implicit-rejection path, where a ciphertext that fails the re-encryption check
must yield the pseudorandom `z`-derived secret rather than an error or a leak. -/

/-- **Kopis-512: key-gen → decapsulate an arbitrary ciphertext matches `KemDecap`.** -/
theorem kopis512_keygen_then_decapsulate (seed : Array U8 32#usize) (ek : Array U8 736#usize) :
    (do let ksk ← RustKopisNeon.kem.KemSecretKey.expand_from_seed 2#usize 10#usize seed
        RustKopisNeon.impls.kopis512.Kopis512SecretKey.decapsulate ksk ek)
      ⦃ (r : RustKopisNeon.impls.SharedSecret) =>
          Properties.arrayToBytes r
            = Spec.Kopis.KemDecap .Kopis_512 (Properties.arrayToBytes seed)
                (Properties.arrayToBytes ek) ⦄ :=
  Kopis.Neon.Properties.kopis512_keygen_decap_spec seed ek

/-- **Kopis-768: key-gen → decapsulate an arbitrary ciphertext matches `KemDecap`.** -/
theorem kopis768_keygen_then_decapsulate (seed : Array U8 32#usize) (ek : Array U8 1088#usize) :
    (do let ksk ← RustKopisNeon.kem.KemSecretKey.expand_from_seed 3#usize 8#usize seed
        RustKopisNeon.impls.kopis768.Kopis768SecretKey.decapsulate ksk ek)
      ⦃ (r : RustKopisNeon.impls.SharedSecret) =>
          Properties.arrayToBytes r
            = Spec.Kopis.KemDecap .Kopis_768 (Properties.arrayToBytes seed)
                (Properties.arrayToBytes ek) ⦄ :=
  Kopis.Neon.Properties.kopis768_keygen_decap_spec seed ek

/-- **Kopis-1024: key-gen → decapsulate an arbitrary ciphertext matches `KemDecap`.** -/
theorem kopis1024_keygen_then_decapsulate (seed : Array U8 32#usize) (ek : Array U8 1472#usize) :
    (do let ksk ← RustKopisNeon.kem.KemSecretKey.expand_from_seed 4#usize 6#usize seed
        RustKopisNeon.impls.kopis1024.Kopis1024SecretKey.decapsulate ksk ek)
      ⦃ (r : RustKopisNeon.impls.SharedSecret) =>
          Properties.arrayToBytes r
            = Spec.Kopis.KemDecap .Kopis_1024 (Properties.arrayToBytes seed)
                (Properties.arrayToBytes ek) ⦄ :=
  Kopis.Neon.Properties.kopis1024_keygen_decap_spec seed ek

/-! ## §4. The trust base — in `TrustBase.lean`

The assumptions everything in §3 rests on, the reasoning for each, and the build-time check
that enforces the list are in `TrustBase.lean`. Read it next; it is short.

It is a separate file because the trust base is the one part of this audit that differs per
backend — an AVX2 build additionally assumes the semantics of every SIMD instruction it uses —
whereas the statements in §3 do not differ that way. Keeping the split means the statements are
read once and the per-backend difference is visible in one place.

In summary, and beyond Lean's own three axioms: the `turboshake` crate's API implements RFC 9861
(5 assumptions, the largest one here), `subtle`'s constant-time select and equality have their
obvious functional meaning (2, functional only — nothing about actual timing), Rust's two
popcount intrinsics mean popcount (2). Nothing is discharged by compiled evaluation any more.
No `sorry` is in the closure, and the check fails the build if one reappears. -/

/-! ## §5. What is *not* proved

A verification claim is only as useful as its boundary. This one does not cover:

**Randomness.** `Kopis512SecretKey::generate` and `Kopis512PublicKey::encapsulate`
draw from a caller-supplied `CryptoRng`. The theorems in §3 cover the deterministic
cores those wrappers call (`expand_from_seed`, `encapsulate_deterministic`) as
functions of the seed / randomness they are handed. Nothing here says anything
about the quality of the RNG, and nothing checks that the wrappers pass the random
bytes through faithfully.

**Nothing about public-key deserialization** — this gap is now closed, by
the three parse-then-encapsulate theorems in
§3.2b.

**Trivial accessors.** `SecretKey::seed`, `SharedSecret::as_bytes` and similar
getters have no theorems.

**KEM correctness as a mathematical property.** Nothing here proves that
decapsulating a validly encapsulated ciphertext recovers the encapsulator's shared
secret. That is a property of the *specification*, not of the Rust, and it is not
proved anywhere in this development — it is only checked empirically, by
`make test-kopis-spec`, on the bundled test vectors.

**Side channels.** The `subtle` assumptions (`TrustBase.lean`, group (b)) fix only the *functional* meaning
of constant-time primitives. Nothing here rules out timing or cache leaks; those
are properties of compiled machine code, which is outside what a source-level
proof about Rust semantics can see.

**Memory zeroization.** No claim that secret material is wiped after use.

**The extraction and the spec themselves.** As noted at the top: that
`ExtractedRustNeon.lean` faithfully reflects `../src/*.rs` is a property of
charon/aeneas, and that `Spec/Kopis/Spec.lean` faithfully reflects `kopis-spec.md`
is a matter for human review plus the KAT runner. -/

end Kopis.TopLevelNeon
