import TopLevelTheoremsSerial
import TopLevelTheoremsAvx2
import TopLevelTheoremsNeon

/-!
# The trusted Lean base of our proofs

This module performs an accounting of all the axioms we use in our proofs. It panics if it
encounters an unexpected axiom used by one of the top-level theorems.
-/

open Lean

/-- Axioms that appear in all backends -/
def commonAxioms : List String :=
  [-- Lean builtin. Propositional extensionality, `(a ↔ b) → a = b`
   "propext",
   -- Lean builtin. Axiom of choice
   "Classical.choice",
   -- Lean builtin. Elements related by R are definitionally equal in quotient space over rel R
   "Quot.sound",
   -- Aeneas builtin. Stand-in for Rust's `core::fmt` machinery
   "Aeneas.Std.core.fmt.Formatter"]

/--
The serial backend needs some axiomatized integer intrinsics, `subtle` crate axioms, and
`turboshake` crate axioms.
-/
def serialAudited : List String := commonAxioms ++
  ["Kopis.Properties.U16.count_ones_spec",
   "Kopis.Properties.U8.count_ones_spec",
   "Kopis.Properties.conditional_select_array_u8_spec",
   "Kopis.Properties.ct_eq_slice_u8_spec",
   "Kopis.Properties.hasher_default_spec",
   "Kopis.Properties.hasher_finalize_spec",
   "Kopis.Properties.hasher_update_spec",
   "Kopis.Properties.reader_read136_spec",
   "Kopis.Properties.reader_read168_spec",
   "RustKopisSerial.Array.Insts.SubtleConditionallySelectable.conditional_select",
   "RustKopisSerial.Slice.Insts.SubtleConstantTimeEq.ct_eq",
   "RustKopisSerial.U8.Insts.SubtleConditionallySelectable.conditional_select",
   "RustKopisSerial.U8.Insts.SubtleConstantTimeEq.ct_eq",
   "RustKopisSerial.core.num.U16.count_ones",
   "RustKopisSerial.core.num.U8.count_ones",
   "RustKopisSerial.subtle.Choice",
   "RustKopisSerial.turboshake.TurboShake",
   "RustKopisSerial.turboshake.TurboShake.Insts.CoreDefaultDefault.default",
   "RustKopisSerial.turboshake.TurboShake.Insts.DigestExtendableOutputTurboShakeReader.finalize_xof",
   "RustKopisSerial.turboshake.TurboShake.Insts.DigestUpdate.update",
   "RustKopisSerial.turboshake.TurboShakeReader",
   "RustKopisSerial.turboshake.TurboShakeReader.Insts.DigestXofReader.read"]

/--
The AVX2 crate needs lots of axiomatized SIMD intrinsics. In addition it also needs `turboshake` and
`sutble` axioms. It also needs `bv_decide`, which decides theorems by running programs natively and
producing a receipt that is validated by a Lean program.
-/
def avx2Audited : List String := commonAxioms ++
  ["Kopis.Avx2.CbdGeneric.U16.count_ones_spec",
   "Kopis.Avx2.CbdGeneric.U8.count_ones_spec",
   "Kopis.Avx2.Properties.U16.count_ones_spec",
   "Kopis.Avx2.Properties.U8.count_ones_spec",
   "Kopis.Avx2.Properties.conditional_select_array_u8_spec",
   "Kopis.Avx2.Properties.ct_eq_slice_u8_spec",
   "Kopis.Avx2.Properties.hasher_default_spec",
   "Kopis.Avx2.Properties.hasher_finalize_spec",
   "Kopis.Avx2.Properties.hasher_update_spec",
   "Kopis.Avx2.Properties.reader_read136_spec",
   "Kopis.Avx2.Properties.reader_read168_spec",
   "Kopis.Avx2.add_epi16_spec",
   "Kopis.Avx2.add_epi32_spec",
   "Kopis.Avx2.and_si256_spec",
   "Kopis.Avx2.andnot_si256_spec",
   "Kopis.Avx2.available_ok",
   "Kopis.Avx2.bits",  -- Shows that an opaque AVX2 register is equivalent to a bitvec
   "Kopis.Avx2.bits'", -- Ditto
   "Kopis.Avx2.broadcastsi128_si256_spec",
   "Kopis.Avx2.castsi256_si128_spec",
   "Kopis.Avx2.cmpgt_epi32_spec",
   "Kopis.Avx2.cvtepu16_epi32_spec",
   "Kopis.Avx2.cvtsi32_si128_spec",
   "Kopis.Avx2.extracti128_si256_spec",
   "Kopis.Avx2.load_i16_spec",
   "Kopis.Avx2.load_i32_spec",
   "Kopis.Avx2.load_u16_spec",
   "Kopis.Avx2.load_u8_spec",
   "Kopis.Avx2.load_u8x16_spec",
   "Kopis.Avx2.load_u8x32_spec",
   "Kopis.Avx2.mulhi_epi16_spec",
   "Kopis.Avx2.mullo_epi16_spec",
   "Kopis.Avx2.mullo_epi32_spec",
   "Kopis.Avx2.or_si256_spec",
   "Kopis.Avx2.packs_epi32_spec",
   "Kopis.Avx2.packus_epi32_spec",
   "Kopis.Avx2.permute2x128_si256_spec",
   "Kopis.Avx2.permute4x64_epi64_spec",
   "Kopis.Avx2.set1_epi16_spec",
   "Kopis.Avx2.set1_epi32_spec",
   "Kopis.Avx2.set1_epi64x_spec",
   "Kopis.Avx2.setzero_si256_spec",
   "Kopis.Avx2.shuffle_epi8_spec",
   "Kopis.Avx2.slli_epi32_spec",
   "Kopis.Avx2.slli_epi64_spec",
   "Kopis.Avx2.srai_epi16_spec",
   "Kopis.Avx2.srai_epi32_spec",
   "Kopis.Avx2.srl_epi16_spec",
   "Kopis.Avx2.srli_epi16_spec",
   "Kopis.Avx2.srli_epi64_spec",
   "Kopis.Avx2.srlv_epi32_spec",
   "Kopis.Avx2.store_i16_spec",
   "Kopis.Avx2.store_i32_spec",
   "Kopis.Avx2.store_u16_spec",
   "Kopis.Avx2.store_u8x32_spec",
   "Kopis.Avx2.sub_epi16_spec",
   "Kopis.Avx2.sub_epi32_spec",
   "Kopis.Avx2.unpackhi_epi16_spec",
   "Kopis.Avx2.unpackhi_epi32_spec",
   "Kopis.Avx2.unpackhi_epi64_spec",
   "Kopis.Avx2.unpacklo_epi16_spec",
   "Kopis.Avx2.unpacklo_epi32_spec",
   "Kopis.Avx2.unpacklo_epi64_spec",
   "Kopis.Avx2.xor_si256_spec",
   "RustKopisAvx2.Array.Insts.SubtleConditionallySelectable.conditional_select",
   "RustKopisAvx2.Slice.Insts.SubtleConstantTimeEq.ct_eq",
   "RustKopisAvx2.U8.Insts.SubtleConditionallySelectable.conditional_select",
   "RustKopisAvx2.U8.Insts.SubtleConstantTimeEq.ct_eq",
   "RustKopisAvx2.backend.avx2.cpu.available",
   "RustKopisAvx2.backend.avx2.intrinsics.Vec128",
   "RustKopisAvx2.backend.avx2.intrinsics.Vec256",
   "RustKopisAvx2.backend.avx2.intrinsics.add_epi16",
   "RustKopisAvx2.backend.avx2.intrinsics.add_epi32",
   "RustKopisAvx2.backend.avx2.intrinsics.and_si256",
   "RustKopisAvx2.backend.avx2.intrinsics.andnot_si256",
   "RustKopisAvx2.backend.avx2.intrinsics.broadcastsi128_si256",
   "RustKopisAvx2.backend.avx2.intrinsics.castsi256_si128",
   "RustKopisAvx2.backend.avx2.intrinsics.cmpgt_epi32",
   "RustKopisAvx2.backend.avx2.intrinsics.cvtepu16_epi32",
   "RustKopisAvx2.backend.avx2.intrinsics.cvtsi32_si128",
   "RustKopisAvx2.backend.avx2.intrinsics.extracti128_si256",
   "RustKopisAvx2.backend.avx2.intrinsics.load_i16",
   "RustKopisAvx2.backend.avx2.intrinsics.load_i32",
   "RustKopisAvx2.backend.avx2.intrinsics.load_u16",
   "RustKopisAvx2.backend.avx2.intrinsics.load_u8",
   "RustKopisAvx2.backend.avx2.intrinsics.load_u8x16",
   "RustKopisAvx2.backend.avx2.intrinsics.load_u8x32",
   "RustKopisAvx2.backend.avx2.intrinsics.mulhi_epi16",
   "RustKopisAvx2.backend.avx2.intrinsics.mullo_epi16",
   "RustKopisAvx2.backend.avx2.intrinsics.mullo_epi32",
   "RustKopisAvx2.backend.avx2.intrinsics.or_si256",
   "RustKopisAvx2.backend.avx2.intrinsics.packs_epi32",
   "RustKopisAvx2.backend.avx2.intrinsics.packus_epi32",
   "RustKopisAvx2.backend.avx2.intrinsics.permute2x128_si256",
   "RustKopisAvx2.backend.avx2.intrinsics.permute4x64_epi64",
   "RustKopisAvx2.backend.avx2.intrinsics.set1_epi16",
   "RustKopisAvx2.backend.avx2.intrinsics.set1_epi32",
   "RustKopisAvx2.backend.avx2.intrinsics.set1_epi64x",
   "RustKopisAvx2.backend.avx2.intrinsics.setzero_si256",
   "RustKopisAvx2.backend.avx2.intrinsics.shuffle_epi8",
   "RustKopisAvx2.backend.avx2.intrinsics.slli_epi32",
   "RustKopisAvx2.backend.avx2.intrinsics.slli_epi64",
   "RustKopisAvx2.backend.avx2.intrinsics.srai_epi16",
   "RustKopisAvx2.backend.avx2.intrinsics.srai_epi32",
   "RustKopisAvx2.backend.avx2.intrinsics.srl_epi16",
   "RustKopisAvx2.backend.avx2.intrinsics.srli_epi16",
   "RustKopisAvx2.backend.avx2.intrinsics.srli_epi64",
   "RustKopisAvx2.backend.avx2.intrinsics.srlv_epi32",
   "RustKopisAvx2.backend.avx2.intrinsics.store_i16",
   "RustKopisAvx2.backend.avx2.intrinsics.store_i32",
   "RustKopisAvx2.backend.avx2.intrinsics.store_u16",
   "RustKopisAvx2.backend.avx2.intrinsics.store_u8x32",
   "RustKopisAvx2.backend.avx2.intrinsics.sub_epi16",
   "RustKopisAvx2.backend.avx2.intrinsics.sub_epi32",
   "RustKopisAvx2.backend.avx2.intrinsics.unpackhi_epi16",
   "RustKopisAvx2.backend.avx2.intrinsics.unpackhi_epi32",
   "RustKopisAvx2.backend.avx2.intrinsics.unpackhi_epi64",
   "RustKopisAvx2.backend.avx2.intrinsics.unpacklo_epi16",
   "RustKopisAvx2.backend.avx2.intrinsics.unpacklo_epi32",
   "RustKopisAvx2.backend.avx2.intrinsics.unpacklo_epi64",
   "RustKopisAvx2.backend.avx2.intrinsics.xor_si256",
   "RustKopisAvx2.core.num.U16.count_ones",
   "RustKopisAvx2.core.num.U8.count_ones",
   "RustKopisAvx2.subtle.Choice",
   "RustKopisAvx2.turboshake.TurboShake",
   "RustKopisAvx2.turboshake.TurboShake.Insts.CoreDefaultDefault.default",
   "RustKopisAvx2.turboshake.TurboShake.Insts.DigestExtendableOutputTurboShakeReader.finalize_xof",
   "RustKopisAvx2.turboshake.TurboShake.Insts.DigestUpdate.update",
   "RustKopisAvx2.turboshake.TurboShakeReader",
   "RustKopisAvx2.turboshake.TurboShakeReader.Insts.DigestXofReader.read",
   "_private.Kopis.Avx2.NttMulLane.0.Kopis.Avx2.join_prod._native.bv_decide.ax_1_5",
   "_private.Kopis.Avx2.Reduce.0.Kopis.Avx2.and_low16._native.bv_decide.ax_1_5",
   "_private.Kopis.Avx2.Reduce.0.Kopis.Avx2.sar_eq._native.bv_decide.ax_1_5",
   "_private.Kopis.Avx2.Reduce.0.Kopis.Avx2.shl_sar_eq._native.bv_decide.ax_1_5"]

/-- Axioms required by the NEON backend. Same genres here as avx2Audited -/
def neonAudited : List String := commonAxioms ++
  ["Kopis.Neon.CbdGeneric.U16.count_ones_spec",
   "Kopis.Neon.CbdGeneric.U8.count_ones_spec",
   "Kopis.Neon.I16.wrapping_neg_spec",
   "Kopis.Neon.Keccak.Usize.div_ceil_spec",
   "Kopis.Neon.Properties.U16.count_ones_spec",
   "Kopis.Neon.Properties.U8.count_ones_spec",
   "Kopis.Neon.Properties.conditional_select_array_u8_spec",
   "Kopis.Neon.Properties.ct_eq_slice_u8_spec",
   "Kopis.Neon.Properties.hasher_default_spec",
   "Kopis.Neon.Properties.hasher_finalize_spec",
   "Kopis.Neon.Properties.hasher_update_spec",
   "Kopis.Neon.Properties.reader_read136_spec",
   "Kopis.Neon.Properties.reader_read168_spec",
   "Kopis.Neon.add_16_spec",
   "Kopis.Neon.add_32_spec",
   "Kopis.Neon.and_spec",
   "Kopis.Neon.bcax_spec",
   "Kopis.Neon.bits",
   "Kopis.Neon.cmgt_s32_spec",
   "Kopis.Neon.cnt_u8_spec",
   "Kopis.Neon.dup_n_s16_spec",
   "Kopis.Neon.dup_n_s32_spec",
   "Kopis.Neon.dup_n_u16_spec",
   "Kopis.Neon.dup_n_u32_spec",
   "Kopis.Neon.dup_n_u64_spec",
   "Kopis.Neon.eor3_spec",
   "Kopis.Neon.eor_spec",
   "Kopis.Neon.load_i16_spec",
   "Kopis.Neon.load_i32_spec",
   "Kopis.Neon.load_u16_spec",
   "Kopis.Neon.load_u8x16_spec",
   "Kopis.Neon.mla_32_spec",
   "Kopis.Neon.mul_16_spec",
   "Kopis.Neon.rax1_spec",
   "Kopis.Neon.set_u64x2_spec",
   "Kopis.Neon.shrn16_pair_s32_spec",
   "Kopis.Neon.shsub_s16_spec",
   "Kopis.Neon.smull_high_s16_spec",
   "Kopis.Neon.smull_low_s16_spec",
   "Kopis.Neon.sqdmulh_s16_spec",
   "Kopis.Neon.sshr_n_s16_spec",
   "Kopis.Neon.store_i16_spec",
   "Kopis.Neon.store_i32_spec",
   "Kopis.Neon.store_u16_spec",
   "Kopis.Neon.store_u8x16_spec",
   "Kopis.Neon.sub_16_spec",
   "Kopis.Neon.sub_32_spec",
   "Kopis.Neon.sxtl_high_s16_spec",
   "Kopis.Neon.sxtl_low_s16_spec",
   "Kopis.Neon.tbl1_u8_spec",
   "Kopis.Neon.trn1_16_spec",
   "Kopis.Neon.trn1_32_spec",
   "Kopis.Neon.trn1_64_spec",
   "Kopis.Neon.trn2_16_spec",
   "Kopis.Neon.trn2_32_spec",
   "Kopis.Neon.trn2_64_spec",
   "Kopis.Neon.ushl_u16_spec",
   "Kopis.Neon.ushl_u32_spec",
   "Kopis.Neon.xar_spec",
   "Kopis.Neon.xtn_pair_32_spec",
   "RustKopisNeon.Array.Insts.SubtleConditionallySelectable.conditional_select",
   "RustKopisNeon.Slice.Insts.SubtleConstantTimeEq.ct_eq",
   "RustKopisNeon.U8.Insts.SubtleConditionallySelectable.conditional_select",
   "RustKopisNeon.U8.Insts.SubtleConstantTimeEq.ct_eq",
   "RustKopisNeon.backend.neon.intrinsics.Vec128",
   "RustKopisNeon.backend.neon.intrinsics.add_16",
   "RustKopisNeon.backend.neon.intrinsics.add_32",
   "RustKopisNeon.backend.neon.intrinsics.and",
   "RustKopisNeon.backend.neon.intrinsics.bcax",
   "RustKopisNeon.backend.neon.intrinsics.cmgt_s32",
   "RustKopisNeon.backend.neon.intrinsics.cnt_u8",
   "RustKopisNeon.backend.neon.intrinsics.dup_n_s16",
   "RustKopisNeon.backend.neon.intrinsics.dup_n_s32",
   "RustKopisNeon.backend.neon.intrinsics.dup_n_u16",
   "RustKopisNeon.backend.neon.intrinsics.dup_n_u32",
   "RustKopisNeon.backend.neon.intrinsics.dup_n_u64",
   "RustKopisNeon.backend.neon.intrinsics.eor",
   "RustKopisNeon.backend.neon.intrinsics.eor3",
   "RustKopisNeon.backend.neon.intrinsics.load_i16",
   "RustKopisNeon.backend.neon.intrinsics.load_i32",
   "RustKopisNeon.backend.neon.intrinsics.load_u16",
   "RustKopisNeon.backend.neon.intrinsics.load_u8x16",
   "RustKopisNeon.backend.neon.intrinsics.mla_32",
   "RustKopisNeon.backend.neon.intrinsics.mul_16",
   "RustKopisNeon.backend.neon.intrinsics.rax1",
   "RustKopisNeon.backend.neon.intrinsics.set_u64x2",
   "RustKopisNeon.backend.neon.intrinsics.shrn16_pair_s32",
   "RustKopisNeon.backend.neon.intrinsics.shsub_s16",
   "RustKopisNeon.backend.neon.intrinsics.smull_high_s16",
   "RustKopisNeon.backend.neon.intrinsics.smull_low_s16",
   "RustKopisNeon.backend.neon.intrinsics.sqdmulh_s16",
   "RustKopisNeon.backend.neon.intrinsics.sshr_n_s16",
   "RustKopisNeon.backend.neon.intrinsics.store_i16",
   "RustKopisNeon.backend.neon.intrinsics.store_i32",
   "RustKopisNeon.backend.neon.intrinsics.store_u16",
   "RustKopisNeon.backend.neon.intrinsics.store_u8x16",
   "RustKopisNeon.backend.neon.intrinsics.sub_16",
   "RustKopisNeon.backend.neon.intrinsics.sub_32",
   "RustKopisNeon.backend.neon.intrinsics.sxtl_high_s16",
   "RustKopisNeon.backend.neon.intrinsics.sxtl_low_s16",
   "RustKopisNeon.backend.neon.intrinsics.tbl1_u8",
   "RustKopisNeon.backend.neon.intrinsics.trn1_16",
   "RustKopisNeon.backend.neon.intrinsics.trn1_32",
   "RustKopisNeon.backend.neon.intrinsics.trn1_64",
   "RustKopisNeon.backend.neon.intrinsics.trn2_16",
   "RustKopisNeon.backend.neon.intrinsics.trn2_32",
   "RustKopisNeon.backend.neon.intrinsics.trn2_64",
   "RustKopisNeon.backend.neon.intrinsics.ushl_u16",
   "RustKopisNeon.backend.neon.intrinsics.ushl_u32",
   "RustKopisNeon.backend.neon.intrinsics.xar",
   "RustKopisNeon.backend.neon.intrinsics.xtn_pair_32",
   "RustKopisNeon.core.num.I16.wrapping_neg",
   "RustKopisNeon.core.num.U16.count_ones",
   "RustKopisNeon.core.num.U8.count_ones",
   "RustKopisNeon.core.num.Usize.div_ceil",
   "RustKopisNeon.subtle.Choice",
   "RustKopisNeon.turboshake.TurboShake",
   "RustKopisNeon.turboshake.TurboShake.Insts.CoreDefaultDefault.default",
   "RustKopisNeon.turboshake.TurboShake.Insts.DigestExtendableOutputTurboShakeReader.finalize_xof",
   "RustKopisNeon.turboshake.TurboShake.Insts.DigestUpdate.update",
   "RustKopisNeon.turboshake.TurboShakeReader",
   "RustKopisNeon.turboshake.TurboShakeReader.Insts.DigestXofReader.read"]

/- Go through all the theorems and dump their axioms. Make sure every axiom is on the list. If not,
throw an error -/
open Lean in
run_cmd do
  let backends : List (String × Name × List String) :=
    [("RustKopisSerial", `Kopis.TopLevelSerial, serialAudited),
     ("RustKopisAvx2", `Kopis.TopLevelAvx2, avx2Audited),
     ("RustKopisNeon", `Kopis.TopLevelNeon, neonAudited)]
  let constants := (← getEnv).constants.toList
  for (label, ns, audited) in backends do
    let theorems := constants.filterMap fun (n, ci) =>
      if ns.isPrefixOf n && !n.isInternal && ci matches .thmInfo _ then some n else none
    if theorems.isEmpty then
      throwError "NO AUDIT SURFACE for {label} — {ns} contains no theorems. Has it been \
        renamed, or did its import fail?"
    let mut found : Array String := #[]
    for t in theorems do
      for a in (← Lean.collectAxioms t) do
        let s := a.toString
        if !found.contains s then found := found.push s
    let unexpected := found.filter (fun a => !audited.contains a)
    let unused := audited.filter (fun a => !found.contains a)
    unless unexpected.isEmpty && unused.isEmpty do
      throwError "TRUST BASE CHANGED for {label} — TrustBase.lean is out of date.\n\
        Checked the {theorems.length} theorems in {ns}.\n\
        New assumptions not in the audited list: {unexpected.toList}\n\
        Audited assumptions no longer used: {unused}"
